Repository bootstrap-vue/bootstrap-vue, pull requests merged in 2018-11, with the labels that each got.

#2120 feat(form-input): support custom-range input + validation and input styles
  package.json
  src/components/form-input/README.md
  src/components/form-input/form-input-type-color.css
  src/components/form-input/form-input-type-range.css
  src/components/form-input/form-input.css
  src/components/form-input/form-input.js
  src/components/form-input/form-input.spec.js
  src/components/input-group/README.md
Labels: Type: Enhancement, Type: Fix, Version: 2.x

#2129 feat(security): Strip HTML script tags before inserting content into DOM. Fixes #1974,#1665
  src/components/button-group/button-group.js
  src/components/card/card-body.js
  src/components/dropdown/dropdown.js
  src/components/form-group/form-group.js
  src/components/input-group/input-group.js
  src/components/jumbotron/jumbotron.js
  src/components/modal/modal.js
  src/components/nav/nav-item-dropdown.js
  src/components/progress/progress-bar.js
  src/components/table/README.md
  src/components/table/table.js
  src/mixins/form-options.js
  src/mixins/pagination.js
  src/utils/strip-scripts.js
Labels: Priority: Medium, Type: Fix, Version: 2.x

#2161 fix(safeId): trigger id creation/update after mount (fixes #1978)
  src/mixins/id.js
Labels: Type: Fix, Version: 2.x

#2050 fix(modal): clear modal paddingLeft and paddingRight if no Scrollbar(s) in adjustDialog().
  src/components/modal/modal.js
Labels: Status: Review Needed

#2164 [WIP] feat(modal): Support multiple modals open at once
  src/components/modal/README.md
  src/components/modal/modal.js
  src/components/modal/modal.spec.js
Labels: Type: Enhancement, Version: 2.x

#2167 fix(form-state): explicitly handle when state is set to empty string. fixes #2166
  src/components/form-input/form-input.spec.js
  src/mixins/form-state.js
Labels: Type: Fix, Version: 2.x

#2168 fix(form-file): Add prop to allow customization of browse button text. fixes #2143
  src/components/form-file/README.md
  src/components/form-file/form-file.css
  src/components/form-file/form-file.js
Labels: Status: WIP, Type: Enhancement, Version: 2.x

#2172 feat(forms): add form prop to all inputs. fixes #2154
  src/components/form-checkbox/form-checkbox-group.js
  src/components/form-checkbox/form-checkbox.js
  src/components/form-file/form-file.js
  src/components/form-input/form-input.js
  src/components/form-input/form-input.spec.js
  src/components/form-radio/form-radio-group.js
  src/components/form-radio/form-radio.js
  src/components/form-select/form-select.js
  src/components/form-textarea/form-textarea.js
  src/mixins/form-radio-check.js
  src/mixins/form.js
Labels: Priority: Medium, Status: WIP, Type: Enhancement, Version: 2.x

#2176 fix(docs): Fix console errors and improve `play` directive
  docs/assets/css/styles.css
  docs/markdown/reference/validation/README.md
  docs/nuxt.config.js
  docs/plugins/play.js
  package.json
  src/components/form-file/README.md
  src/components/tabs/README.md
  yarn.lock
Labels: Status: WIP, Type: Docs, Type: Fix, Version: 2.x

#2177 fix(docs): fix playground issues. fixes #1843
  docs/components/codemirror.vue
  docs/pages/play.vue
Labels: Status: WIP, Type: Docs, Type: Fix, Version: 2.x

#2193 docs(playground): improve console overrides
  docs/pages/play.vue
Labels: Type: Docs

#2196 feat(table): Add table-busy slot for loading status. Closes #1859
  src/components/table/README.md
  src/components/table/package.json
  src/components/table/table-busy.spec.js
  src/components/table/table.js
Labels: Type: Enhancement, Type: Feature request, Version: 2.x

#2111 [WIP] fix(form-textarea): Bug fixes and features
  src/components/form-textarea/README.md
  src/components/form-textarea/fixtures/form-textarea.html
  src/components/form-textarea/form-textarea.js
  src/components/form-textarea/form-textarea.spec.js
  src/components/form-textarea/package.json
  src/mixins/form-text.js
Labels: Status: WIP, Type: Enhancement, Type: Fix, Version: 2.x

#2205 fix(alert): target custom transition CSS to just the alert component
  src/components/alert/alert.css
Labels: Priority: High, Type: Fix, Version: 2.x

#2204 feat(form-input): Use new form-text mixin and add trim and number modifiers
  src/components/form-input/README.md
  src/components/form-input/form-input.js
  src/components/form-input/form-input.spec.js
  src/components/form-input/package.json
  src/components/form-textarea/README.md
  src/components/form-textarea/form-textarea.js
  src/mixins/form-text.js
Labels: Type: Enhancement, Type: Feature, Type: Fix, Type: Unit Testing, Version: 2.x

#2211 fix(modal): Handle enforce focus when modals are stacked (Fixes #2175)
  src/components/modal/modal.js
Labels: Type: Fix

#2214 feat(table): Remove need to add `.stop` modifier on slot inputs/links/buttons
  src/components/table/README.md
  src/components/table/table.js
Labels: Status: WIP, Type: Enhancement, Version: 2.x

#2215 fix(modal): better enforce focus handler.
  src/components/modal/modal.js
  src/utils/dom.js
Labels: Status: WIP

#2216 feat(table): initial SCSS file
  src/components/table/_variables.scss
  src/components/table/table.css
  src/components/table/table.js
  src/components/table/table.scss
  src/components/table/table.spec.js
Labels: Status: WIP

#2217 feat(form-input): initial SCSS file
  src/components/form-input/_variables.scss
  src/components/form-input/form-input-type-color.css
  src/components/form-input/form-input.css
  src/components/form-input/form-input.js
  src/components/form-input/form-input.scss
  src/components/table/table.scss
Labels: Status: WIP

#2218 feat(css): create SCSS versions of CSS
  src/components/alert/_variables.scss
  src/components/alert/alert.scss
  src/components/dropdown/_variables.scss
  src/components/dropdown/dropdown.scss
  src/components/form-file/_variables.scss
  src/components/form-file/form-file.scss
  src/components/input-group/_variables.scss
  src/components/input-group/input-group.scss
Labels: Status: WIP

#2223 docs(modal): minor update on multiple modal support
  src/components/modal/README.md
Labels: Type: Docs
