Repository bootstrap-vue/bootstrap-vue, pull requests merged in 2018-12, with the labels that each got.

#2238 feat(build): replace uglify-es with terser
  package.json
  scripts/build
Labels: Type: Fix, Version: 2.x

#2239 fix(scss): import _input-group.scss once at most
  src/components/input-group/_input-group.scss
Labels: Type: Fix, Type: Perf, Version: 2.x

#2241 feat(form-radio-check): migrate to using provide/inject, add inline props
  package.json
  src/components/form-checkbox/README.md
  src/components/form-checkbox/fixtures/form-checkbox.html
  src/components/form-checkbox/fixtures/form-checkbox.js
  src/components/form-checkbox/form-checkbox-group.js
  src/components/form-checkbox/form-checkbox-group.spec.js
  src/components/form-checkbox/form-checkbox.js
  src/components/form-checkbox/form-checkbox.spec.js
  src/components/form-radio/README.md
  src/components/form-radio/fixtures/form-radio.html
  src/components/form-radio/fixtures/form-radio.js
  src/components/form-radio/form-radio-group.js
  src/components/form-radio/form-radio-group.spec.js
  src/components/form-radio/form-radio.js
  src/components/form-radio/form-radio.spec.js
  src/mixins/form-radio-check-group.js
  src/mixins/form-radio-check.js
  src/utils/loose-index-of.js
Labels: Type: Enhancement, Type: Feature, Type: Fix, Type: Perf, Version: 2.x

#2254 fix(table): Emit v-model input event only when computedItems changes (closes #2231)
  src/components/table/table.js
Labels: Status: WIP, Type: Enhancement, Type: Fix, Version: 2.x

#2255 fix(docs): improve CSS load ordering
  docs/assets/css/styles.css
  docs/nuxt.config.js
  docs/plugins/bootstrap-vue.js
Labels: Type: Docs

#2257 feat(form-select): Expose focus and blur methods (Closes #2237)
  src/components/form-select/form-select.js
Labels: Type: Enhancement, Version: 2.x

#2252 fix(dropdown): Menu focusout close handling
  src/components/dropdown/dropdown.js
  src/components/link/link.js
  src/components/nav/nav-item-dropdown.js
  src/mixins/click-out.js
  src/mixins/dropdown.js
  src/mixins/focus-in.js
Labels: Status: WIP, Type: Fix

#2259 feat(modal): Make stackable optional
  src/components/modal/README.md
  src/components/modal/modal.js
Labels: Type: Enhancement, Version: 2.x

#2258 feat(form-group): Add multiple breakpoint support for label (Closes #2230)
  src/components/form-group/README.md
  src/components/form-group/fixtures/form-group.html
  src/components/form-group/form-group.js
  src/components/form-group/package.json
  src/components/popover/README.md
  src/components/table/README.md
Labels: Type: Enhancement, Type: Fix, Version: 2.x

#2267 fix(table): Clear selection when data change
  src/components/table/table.js
Labels: Type: Fix, Version: 2.x

#2274 fix(docs): guarantee css load order
  docs/assets/css/_bootstrap-vue.scss
  docs/assets/css/main.scss
  docs/assets/css/styles.css
  docs/nuxt.config.js
  docs/plugins/bootstrap-vue.js
  package.json
Labels: Status: WIP

#2282 chore(docs): Pass options to markdown loader for heading IDs
  docs/nuxt.config.js
Labels: Type: Docs, Type: Fix

#2285 chore(docs): Move CSS imports back to nuxt.config.js
  docs/assets/css/_bootstrap-vue.scss
  docs/assets/css/main.scss
  docs/nuxt.config.js
Labels: Type: Docs, Type: Enhancement, Version: 2.x

#2286 feat(docs): use babel-standalone in playground/v-play to support IE
  docs/assets/css/styles.css
  docs/nuxt.config.js
  docs/pages/play.vue
  docs/plugins/play.js
  docs/utils/compile-js.js
  package.json
Labels: Status: Browser Bug, Type: Docs, Type: Enhancement

#2293 feat(form-checkbox): support custom switch styling
  src/components/form-checkbox/README.md
  src/components/form-checkbox/_form-checkbox.scss
  src/components/form-checkbox/form-checkbox-group.js
  src/components/form-checkbox/form-checkbox.js
  src/components/form-checkbox/form-checkbox.spec.js
  src/components/form-checkbox/index.scss
  src/mixins/form-radio-check.js
Labels: Type: Feature, Version: 2.x

#2294 feat(docs): conditionally load babel-standalone only on browsers that need transpilation
  docs/pages/play.vue
  docs/plugins/play.js
  docs/utils/needs-transpiler.js
Labels: Type: Docs, Type: Enhancement, Version: 2.x

#2300 feat(table): add borderless prop
  src/components/table/README.md
  src/components/table/table.js
Labels: Type: Feature, Version: 2.x

#2299 fix(pagination pagination-nav): v-model active class fix + keypress click fix (Fixes #1985, #1629)
  src/components/pagination-nav/README.md
  src/components/pagination-nav/fixtures/pagination-nav.html
  src/components/pagination-nav/fixtures/pagination-nav.js
  src/components/pagination-nav/pagination-nav.js
  src/components/pagination/README.md
  src/components/pagination/fixtures/pagination.html
  src/components/pagination/fixtures/pagination.js
  src/components/pagination/pagination.js
  src/mixins/pagination.js
Labels: Status: WIP, Type: Fix, Version: 2.x

#2301 feat(dropdown): support 'href', 'to' and 'variant' in split button mode (Closes #1960)
  src/components/dropdown/README.md
  src/components/dropdown/dropdown.js
  src/components/dropdown/fixtures/dropdown.html
Labels: Type: Enhancement, Version: 2.x

#2306 feat(spinner): Pre-Release Bootstrap V4.2 spinners
  src/components/index.js
  src/components/index.scss
  src/components/spinner/README.md
  src/components/spinner/_spinner.scss
  src/components/spinner/index.js
  src/components/spinner/index.scss
  src/components/spinner/package.json
  src/components/spinner/spinner.js
  src/components/spinner/spinner.spec.js
Labels: Type: Feature, Version: 2.x

#2313 feat(list-group): add striped support
  src/components/index.scss
  src/components/list-group/README.md
  src/components/list-group/_list-group.scss
  src/components/list-group/fixtures/list-group.html
  src/components/list-group/index.scss
  src/components/list-group/list-group.js
Labels: Type: Enhancement, Type: Feature, Version: 2.x

#2343 chore(form-checkbox): remove interim 4.2 switch style scss
  src/components/form-checkbox/README.md
  src/components/form-checkbox/_form-checkbox.scss
  src/components/form-checkbox/index.scss
Labels: Version: 2.x

#2344 chore(form-input): remove interim fixes for disabled range inputs
  src/components/form-input/_form-input.scss
Labels: Version: 2.x

#2348 docs(modal): document v4.2 modal size xl
  src/components/modal/README.md
Labels: Type: Docs, Version: 2.x

#2369 docs(card): document responsive horizontal layout (closes #2364)
  src/components/card/README.md
Labels: Type: Docs, Version: 2.x

#2370 fix(docs): Update links to Bootstrap V4.2
  docs/markdown/intro/README.md
  docs/markdown/reference/theming/README.md
  docs/markdown/reference/utility-classes/README.md
  src/components/form/README.md
Labels: Status: Upstream, Type: Docs, Version: 2.x

#2375 feat(card): new helper sub-components
  src/components/card/README.md
  src/components/card/card-body.js
  src/components/card/card-sub-title.js
  src/components/card/card-text.js
  src/components/card/card-text.spec.js
  src/components/card/card-title.js
  src/components/card/index.js
  src/components/card/package.json
Labels: Type: Enhancement, Type: Feature, Version: 2.x
