Repository bootstrap-vue/bootstrap-vue, pull requests merged in 2018-10, with the labels that each got.

#2064 feat(table): Support contextmenu event binding for table rows
  src/components/table/package.json
  src/components/table/table.js
  src/components/table/table.spec.js
Labels: Status: Changes needed, Status: Review Needed, Type: Enhancement

#1874 feat(table): Add row-unhovered event
  src/components/table/package.json
  src/components/table/table.js
Labels: Status: Review Needed, Type: Enhancement

#2106 fix(form-group): add missing disabled prop
  src/components/form-group/README.md
  src/components/form-group/form-group.js
Labels: Type: Fix

#2008 fix(form-file): issue with "accept" values (fixes #1526, reverts #2028)
  src/components/form-file/form-file.js
Labels: Status: Review Needed

#1994 feat(table): pass sortDesc to user provided sortCompare routine
  src/components/table/README.md
  src/components/table/table.js
Labels: Type: Enhancement

#2091 Show v-model usage for b-alert
  src/components/alert/README.md
  src/components/alert/alert.js
Labels: Status: Changes needed, Status: Review Needed
