Repository bootstrap-vue/bootstrap-vue, pull requests merged in 2019-03, with the labels that each got.

#2739 chore: util and mixin for normalizing scoped and un-scoped slots
  src/mixins/normalize-slot.js
  src/utils/normalize-slot.js
  src/utils/normalize-slot.spec.js
Labels: Status: WIP, Type: Enhancement

#2740 feat(table): make some slots available either as scoped or unscoped
  src/components/table/README.md
  src/components/table/package.json
  src/components/table/table.js
  src/mixins/normalize-slot.js
Labels: Type: Enhancement

#2741 perf(table): minor tweaks to primary key usage
  src/components/table/README.md
  src/components/table/table.js
Labels: Type: Enhancement, Type: Fix, Type: Perf

#2755 fix(nav-item): move listeners to link element
  src/components/nav/nav-item.js
  src/components/nav/nav-item.spec.js
Labels: Type: Fix

#2757 fix(pagination): avoid using domProps innerText (Addresses #2744)
  src/components/pagination-nav/README.md
  src/components/pagination/README.md
  src/components/pagination/pagination.spec.js
  src/mixins/pagination.js
Labels: Type: Fix, Type: Unit Testing

#2761 fix(radio/check group): remove size class from the group container (Closes #2743)
  src/mixins/form-radio-check-group.js
Labels: Type: Fix

#2765 feat(modal): add variant prop for header close button
  src/components/modal/modal.js
Labels: Type: Feature

#2773 chore(docs): minor updates to tab docs (Closes #2772)
  src/components/tabs/README.md
Labels: Type: Docs

#2775 fix(util/html): ensure argument is a string (Closes #2770)
  src/utils/html.js
Labels: Type: Fix

#2764 feat(util/get, table): handle edge case where user has dot in actual item data field key (Closes #2762)
  src/utils/get.js
  src/utils/get.spec.js
Labels: Type: Enhancement, Type: Fix

#2788 chore(docs): fix typo in input-group example (Closes #2786)
  src/components/input-group/README.md
Labels: Type: Docs

#2792 chore(docs): fix prettier/eslint warnings
  docs/pages/play.vue
Labels: Type: Docs

#2801 fix(table): don't emit row/head-clicked when user is selecting text (Closes #2791)
  src/components/table/table.js
  src/components/table/table.spec.js
Labels: Type: Fix

#2804 fix(table): fix detection of text selection
  src/components/table/table.js
Labels: Type: Fix

#2813 fix(util/loose-equal): handle comparing sparse arrays
  src/utils/loose-equal.js
  src/utils/loose-equal.spec.js
Labels: Type: Fix

#2805 chore(table): break out code into helper modules and add additional tests
  src/components/table/_table.scss
  src/components/table/helpers/constants.js
  src/components/table/helpers/default-sort-compare.js
  src/components/table/helpers/default-sort-compare.spec.js
  src/components/table/helpers/filter-event.js
  src/components/table/helpers/mixin-bottom-row.js
  src/components/table/helpers/mixin-busy.js
  src/components/table/helpers/mixin-caption.js
  src/components/table/helpers/mixin-colgroup.js
  src/components/table/helpers/mixin-empty.js
  src/components/table/helpers/mixin-provider.js
  src/components/table/helpers/mixin-selectable.js
  src/components/table/helpers/mixin-tbody-row.js
  src/components/table/helpers/mixin-tbody.js
  src/components/table/helpers/mixin-tfoot.js
  src/components/table/helpers/mixin-thead.js
  src/components/table/helpers/mixin-top-row.js
  src/components/table/helpers/normalize-fields.js
  src/components/table/helpers/normalize-fields.spec.js
  src/components/table/helpers/sanitize-row.js
  src/components/table/helpers/stringify-object-values.js
  src/components/table/helpers/stringify-record-values.js
  src/components/table/helpers/text-selection-active.js
  src/components/table/table-bottom-row.spec.js
  src/components/table/table-caption.spec.js
  src/components/table/table-colgroup.spec.js
  src/components/table/table-row-details.spec.js
  src/components/table/table-selectable.spec.js
  src/components/table/table-sort.spec.js
  src/components/table/table-tbody-row-events.spec.js
  src/components/table/table-tbody-transition.spec.js
  src/components/table/table-tfoot-events.spec.js
  src/components/table/table-thead-events.spec.js
  src/components/table/table-thead-top.spec.js
  src/components/table/table-top-row.spec.js
  src/components/table/table.js
  src/mixins/id.js
  src/utils/loose-equal.spec.js
  tests/utils.js
Labels: Type: Enhancement, Type: Perf

#2824 fix(table): allow string for pagination prop types (closes #2821)
  src/components/table/table.js
Labels: Type: Fix

#2834 fix(pagination-nav): fix race condition with clicking prev/next buttons
  src/components/pagination-nav/pagination-nav.js
  src/components/pagination-nav/pagination-nav.spec.js
  src/components/pagination/pagination.spec.js
Labels: Type: Fix

#2840 feat(docs): get recommended `Vue.js` and `Bootstrap` version from `package.json`
  docs/content/index.js
  docs/markdown/intro/README.md
  docs/pages/docs/index.js
  docs/pages/docs/index.vue
  docs/utils/index.js
Labels: Type: Docs, Type: Enhancement

#2842 fix(form-radio/form-checkbox): ensure prop required propagated in group mode (fixes #2839)
  src/components/form-checkbox/form-checkbox-group.spec.js
  src/components/form-radio/form-radio-group.spec.js
  src/mixins/form-radio-check.js
  src/utils/dom.spec.js
Labels: Type: Fix

#2843 chore(docs): minor tweaks to Sidebar and TOC
  docs/assets/scss/styles.scss
  docs/components/toc.vue
  docs/content/index.js
Labels: Type: Docs

#2844 fix(carousel): fix touchmove handler to re-enable swipe gestures
  src/components/carousel/carousel.js
Labels: Type: Fix

#2851 chore(tests): call wrapper.destroy() after each test to release DOM and memory
  src/components/carousel/carousel-slide.spec.js
  src/components/dropdown/dropdown-item-button.spec.js
  src/components/dropdown/dropdown-item.spec.js
  src/components/form-checkbox/form-checkbox-group.spec.js
  src/components/form-checkbox/form-checkbox.spec.js
  src/components/form-file/form-file.spec.js
  src/components/form-input/form-input.spec.js
  src/components/form-radio/form-radio-group.spec.js
  src/components/form-radio/form-radio.spec.js
  src/components/form-textarea/form-textarea.spec.js
  src/components/table/table-bottom-row.spec.js
  src/components/table/table-busy.spec.js
  src/components/table/table-caption.spec.js
  src/components/table/table-colgroup.spec.js
  src/components/table/table-primarykey.spec.js
  src/components/table/table-provider.spec.js
  src/components/table/table-row-details.spec.js
  src/components/table/table-selectable.spec.js
  src/components/table/table-sort.spec.js
  src/components/table/table-tbody-row-events.spec.js
  src/components/table/table-tbody-transition.spec.js
  src/components/table/table-tfoot-events.spec.js
  src/components/table/table-thead-events.spec.js
  src/components/table/table-thead-top.spec.js
  src/components/tabs/tab.spec.js
  src/components/tabs/tabs.spec.js
  src/utils/dom.spec.js
Labels: Status: WIP, Type: Perf, Type: Unit Testing

#2836 feat(pagination-nav): autodetect current page based on $route or page URL
  package.json
  src/_utilities.scss
  src/components/index.scss
  src/components/link/link.js
  src/components/link/link.spec.js
  src/components/pagination-nav/README.md
  src/components/pagination-nav/_pagination-nav.scss
  src/components/pagination-nav/fixtures/pagination-nav.html
  src/components/pagination-nav/fixtures/pagination-nav.js
  src/components/pagination-nav/index.scss
  src/components/pagination-nav/package.json
  src/components/pagination-nav/pagination-nav.js
  src/components/pagination-nav/pagination-nav.spec.js
  src/components/pagination/README.md
  src/components/pagination/_pagination.scss
  src/components/pagination/index.scss
  src/components/pagination/package.json
  src/components/pagination/pagination.js
  src/components/pagination/pagination.spec.js
  src/index.scss
  src/mixins/pagination.js
  src/utils/router.js
  src/utils/router.spec.js
  yarn.lock
Labels: Type: Feature

#2865 fix(table): fix range selection
  src/components/table/README.md
  src/components/table/_table.scss
  src/components/table/helpers/mixin-selectable.js
  src/components/table/helpers/mixin-tbody-row.js
  src/components/table/table-selectable.spec.js
  src/components/table/table.js
Labels: Type: Fix

#2870 feat(table): add basic keyboard nav when table has row-clicked handler or is selctable (closes #2869)
  src/components/table/README.md
  src/components/table/helpers/mixin-tbody-row.js
  src/components/table/table-tbody-row-events.spec.js
  src/components/table/table.spec.js
Labels: Type: Enhancement, Type: Feature

#2872 chore(tests): more tests
  src/components/breadcrumb/fixtures/breadcrumb.html
  src/components/breadcrumb/fixtures/breadcrumb.js
  src/components/button-toolbar/button-toolbar.js
  src/components/button-toolbar/button-toolbar.spec.js
  src/components/button-toolbar/fixtures/button-toolbar.html
  src/components/button-toolbar/fixtures/button-toolbar.js
  src/components/carousel/carousel-slide.js
  src/components/carousel/carousel.js
  src/components/carousel/carousel.spec.js
  src/components/carousel/fixtures/carousel.html
  src/components/collapse/collapse.js
  src/components/form-file/form-file.js
  src/components/form-group/fixtures/form-group.html
  src/components/form-group/form-group.js
  src/components/form-group/form-group.spec.js
  src/components/progress/progress-bar.spec.js
  src/directives/toggle/toggle.js
Labels: Type: Unit Testing

#2888 feat(carousel): add no-hover-pause prop
  src/components/carousel/README.md
  src/components/carousel/carousel.js
Labels: Type: Feature

#2892 feat(utils/noop): add `noop()` util
  src/components/carousel/carousel.js
  src/utils/noop.js
  src/utils/tooltip.class.js
Labels: Type: Enhancement

#2884 fix(table): fix broken aria-labels for sortable columns + break out code into additional mixins + tests
  src/components/form-select/form-select.spec.js
  src/components/pagination/pagination.spec.js
  src/components/table/README.md
  src/components/table/fixtures/table.html
  src/components/table/fixtures/table.js
  src/components/table/helpers/mixin-empty.js
  src/components/table/helpers/mixin-filtering.js
  src/components/table/helpers/mixin-items.js
  src/components/table/helpers/mixin-pagination.js
  src/components/table/helpers/mixin-provider.js
  src/components/table/helpers/mixin-sorting.js
  src/components/table/helpers/mixin-tbody-row.js
  src/components/table/helpers/mixin-thead.js
  src/components/table/table-busy.spec.js
  src/components/table/table-caption.spec.js
  src/components/table/table-colgroup.spec.js
  src/components/table/table-filtering.spec.js
  src/components/table/table-pagination.spec.js
  src/components/table/table-primarykey.spec.js
  src/components/table/table-provider.spec.js
  src/components/table/table-row-details.spec.js
  src/components/table/table-selectable.spec.js
  src/components/table/table-sort.spec.js
  src/components/table/table-sorting.spec.js
  src/components/table/table-tbody-bottom-row.spec.js
  src/components/table/table-tbody-row-events.spec.js
  src/components/table/table-tbody-top-row.spec.js
  src/components/table/table-tbody-transition.spec.js
  src/components/table/table-tfoot-events.spec.js
  src/components/table/table-thead-events.spec.js
  src/components/table/table-thead-top.spec.js
  src/components/table/table.js
  src/components/table/table.spec.js
  src/utils/startcase.spec.js
  tests/utils.js
Labels: Type: Fix, Type: Perf

#2896 docs(form-checkbox): fixed closing `<b-form-valid-feedback>` tag in contextual state and validation example
  src/components/form-checkbox/README.md
Labels: Type: Docs

#2897 fix(table): fix SSR mismatch errors
  src/components/table/helpers/mixin-thead.js
Labels: Type: Fix, Type: SSR

#2901 fix(utils/dom): update `closest()` routine to support SVG in IE11 (closes #2900)
  src/utils/dom.js
Labels: Type: Fix

#2899 feat(forms): new b-form-datalist component
  src/components/form-input/README.md
  src/components/form/README.md
  src/components/form/form-datalist.js
  src/components/form/form-datalist.spec.js
  src/components/form/index.js
  src/components/form/package.json
Labels: Type: Enhancement, Type: Feature

#2902 feat(form-file): add in prop and scoped slot for formatting selected file names
  src/components/form-file/README.md
  src/components/form-file/form-file.js
  src/components/form-file/form-file.spec.js
  src/components/form-file/package.json
Labels: Type: Enhancement

#2904 chore(docs): fix typo in collapse accordion example (closes #2903)
  src/components/collapse/README.md
Labels: Type: Docs

#2826 feat: add BOOTSTRAP_VUE_NO_WARN environment variable to hide warnings
  docs/markdown/misc/settings/README.md
  docs/markdown/misc/settings/meta.json
  src/utils/env.js
  src/utils/warn.js
  src/utils/warn.spec.js
Labels: Type: Feature

#2910 fix(dropdown): fix `no-caret` prop when dropleft (fixes #2909)
  src/components/dropdown/_dropdown.scss
Labels: Type: Fix

#2927 chore: directives code cleanup
  docs/nuxt.config.js
  src/directives/modal/modal.js
  src/directives/modal/modal.spec.js
  src/directives/popover/popover.js
  src/directives/popover/popover.spec.js
  src/directives/scrollspy/scrollspy.js
  src/directives/scrollspy/scrollspy.spec.js
  src/directives/toggle/toggle.js
  src/directives/toggle/toggle.spec.js
  src/directives/tooltip/tooltip.js
  src/directives/tooltip/tooltip.spec.js
Labels: Type: Enhancement

#2940 fix(docs): fix issue with table docs page (closes #2939)
  docs/components/componentdoc.vue
  docs/components/importdoc.vue
  docs/components/search.vue
  docs/components/toc.vue
  docs/plugins/docs-mixin.js
  src/components/table/README.md
  src/components/table/helpers/mixin-filtering.js
Labels: Type: Docs, Type: Fix

#2943 fix(link): support handling multiple click event listeners (fixes #2938)
  src/components/link/fixtures/link.html
  src/components/link/fixtures/link.js
  src/components/link/link.js
  src/components/link/link.spec.js
Labels: Type: Fix

#2936 fix(form-group): don't render aria-labelledby on group when label-for provided (fixes #2933)
  src/components/form-group/fixtures/form-group.html
  src/components/form-group/form-group.js
  src/components/form-group/form-group.spec.js
Labels: Type: Accessibility, Type: Fix

#2947 fix(docs): add back missing leading slash to search urls (closes #2945)
  docs/components/search.vue
Labels: Type: Docs, Type: Fix

#2949 chore: docs search hotfix
  docs/components/search.vue
Labels: Type: Docs, Type: Fix

#2953 feat(scrollspy): support when vue-router is in `hash` based route mode (closes #2722)
  src/directives/scrollspy/README.md
  src/directives/scrollspy/scrollspy.class.js
Labels: Type: Enhancement

#2954 chore(unit testing): more test conversions
  src/components/card/card.spec.js
  src/components/card/fixtures/card.html
  src/components/card/fixtures/card.js
  src/components/embed/embed.spec.js
  src/components/embed/fixtures/embed.html
  src/components/embed/fixtures/embed.js
Labels: Type: Unit Testing

#2963 fix(modal): prevent page scroll as modal opens
  src/components/modal/modal.js
Labels: Type: Fix

#2957 chore(docs): add meta description for docs pages
  docs/content/index.js
  docs/markdown/misc/changelog/meta.json
  docs/markdown/misc/contributing/meta.json
  docs/markdown/misc/settings/meta.json
  docs/markdown/reference/color-variants/meta.json
  docs/markdown/reference/images/README.md
  docs/markdown/reference/images/meta.json
  docs/markdown/reference/router-links/meta.json
  docs/markdown/reference/size-props/meta.json
  docs/markdown/reference/spacing-classes/meta.json
  docs/markdown/reference/starter-templates/meta.json
  docs/markdown/reference/theming/meta.json
  docs/markdown/reference/utility-classes/meta.json
  docs/markdown/reference/validation/meta.json
  docs/pages/play.vue
  docs/plugins/docs-mixin.js
  src/components/alert/package.json
  src/components/badge/package.json
  src/components/breadcrumb/package.json
  src/components/button-group/package.json
  src/components/button-toolbar/package.json
  src/components/button/package.json
  src/components/card/package.json
  src/components/carousel/package.json
  src/components/collapse/package.json
  src/components/dropdown/package.json
  src/components/embed/package.json
  src/components/form-checkbox/package.json
  src/components/form-file/package.json
  src/components/form-group/package.json
  src/components/form-input/package.json
  src/components/form-radio/package.json
  src/components/form-select/package.json
  src/components/form-textarea/package.json
  src/components/form/package.json
  src/components/image/package.json
  src/components/input-group/package.json
  src/components/jumbotron/package.json
  src/components/layout/package.json
  src/components/link/package.json
  src/components/list-group/package.json
  src/components/media/package.json
  src/components/modal/package.json
  src/components/nav/package.json
  src/components/navbar/package.json
  src/components/pagination-nav/package.json
  src/components/pagination/package.json
  src/components/popover/package.json
  src/components/progress/package.json
  src/components/spinner/package.json
  src/components/table/package.json
  src/components/tabs/package.json
  src/components/tooltip/package.json
  src/directives/popover/package.json
  src/directives/scrollspy/package.json
  src/directives/tooltip/package.json
Labels: Type: Docs

#2966 fix(docs): fix component plugin's included plugins and directives
  docs/components/importdoc.vue
  src/components/collapse/index.js
  src/components/collapse/package.json
  src/components/modal/index.js
  src/components/modal/package.json
  src/components/nav/package.json
  src/components/navbar/package.json
  src/components/popover/index.js
  src/components/popover/package.json
  src/components/tooltip/index.js
  src/components/tooltip/package.json
  src/index.js
  src/utils/plugins.js
Labels: Type: Docs, Type: Perf

#2964 chore: more unit test conversion
  src/components/collapse/fixtures/collapse.html
  src/components/input-group/fixtures/input-group.html
  src/components/input-group/fixtures/input-group.js
  src/components/input-group/input-group-append.spec.js
  src/components/input-group/input-group-prepend.spec.js
  src/components/input-group/input-group-text.spec.js
  src/components/input-group/input-group.spec.js
  src/components/layout/col.js
  src/components/layout/col.spec.js
  src/components/layout/container.spec.js
  src/components/layout/fixtures/col.html
  src/components/layout/fixtures/col.js
  src/components/layout/fixtures/container.html
  src/components/layout/fixtures/container.js
  src/components/layout/fixtures/row.html
  src/components/layout/fixtures/row.js
  src/components/layout/form-row.spec.js
  src/components/layout/row.spec.js
  src/components/list-group/list-group-item.spec.js
  src/components/media/fixtures/media.html
  src/components/media/fixtures/media.js
  src/components/media/media-aside.spec.js
  src/components/media/media-body.spec.js
  src/components/media/media.spec.js
  src/components/nav/nav-item-dropdown.spec.js
  src/components/navbar/fixtures/navbar.html
  src/components/navbar/fixtures/navbar.js
  src/components/navbar/navbar-dropdown.spec.js
  src/components/progress/fixtures/progress.html
  src/components/progress/fixtures/progress.js
Labels: Type: Unit Testing
