Repository bootstrap-vue/bootstrap-vue, pull requests merged in 2019-12, with the labels that each got.

#4439 feat(b-row): add Bootstrap v4.4 row columns support
  src/components/layout/README.md
  src/components/layout/col.js
  src/components/layout/package.json
  src/components/layout/row.js
  src/components/layout/row.spec.js
Labels: Bootstrap v4, Type: Feature

#4409 feat(b-form-tags): new tagged input component
  src/components/form-tags/README.md
  src/components/form-tags/_form-tags.scss
  src/components/form-tags/form-tag.js
  src/components/form-tags/form-tag.spec.js
  src/components/form-tags/form-tags.js
  src/components/form-tags/form-tags.spec.js
  src/components/form-tags/index.d.ts
  src/components/form-tags/index.js
  src/components/form-tags/index.scss
  src/components/form-tags/package.json
  src/components/index.d.ts
  src/components/index.js
  src/components/index.scss
  src/index.js
  src/utils/config-defaults.js
Labels: Type: Custom Component, Type: Feature

#4440 chore: minor tweaks for bootstrap v4.4
  docs/components/anchored-heading.js
  docs/components/section-toc.vue
  docs/markdown/intro/README.md
  docs/nuxt.config.js
  docs/utils/index.js
  src/_utilities.scss
  src/components/dropdown/_dropdown.scss
  src/components/tabs/tab.js
  src/components/tabs/tab.spec.js
Labels: Bootstrap v4, Type: Docs

#4468 fix(b-toast): fix ensureToaster method call when toaster name changes
  src/components/toast/toast.js
Labels: PR: Patch, Type: Fix

#4467 chore(docs): add link to v2.0.0 migration guide in getting started docs
  docs/markdown/intro/README.md
Labels: Type: Docs

#4441 chore: create "listenOnDocument" and "listenOnWindow" mixins
  src/components/modal/modal.js
  src/mixins/listen-on-document.js
  src/mixins/listen-on-document.spec.js
  src/mixins/listen-on-window.js
  src/mixins/listen-on-window.spec.js
Labels: Type: Refactor

#4475 feat(b-dropdown-form): add formClass prop for adding classes to the form element (closes #4474)
  src/components/dropdown/dropdown-form.js
  src/components/dropdown/dropdown-form.spec.js
  src/components/dropdown/package.json
Labels: Type: Feature

#4479 chore: more tweaks for new Bootstrap v4.4 reboot changes
  src/components/form-checkbox/_form-checkbox-group.scss
  src/components/form-checkbox/form-checkbox-group.spec.js
  src/components/form-group/form-group.js
  src/components/form-group/form-group.spec.js
  src/components/form-radio/_form-radio-group.scss
  src/components/form-radio/form-radio-group.spec.js
  src/components/form-tags/README.md
  src/mixins/form-radio-check-group.js
Labels: Bootstrap v4, PR: Patch

#4482 chore: prettify
  CHANGELOG.md
  docs/markdown/intro/README.md
  src/components/collapse/README.md
  src/components/dropdown/_dropdown.scss
  src/components/form-tags/_form-tags.scss
  src/components/table/README.md
Labels: Type: Docs

#4488 feat(b-table): better sort labeling for screen readers (closes #4487)
  src/components/table/helpers/mixin-sorting.js
  src/components/table/helpers/mixin-thead.js
  src/components/table/package.json
  src/components/table/table-sorting.spec.js
Labels: Type: Accessibility

#4484 fix(docs): handle undocumented breaking changes in babel-standalone for IE11
  docs/pages/play.vue
  docs/utils/compile-js.js
  docs/utils/needs-transpiler.js
Labels: Type: Docs, Type: Fix

#4501 chore(docs): fix typo in toast
  src/components/toast/README.md
Labels: Type: Docs, Type: Fix

#4517 fix(docs): correct formatting of <b-modal> `ok-only` prop
  src/components/modal/README.md
Labels: Type: Docs, Type: Fix

#4489 feat(icons): optional icon components
  docs/components/componentdoc.vue
  docs/components/feedback.js
  docs/components/footer.vue
  docs/components/header.vue
  docs/components/icons-table.vue
  docs/components/importdoc.vue
  docs/content/index.js
  docs/markdown/intro/README.md
  docs/pages/docs/icons/index.js
  docs/pages/docs/index.js
  docs/pages/index.vue
  docs/plugins/bootstrap-vue.js
  docs/utils/index.js
  nuxt/index.js
  nuxt/plugin.template.js
  package.json
  scripts/banner.js
  scripts/build.sh
  scripts/create-icons.js
  scripts/create-web-types.js
  scripts/rollup.config.js
  src/browser-icons.js
  src/browser.js
  src/components/modal/README.md
  src/components/toast/_toast.scss
  src/icons-only.js
  src/icons.scss
  src/icons/README.md
  src/icons/_icons.scss
  src/icons/helpers/make-icon.js
  src/icons/icon.js
  src/icons/icons.d.ts
  src/icons/icons.js
  src/icons/icons.spec.js
  src/icons/index.d.ts
  src/icons/index.js
  src/icons/index.scss
  src/icons/package.json
  src/icons/plugin.js
  src/index.d.ts
  src/index.js
  src/index.scss
  src/utils/plugins.js
  src/utils/string.js
  src/utils/string.spec.js
  yarn.lock
Labels: Bootstrap v4, Bootstrap v5, Type: Feature
