Repository bootstrap-vue/bootstrap-vue, pull requests merged in 2019-09, with the labels that each got.

#3996 feat(dropdown): add `role=presentation` to `<li>` elements for improved a11y
  src/components/dropdown/dropdown-divider.js
  src/components/dropdown/dropdown-form.js
  src/components/dropdown/dropdown-group.js
  src/components/dropdown/dropdown-header.js
  src/components/dropdown/dropdown-item-button.js
  src/components/dropdown/dropdown-item.js
  src/components/dropdown/dropdown-text.js
Labels: Type: Accessibility

#4000 docs(b-nav): add example markup for using vue-router/nuxt-child (closes #3999)
  src/components/nav/README.md
Labels: Type: Docs

#4004 fix(b-modal): fix scroll to top issue when modal has `no-fade` set (closes #4003)
  src/components/modal/modal.js
Labels: Type: Fix

#4006 chore(docs): better ARIA compliant `b-nav` + `b-card` examples
  src/components/card/README.md
  src/components/nav/README.md
Labels: Type: Docs

#4013 docs(router-links): add more details to `active-class` and `exact-active-class` props (closes #4012)
  docs/markdown/reference/router-links/README.md
Labels: Type: Docs

#4011 perf(b-table): cache cell slot names each render cycle (addresses #4008)
  src/components/table/helpers/mixin-tbody-row.js
  src/components/table/helpers/mixin-tbody.js
Labels: Type: Perf

#4016 chore(docs): minor adjustments to the table docs
  src/components/table/README.md
Labels: Type: Docs

#4025 fix(b-table, b-table-lite): generate `:key` for `row-details` row based on the `primary-key` field value if available
  src/components/table/helpers/mixin-tbody-row.js
Labels: Type: Enhancement, Type: Fix, Type: Perf

#4024 fix(b-dropdown-*): ensure class bindings are placed on root element for all dropdown sub-components (closes #4022)
  src/components/dropdown/dropdown-divider.js
  src/components/dropdown/dropdown-form.js
  src/components/dropdown/dropdown-group.js
  src/components/dropdown/dropdown-header.js
  src/components/dropdown/dropdown-text.js
Labels: Type: Enhancement, Type: Fix

#4027 feat(b-table, b-table-lite): add new scoped slot `custom-foot` to allow user to create their own table footer (closes #3960)
  src/components/table/README.md
  src/components/table/helpers/mixin-tfoot.js
  src/components/table/package.json
  src/components/table/table-tfoot-custom.spec.js
Labels: Type: Feature

#4029 fix(docs): heading before margin
  docs/assets/scss/styles.scss
Labels: Type: Docs, Type: Fix

#4037 chore(b-toaster): clean out old toaster scss comments
  src/components/toast/_toaster-transition.scss
  src/components/toast/_toaster.scss
Labels: Type: SCSS

#4041 chore(docs): fix slot names in table package.json
  src/components/table/package.json
Labels: Type: Docs

#4042 chore(docs): hotfix slot names in table package.json meta
  src/components/table/package.json
Labels: Type: Docs

#4036 chore(docs): link to options prop details section (closes #4035)
  CHANGELOG.md
  src/components/form-checkbox/README.md
  src/components/form-radio/README.md
  src/components/form-select/README.md
  src/components/form/README.md
Labels: Type: Docs

#4040 chore(docs): switch play.vue to use new `v-slot` syntax and fix card style css scope
  docs/pages/play.vue
Labels: Type: Docs

#4045 chore(docs): minor updates to tooltip/popover docs
  src/components/popover/README.md
  src/components/tooltip/README.md
  src/directives/popover/README.md
  src/directives/tooltip/README.md
Labels: Type: Docs

#4028 chore(nuxt.config.js): update `manifest` to `pwa.manifest`
  docs/nuxt.config.js
Labels: Status: On Hold

#4055 fix(b-media): fix vertical align class when top or bottom selected (fixes #4052)
  src/components/media/media-aside.js
  src/components/media/media-aside.spec.js
  src/components/media/media.spec.js
Labels: PR: Patch, Type: Fix

#4057 fix(v-b-tooltip, v-b-popover): add missing `disabled` config option
  src/directives/popover/README.md
  src/directives/popover/popover.js
  src/directives/tooltip/README.md
  src/directives/tooltip/tooltip.js
Labels: PR: Patch, Type: Fix

#4059 docs(b-nav): add name to default tab route in vue-router example
  src/components/nav/README.md
Labels: PR: Patch, Type: Docs

#4061 docs(accessibility): add sub section on application a11y testing
  docs/markdown/reference/accessibility/README.md
Labels: Type: Docs

#4062 docs(readme): Fixed typo
  src/components/form-select/README.md
Labels: Type: Docs

#4066 fix(docs): closing tag in the first example of the tooltip documentation page
  src/components/tooltip/README.md
Labels: Type: Docs

#4072 chore(docs): ensure opengraph and twitter meta is provided
  docs/nuxt.config.js
Labels: Type: Docs

#4075 fix(tooltip, popover): check `document.body` instead of `document` for IE11 support (fixes #4074)
  src/components/tooltip/helpers/bv-tooltip.js
Labels: PR: Patch, Type: Fix

#4068 fix(b-table): handle filter as an object when using providers and prevent duplicate provider calls on mount (fixes #4065)
  src/components/table/helpers/mixin-filtering.js
  src/components/table/table-filtering.spec.js
  src/components/table/table-provider.spec.js
Labels: PR: Patch, Type: Fix

#4076 fix(v-b-tooltip, v-b-popover): don't show if no title/content provided (closes #4064)
  src/components/popover/helpers/bv-popover-template.js
  src/components/tooltip/helpers/bv-tooltip.js
  src/directives/popover/README.md
  src/directives/popover/popover.js
  src/directives/tooltip/README.md
  src/directives/tooltip/tooltip.js
  src/directives/tooltip/tooltip.spec.js
Labels: PR: Patch, Type: Enhancement, Type: Fix

#4086 docs: add opencolletive backers/donors on landing page
  CONTRIBUTING.md
  docs/components/backers-donors.vue
  docs/pages/index.vue
Labels: Type: Docs

#4090 docs(b-form-radio): add note that `unchecked-value` is not submitted via native form submit (closes #4089)
  src/components/form-checkbox/README.md
Labels: Type: Docs

#4060 chore: release 2.0.1
  CHANGELOG.md
  CONTRIBUTING.md
  docs/components/backers-donors.vue
  docs/markdown/reference/accessibility/README.md
  docs/markdown/reference/validation/README.md
  docs/nuxt.config.js
  docs/pages/index.vue
  docs/pages/play.vue
  package.json
  src/components/form-checkbox/README.md
  src/components/form-file/README.md
  src/components/form-radio/README.md
  src/components/form-select/README.md
  src/components/form/README.md
  src/components/media/media-aside.js
  src/components/media/media-aside.spec.js
  src/components/media/media.spec.js
  src/components/modal/helpers/bv-modal.js
  src/components/modal/modal.js
  src/components/nav/README.md
  src/components/pagination-nav/pagination-nav.js
  src/components/popover/README.md
  src/components/popover/helpers/bv-popover-template.js
  src/components/table/README.md
  src/components/table/helpers/mixin-filtering.js
  src/components/table/helpers/mixin-provider.js
  src/components/table/table-filtering.spec.js
  src/components/table/table-provider.spec.js
  src/components/table/table.js
  src/components/toast/_toaster-transition.scss
  src/components/toast/_toaster.scss
  src/components/toast/toast.js
  src/components/tooltip/README.md
  src/components/tooltip/helpers/bv-tooltip.js
  src/directives/popover/README.md
  src/directives/popover/popover.js
  src/directives/tooltip/README.md
  src/directives/tooltip/tooltip.js
  src/directives/tooltip/tooltip.spec.js
  src/mixins/pagination.js
  yarn.lock
Labels: PR: Patch

#4093 chore(docs): fix table example typo
  src/components/table/README.md
Labels: Type: Docs

#4097 docs(table): document table `active` variant in selectable rows section
  docs/markdown/reference/color-variants/README.md
  src/components/table/README.md
Labels: PR: Patch, Type: Docs

#4098 fix(tables): add in missing Bootstrap variant class `bg-active` for dark tables
  src/_variables.scss
  src/components/table/_table.scss
Labels: PR: Patch, Type: Enhancement, Type: Fix, Type: SCSS

#4108 docs(modal): add section on footer button sizing
  src/components/modal/README.md
Labels: PR: Patch, Type: Docs

#4103 docs: add 3rd party components/library links to misc docs
  docs/markdown/misc/third-party/README.md
  docs/markdown/misc/third-party/meta.json
Labels: PR: Patch, Status: WIP, Type: Docs

#4127 fix(tables): ensure row variant `active` (class `table-active`) takes precedence over other row variants (addresses #3008)
  src/components/table/README.md
  src/components/table/_table.scss
Labels: PR: Patch, Type: Fix

#4133 fix(b-popover, b-tooltip): ensure `boundary-padding` is passed to popper instance (fixes #4131)
  src/components/popover/package.json
  src/components/popover/popover.js
  src/components/tooltip/helpers/bv-tooltip.js
  src/components/tooltip/package.json
  src/components/tooltip/tooltip.js
  src/directives/popover/popover.js
  src/directives/tooltip/tooltip.js
Labels: PR: Patch, Type: Fix

#4136 docs(b-toast): show example of using `<b-alert>` as an alternative to a toast
  src/components/toast/README.md
Labels: PR: Patch, Type: Docs

#4099 chore: release v2.0.2
  CHANGELOG.md
  docs/markdown/misc/third-party/README.md
  docs/markdown/misc/third-party/meta.json
  docs/markdown/reference/color-variants/README.md
  package.json
  src/_variables.scss
  src/components/collapse/README.md
  src/components/collapse/collapse.js
  src/components/modal/README.md
  src/components/popover/package.json
  src/components/popover/popover.js
  src/components/table/README.md
  src/components/table/_table.scss
  src/components/toast/README.md
  src/components/tooltip/helpers/bv-tooltip.js
  src/components/tooltip/package.json
  src/components/tooltip/tooltip.js
  src/directives/popover/README.md
  src/directives/popover/popover.js
  src/directives/tooltip/README.md
  src/directives/tooltip/tooltip.js
  yarn.lock
Labels: PR: Patch

#4139 fix(dropdown): focus-out handling when new focus comes from another `dropdown-toggle` (closes #4113)
  src/components/dropdown/dropdown.spec.js
  src/mixins/dropdown.js
  src/utils/dom.js
  src/utils/dom.spec.js
Labels: PR: Patch, Type: Fix

#4144 docs: clarify the autofocus prop
  src/components/form-checkbox/README.md
  src/components/form-file/README.md
  src/components/form-input/README.md
  src/components/form-radio/README.md
  src/components/form-select/README.md
  src/components/form-textarea/README.md
Labels: PR: Patch, Type: Docs

#4147 fix(table): disable sticky header max-height on printers
  src/components/table/_table.scss
Labels: PR: Patch, Type: Fix, Type: SCSS

#4148 chore(docs): update meta for getting started page
  docs/markdown/intro/meta.json
  docs/pages/docs/index.js
Labels: PR: Patch, Type: Docs

#4156 perf(tables): make `b-th` extend `b-td` instead of using functional wrappers
  src/components/table/helpers/table-cell.js
  src/components/table/td.js
  src/components/table/th.js
Labels: PR: Patch, Type: Perf, Type: Refactor

#4145 docs: add quick links to docs pages for small screens and add section table of contents indexes
  docs/components/doc-breadcrumbs.vue
  docs/components/feedback.js
  docs/components/quick-links.vue
  docs/components/search.vue
  docs/components/section-toc.vue
  docs/components/section.js
  docs/components/sidebar.vue
  docs/components/toc.vue
  docs/content/index.js
  docs/layouts/docs.js
  docs/markdown/intro/README.md
  docs/markdown/reference/spacing-classes/meta.json
  docs/pages/docs/components/index.js
  docs/pages/docs/directives/index.js
  docs/pages/docs/misc/index.js
  docs/pages/docs/reference/index.js
  docs/plugins/docs-mixin.js
  src/components/link/package.json
  src/components/pagination/package.json
Labels: Type: Docs, Type: Perf

#4164 perf(table): improve provide/inject performance (addresses #4155)
  src/components/table/tbody.js
  src/components/table/td.js
  src/components/table/tfoot.js
  src/components/table/thead.js
  src/components/table/tr.js
Labels: PR: Patch, Type: Perf, Type: Refactor

#4168 fix(b-form-file): fix prop type checking for `value` prop
  src/components/form-file/README.md
  src/components/form-file/form-file.js
  src/components/form-file/form-file.spec.js
  src/components/form-file/package.json
  src/utils/inspect.js
Labels: PR: Patch, Type: Fix, Type: Refactor

#4167 fix(b-table): minor code optimizations to filter debouncing
  src/components/table/helpers/mixin-filtering.js
  src/components/table/table-filtering.spec.js
Labels: PR: Patch, Type: Fix, Type: Refactor

#4172 docs(componentdoc.vue): add version badge to prop reference table
  docs/components/componentdoc.vue
  src/components/carousel/package.json
  src/components/modal/package.json
  src/components/nav/package.json
  src/components/table/package.json
Labels: PR: Patch, Type: Docs

#4174 fix(b-tooltip/b-popover): add `SVGElement` as acceptable prop type (closes #4173)
  src/components/tooltip/helpers/bv-popper.js
  src/components/tooltip/tooltip.js
  src/utils/safe-types.js
Labels: PR: Patch, Status: WIP, Type: Fix
