Repository bootstrap-vue/bootstrap-vue, pull requests merged in 2019-11, with the labels that each got.

#4353 docs(tabs): document load tab content only when active (closes #4352)
  src/components/tabs/README.md
Labels: PR: Patch, Type: Docs

#4350 feat(b-img, b-img-lazy): add support for `srcset` and `sizes` props (closes #4348)
  src/components/image/README.md
  src/components/image/img-lazy.js
  src/components/image/img.js
  src/components/image/package.json
Labels: PR: Minor, Type: Feature

#4329 fix(b-dropdown): handle issue with touch devices on MacOS using Safari/Firefox (Fixes #4328, #4344)
  src/components/dropdown/dropdown.spec.js
  src/components/dropdown/package.json
  src/mixins/click-out.js
  src/mixins/dropdown.js
  src/mixins/focus-in.js
Labels: PR: Patch, Type: Fix

#4361 chore(docs): fix eslint warnings
  docs/pages/play.vue
  docs/plugins/docs-mixin.js
Labels: PR: Patch

#4356 fix(tables): fix issue with sticky columns when table is not responsive but has sticky headers (fixes #4354)
  src/components/table/helpers/mixin-tbody-row.js
  src/components/table/table-sticky-column.spec.js
  src/components/table/tbody.js
  src/components/table/td.js
  src/components/table/tfoot.js
  src/components/table/thead.js
  src/components/table/tr.js
Labels: PR: Patch, Status: WIP, Type: Fix

#4362 chore(docs): update tabs lazy examples
  src/components/tabs/README.md
Labels: Type: Docs, Type: Fix

#4364 fix(v-b-modal): open modal using `ENTER` key on non-button elements for A11Y
  src/directives/modal/modal.js
  src/directives/modal/modal.spec.js
Labels: PR: Patch, Type: Accessibility, Type: Fix

#4365 fix(v-b-modal): ensure trigger element is keyboard accessible if not a link or button, for A11Y
  src/components/modal/README.md
  src/directives/modal/modal.js
  src/directives/modal/modal.spec.js
Labels: PR: Patch, Type: Accessibility, Type: Fix

#4372 fix(b-table, b-table-lite, b-tbody): fix delegated event handlers when transition + minor adjustment to row `key` generation (fixes #4370)
  src/components/table/helpers/mixin-tbody-row.js
  src/components/table/helpers/mixin-tbody.js
  src/components/table/tbody.js
Labels: Type: Enhancement, Type: Fix

#4386 feat(b-form-select): support paths for `valueField`, `textField`, `htmlField` and `disabledField` props
  src/mixins/form-options.js
Labels: PR: Minor, Type: Feature

#4317 feat(b-collapse): add new prop `appear` to animate an initially visible collapse
  src/components/collapse/README.md
  src/components/collapse/collapse.js
  src/components/collapse/package.json
  src/utils/bv-collapse.js
Labels: PR: Minor, Type: Feature

#4388 fix(b-table, b-table-lite): handle edge case with row events when table is removed from dom. instantiate row event handlers only when listeners are registered (fixes #4384)
  src/components/table/helpers/mixin-tbody-row.js
  src/components/table/helpers/mixin-tbody.js
  src/components/table/table-tbody-row-events.spec.js
Labels: PR: Patch, Type: Enhancement, Type: Fix

#4391 chore: create hasListener mixin
  src/components/table/helpers/mixin-tbody-row.js
  src/components/table/helpers/mixin-tbody.js
  src/components/table/helpers/mixin-thead.js
  src/components/table/table-lite.js
  src/components/table/table.js
  src/mixins/has-listener.js
Labels: PR: Patch, Type: Refactor

#4394 feat(b-dropdown): add splitClass property to dropdown component
  src/components/dropdown/dropdown.js
  src/components/dropdown/dropdown.spec.js
  src/components/dropdown/package.json
Labels: PR: Minor, Type: Feature

#4395 docs(form-input): fix prop name typo
  src/components/form-input/README.md
Labels: PR: Patch, Type: Docs, Type: Enhancement

#4267 feat(b-form-select): add group/tree support and dedicated option and option-group components (closes #3222)
  docs/components/componentdoc.vue
  docs/pages/docs/components/_slug.js
  src/components/form-checkbox/README.md
  src/components/form-file/form-file.js
  src/components/form-radio/README.md
  src/components/form-select/README.md
  src/components/form-select/form-select-option-group.js
  src/components/form-select/form-select-option-group.spec.js
  src/components/form-select/form-select-option.js
  src/components/form-select/form-select-option.spec.js
  src/components/form-select/form-select.js
  src/components/form-select/form-select.spec.js
  src/components/form-select/helpers/mixin-options.js
  src/components/form-select/index.js
  src/components/form-select/package.json
  src/components/form/form-datalist.spec.js
  src/components/modal/helpers/bv-modal.js
  src/components/pagination-nav/pagination-nav.js
  src/components/table/helpers/mixin-filtering.js
  src/components/table/helpers/mixin-provider.js
  src/components/toast/helpers/bv-toast.js
  src/components/toast/toaster.js
  src/components/tooltip/helpers/bv-tooltip.js
  src/index.js
  src/mixins/form-options.js
  src/utils/warn.js
  src/utils/warn.spec.js
Labels: PR: Minor, Type: Enhancement, Type: Feature

#4403 chore(docs): minor updates to tooltip/popover docs
  src/components/popover/README.md
  src/components/tooltip/README.md
  src/directives/popover/README.md
  src/directives/tooltip/README.md
Labels: PR: Patch, Type: Docs

#4401 fix(tooltips, popovers): fix memory leak (closes #4400)
  src/components/tooltip/helpers/bv-tooltip.js
Labels: PR: Patch, Type: Fix

#4405 feat(b-collapse): add optional scoping to default slot
  src/components/collapse/README.md
  src/components/collapse/collapse.js
  src/components/collapse/collapse.spec.js
  src/components/collapse/package.json
Labels: PR: Minor, Type: Feature

#4428 chore(docs): fix typo in compontendoc.vue.
  docs/components/componentdoc.vue
Labels: Type: Docs
