Repository bootstrap-vue/bootstrap-vue, pull requests merged in 2019-05, with the labels that each got.

#3219 docs: add badges to ehanced/new/changed sections of docs
  src/components/modal/README.md
  src/components/nav/README.md
  src/components/tabs/README.md
Labels: Type: Docs

#3220 feat: add warning if multiple instances of Vue detected (addresses #3040)
  src/components/modal/helpers/bv-modal.spec.js
  src/utils/config.spec.js
  src/utils/plugins.js
Labels: Type: Enhancement

#3228 fix(modal): exclude document.body when determining return focus element
  src/components/modal/modal.js
  src/components/modal/modal.spec.js
Labels: Type: Fix

#3229 feat(config): Add option in config to set global tooltip and popover boundary
  src/components/popover/popover.js
  src/components/tooltip/tooltip.js
  src/directives/popover/popover.js
  src/directives/tooltip/tooltip.js
  src/mixins/toolpop.js
  src/utils/config.js
  src/utils/tooltip.class.js
Labels: Status: WIP, Type: Enhancement

#3235 fix(modal): prevent duplicate key when sending to portal-target
  src/components/dropdown/README.md
  src/components/modal/modal.js
Labels: Type: Fix

#3236 chore(toast): create unit tests for toasts
  src/components/modal/modal.js
  src/components/toast/helpers/bv-toast.js
  src/components/toast/helpers/bv-toast.spec.js
  src/components/toast/toast.js
  src/components/toast/toast.spec.js
  src/components/toast/toaster.js
  src/components/toast/toaster.spec.js
Labels: Type: Unit Testing

#3243 chore(docs): reference Vue 2.6+ in docs
  docs/pages/index.vue
Labels: Type: Docs

#3242 feat(b-dropdown & b-nav-item-dropdown): pass optional scope to default slot & fixes keyboard nav with dropdown forms
  src/components/dropdown/README.md
  src/components/dropdown/_dropdown-form.scss
  src/components/dropdown/_dropdown-text.scss
  src/components/dropdown/_dropdown.scss
  src/components/dropdown/dropdown-form.js
  src/components/dropdown/dropdown-form.spec.js
  src/components/dropdown/dropdown.js
  src/components/nav/README.md
  src/components/nav/nav-item-dropdown.js
  src/mixins/dropdown.js
Labels: Type: Accessibility, Type: Enhancement, Type: Fix

#3252 fix($bvToast,$bvModal): ensure values passed to slots are arrays for Vue.js 2.5.x compatibility (closes #3174)
  src/components/modal/helpers/bv-modal.js
  src/components/toast/helpers/bv-toast.js
Labels: Type: Fix

#3256 chore(docs): mention Vue CLI 3 plugin
  docs/markdown/intro/README.md
  docs/markdown/reference/starter-templates/README.md
Labels: Type: Docs

#3266 fix(b-nav-item-dropdown): fix disabled state (fixes #3264)
  src/components/nav/README.md
  src/components/nav/nav-item-dropdown.js
  src/components/nav/nav-item-dropdown.spec.js
Labels: Type: Fix

#3263 chore(docs): minor docs updates (closes #3262)
  src/components/modal/README.md
  src/components/modal/helpers/bv-modal.js
  src/components/toast/README.md
  src/components/toast/helpers/bv-toast.js
  src/utils/warn.js
Labels: Type: Docs

#3280 fix(types): fix msxBoxConfirm typo
  types/components/modal/index.d.ts
Labels: Type: Fix, Type: Types

#3278 chore(docs): update `/docs/misc/config` docs with simplified plugin import
  docs/markdown/misc/settings/README.md
Labels: Type: Docs

#3279 feat(b-img-lazy): add support for IntersectionObserver (closes #3276)
  src/components/image/README.md
  src/components/image/img-lazy.js
  src/components/image/img-lazy.spec.js
  src/utils/env.js
Labels: Type: Enhancement

#3287 docs(table): fix typo in complete example
  src/components/table/README.md
Labels: Type: Docs

#3288 fix(b-input-group): fix issue with slots (closes #3284)
  src/components/input-group/input-group.js
  src/components/input-group/input-group.spec.js
Labels: Type: Fix

#3293 chore(docs): exclude route render attempt for plugins.js
  docs/nuxt.config.js
Labels: Type: Docs

#3306 chore(docs): fix typo in form-input meta
  src/components/form-input/package.json
Labels: Type: Docs

#3281 perf: use re-usable fade transition component
  src/components/alert/alert.js
  src/components/alert/alert.spec.js
  src/components/index.scss
  src/components/modal/_modal.scss
  src/components/modal/index.scss
  src/components/modal/modal.js
  src/components/modal/modal.spec.js
  src/components/tabs/tab.js
  src/components/tabs/tab.spec.js
  src/components/toast/_toast.scss
  src/components/toast/toast.js
  src/components/toast/toast.spec.js
  src/utils/bv-transition.js
Labels: Type: Perf

#3305 chore($bvModal): encapsulate class, etc, into the plugin installer
  src/components/modal/helpers/bv-modal.js
Labels: Type: Perf

#3304 chore($bvToast): encapsulate class, etc, into the plugin installer
  src/components/toast/helpers/bv-toast.js
Labels: Type: Perf

#3315 feat: don't warn about multiple Vue instances when testing in JSDOM (closes #3303)
  src/components/modal/helpers/bv-modal.spec.js
  src/components/toast/helpers/bv-toast.spec.js
  src/utils/config.spec.js
  src/utils/dom.js
  src/utils/env.js
  src/utils/plugins.js
Labels: Type: Enhancement

#3321 fix(b-input-group): use same input-group-prepend/append for both props and slots
  src/components/input-group/input-group.js
Labels: Type: Enhancement, Type: Fix

#3328 fix(b-toaster): CSS fix for IE11 support (fixes #3327)
  src/components/toast/_toaster.scss
Labels: Type: Fix

#3320 fix(b-modal): delay initially open modal via nextTick when using v-model or visible prop
  src/components/modal/modal.js
Labels: Type: Fix

#3332 fix(docs): correct Vuelidate validation example and some minor tweaks
  docs/markdown/reference/validation/README.md
Labels: Type: Docs

#3335 fix(docs): correct modal directive name (closes #3334)
  src/components/modal/package.json
Labels: Type: Docs, Type: Fix

#3336 fix(docs): route generation + `b-progress-bar` label HTML support examples (closes #3333)
  docs/nuxt.config.js
  src/components/progress/README.md
Labels: Type: Docs, Type: Fix

#3340 fix: use `installFactory` for main `BootstrapVue` plugin (closes #3338)
  src/index.js
Labels: Type: Fix

#3325 feat(nuxt module): optimize imports into single import statements
  docs/markdown/intro/README.md
  nuxt/plugin.template.js
Labels: Type: Docs, Type: Enhancement, Type: Nuxt.js

#3341 feat(form controls): add `autofocus` prop
  src/components/form-checkbox/README.md
  src/components/form-checkbox/form-checkbox.spec.js
  src/components/form-file/README.md
  src/components/form-file/form-file.spec.js
  src/components/form-input/README.md
  src/components/form-input/form-input.spec.js
  src/components/form-radio/README.md
  src/components/form-radio/form-radio.spec.js
  src/components/form-select/README.md
  src/components/form-select/form-select.spec.js
  src/components/form-textarea/README.md
  src/components/form-textarea/form-textarea.spec.js
  src/mixins/form.js
Labels: Type: Feature

#3347 fix(b-alert): handle case where dismiss countdown changes to a boolean value (closes #3346)
  src/components/alert/alert.js
Labels: Type: Fix

#3349 feat(b-tooltip, b-popover): add `fallback-placement` prop (closes #3348)
  src/components/popover/README.md
  src/components/popover/popover.js
  src/components/tooltip/README.md
  src/components/tooltip/tooltip.js
  src/directives/tooltip/README.md
  src/mixins/toolpop.js
Labels: Type: Enhancement

#3326 feat(b-modal): improved portaling - retaining parent-child hierarchy (addresses #3312)
  src/components/modal/README.md
  src/components/modal/helpers/modal-manager.js
  src/components/modal/helpers/modal-target.js
  src/components/modal/modal.js
  src/components/modal/modal.spec.js
  src/utils/transporter.js
  src/utils/transporter.spec.js
Labels: Type: Enhancement, Type: Fix

#3329 fix(toast): accessibility - prevent duplicate toast announcements for screen readers (closes #3322)
  src/components/toast/README.md
  src/components/toast/helpers/bv-toast.spec.js
  src/components/toast/toast.js
  src/components/toast/toast.spec.js
  src/components/toast/toaster.js
  src/components/toast/toaster.spec.js
  src/utils/config.js
  src/utils/env.js
Labels: Type: Accessibility

#3355 chore: add badges to new features for form-controls docs
  src/components/form-checkbox/README.md
  src/components/form-file/README.md
  src/components/form-input/README.md
  src/components/form-radio/README.md
  src/components/form-select/README.md
  src/components/form-textarea/README.md
Labels: Type: Docs

#3363 chore(toast): update toast docs (closes #3359)
  src/components/toast/README.md
Labels: Type: Docs

#3367 fix(b-dropdown): delay show of dropdown when calling `show()` (closes #3366)
  src/components/dropdown/dropdown.spec.js
  src/components/dropdown/index.d.ts
  src/components/nav/index.d.ts
  src/mixins/dropdown.js
Labels: Type: Fix

#3376 chore(docs): add advanced usage example to toasts
  src/components/toast/README.md
Labels: Type: Docs

#3358 feat(es): don't transpile import/export statements to require/exports (closes #3323)
  babel.config.js
  docs/markdown/intro/README.md
Labels: Type: Enhancement

#3375 fix(tabs): use DOM query for tab probing after mount (closes: #3361)
  src/components/tabs/tab.js
  src/components/tabs/tab.spec.js
  src/components/tabs/tabs.js
  src/components/tabs/tabs.spec.js
Labels: Type: Fix

#3377 chore(types): additional updates to type declarations
  src/components/alert/index.d.ts
  src/components/collapse/index.d.ts
  src/components/tabs/index.d.ts
Labels: Type: Types

#3379 chore(docs): minor update to configuration docs
  docs/markdown/misc/settings/README.md
Labels: Type: Docs

#3382 chore: update to `utils/plugins` multiple vue warn and docs intro update (closes #3351)
  docs/markdown/intro/README.md
  src/utils/plugins.js
Labels: Type: Docs

#3383 fix(table): don't use css `grid` for stacked table SCSS - for IE11 compatibility (closes #3307)
  scripts/build.sh
  src/_variables.scss
  src/components/table/_table.scss
Labels: Status: Browser Bug, Type: Fix

#3384 docs(header): order version dropdown based on hostname / dev mode
  docs/components/header.vue
Labels: Type: Docs

#3386 fix(form control): handle autofocus inside modal or when inside a transition
  src/components/form-checkbox/form-checkbox.spec.js
  src/components/form-file/form-file.spec.js
  src/components/form-input/form-input.spec.js
  src/components/form-radio/form-radio.spec.js
  src/components/form-select/form-select.spec.js
  src/components/form-textarea/form-textarea.spec.js
  src/mixins/form.js
Labels: Type: Fix

#3387 feat(button): add new `squared` prop for making buttons with square corners
  src/components/button/README.md
  src/components/button/button.js
  src/components/button/button.spec.js
Labels: Type: Enhancement

#3394 fix(modal): use `safeId()` when comparing id received by hide/show handler (closes #3389
  src/components/modal/modal.js
Labels: Type: Enhancement, Type: Fix

#3391 fix(types): adjust typing of BvComponent & BvPlugin (closes #3390)
  src/index.d.ts
Labels: Status: Help Wanted, Type: Types

#3396 fix(tabs): fix regression with dynamically added tabs (fixes #3395)
  src/components/tabs/tab.js
  src/components/tabs/tabs.js
Labels: Type: Fix

#3404 feat(es): revert to tranforming es modules into CJS and simplify build with top-level named import/exports (closes #3397, #3393, #3323)
  .eslintignore
  .gitignore
  .prettierignore
  babel.config.js
  docs/components/componentdoc.vue
  docs/components/importdoc.vue
  docs/markdown/intro/README.md
  docs/markdown/misc/settings/README.md
  nuxt/index.js
  nuxt/plugin.dev.js
  nuxt/plugin.prod.js
  nuxt/plugin.template.js
  package.json
  scripts/build.sh
  scripts/rollup.config.js
  src/browser.js
  src/components/index.esm.js
  src/components/index.js
  src/directives/index.esm.js
  src/directives/index.js
  src/index.js
  src/legacy-es.js
  src/utils/config.js
Labels: Status: WIP, Type: Enhancement, Type: Feature, Type: Fix, Type: Refactor

#3421 chore(docs): mention that Nuxt module now configures `transformAssetUrls`
  docs/markdown/intro/README.md
  docs/markdown/reference/images/README.md
Labels: Type: Docs

#3423 feat(nuxt module): alias `esm/` and `es/` to `src/` for Nuxt prod mode
  nuxt/index.js
Labels: Type: Enhancement, Type: Nuxt.js

#3426 feat(b-tooltip, b-popover): allow global `delay` customization
  src/components/popover/popover.js
  src/components/tooltip/tooltip.js
  src/directives/popover/popover.js
  src/directives/tooltip/tooltip.js
  src/mixins/toolpop.js
  src/utils/config.js
Labels: PR: Patch, Type: Enhancement
