Repository bootstrap-vue/bootstrap-vue, pull requests merged in 2019-10, with the labels that each got.

#4185 chore(docs): improve v-play performance and only recreate instance if changed
  docs/plugins/play.js
Labels: PR: Patch, Type: Docs, Type: Perf

#4187 fix(v-b-modal): bind to inner link or button for dropdown items or nav items (fixes #4149)
  src/directives/modal/modal.js
Labels: PR: Patch, Type: Accessibility, Type: Fix

#4192 perf(b-table, b-table-lite): delegate row event handlers to the tbody element
  src/components/table/helpers/mixin-tbody-row.js
  src/components/table/helpers/mixin-tbody.js
Labels: PR: Patch, Type: Perf, Type: Refactor

#4194 docs(table): add details on the `tbody-tr-class` callback arguments
  src/components/table/README.md
Labels: PR: Patch, Type: Docs

#4195 chore(docs): add head meta description to section index pages for better SEO
  docs/plugins/docs-mixin.js
Labels: PR: Patch, Type: Docs

#4206 chore(docs): fix navbar typo
  src/components/navbar/package.json
Labels: PR: Patch, Type: Docs

#4209 chore(docs): remove excess closing tags
  src/components/card/README.md
Labels: PR: Patch, Type: Docs

#4212 fix(carousel): disable the next/prev controls when the carousel is sliding (closes #4210)
  src/components/carousel/carousel.js
Labels: PR: Patch, Type: Fix

#4224 chore(docs): minor updates to the theming reference section
  docs/markdown/reference/theming/README.md
Labels: PR: Patch, Type: Docs

#4207 chore(core): allow advanced scss import
  docs/markdown/intro/README.md
  package.json
Labels: PR: Patch, Type: Docs, Type: Refactor

#4219 chore(docs): tweaks to page quick-links styling
  docs/components/quick-links.vue
Labels: PR: Patch, Type: Docs

#4229 fix(types): BCardSubTitle component declared export name
  src/components/card/index.d.ts
Labels: PR: Patch, Type: Fix, Type: Types

#4223 fix(b-dropdown-form): fix SCSS styling when placed in a nav dropdown (fixes #4220)
  src/components/dropdown/_dropdown-form.scss
Labels: PR: Patch, Type: Fix, Type: SCSS

#4213 perf(b-table, b-table-lite): improve render performance (closes #4211, #4155)
  src/components/table/helpers/mixin-tbody-row.js
  src/components/table/table-sticky-column.spec.js
Labels: PR: Patch, Type: Perf, Type: Refactor

#4228 chore(docs): minor update to b-form-input docs
  src/components/form-input/README.md
Labels: PR: Patch, Type: Docs

#4238 chore(docs): note about requiring BootstrapVue custom CSS for tooltips/popovers
  src/components/popover/README.md
  src/components/tooltip/README.md
  src/directives/popover/README.md
  src/directives/tooltip/README.md
Labels: PR: Patch, Type: Docs

#4227 chore: release v2.0.4
  CHANGELOG.md
  docs/components/quick-links.vue
  docs/markdown/intro/README.md
  docs/markdown/reference/theming/README.md
  package.json
  src/components/card/README.md
  src/components/card/index.d.ts
  src/components/carousel/carousel.js
  src/components/dropdown/_dropdown-form.scss
  src/components/form-input/README.md
  src/components/navbar/package.json
  src/components/popover/README.md
  src/components/table/helpers/mixin-tbody-row.js
  src/components/table/table-sticky-column.spec.js
  src/components/tooltip/README.md
  src/directives/popover/README.md
  src/directives/tooltip/README.md
  yarn.lock
Labels: PR: Patch

#4239 chore: prettify and correct typos
  CHANGELOG.md
  docs/markdown/intro/README.md
  docs/markdown/reference/theming/README.md
Labels: Type: Docs

#4100 fix(b-nav-form, b-nav-text): ensure these sub-components have `<li>` as root element for accessibility
  src/components/nav/README.md
  src/components/nav/nav-form.js
  src/components/nav/nav-form.spec.js
  src/components/nav/nav-text.js
  src/components/nav/nav-text.spec.js
  src/components/navbar/README.md
Labels: PR: Minor, Type: Accessibility, Type: Enhancement

#4246 chore(docs): add missing table docs for cell scope property `fields`
  docs/components/componentdoc.vue
  src/components/table/README.md
  src/components/table/package.json
Labels: PR: Patch, Type: Docs

#4236 feat(b-pagination, b-pagination-nav): add `pills` style option
  src/_utilities.scss
  src/components/pagination-nav/README.md
  src/components/pagination-nav/_pagination-nav.scss
  src/components/pagination-nav/package.json
  src/components/pagination/README.md
  src/components/pagination/_pagination.scss
  src/components/pagination/package.json
  src/components/pagination/pagination.spec.js
  src/mixins/pagination.js
Labels: PR: Minor, Type: Feature

#4218 feat(b-form-group): allow setting label cols props to `auto` (closes #4217)
  src/components/form-group/README.md
  src/components/form-group/form-group.js
Labels: PR: Minor, Type: Enhancement

#4128 feat(b-table): default the row select feature `selected-variant` to the `active` variant
  src/components/table/README.md
  src/components/table/package.json
  src/utils/config-defaults.js
Labels: PR: Minor, Type: Feature

#4260 feat: improve `CONTRIBUTING.md`
  CONTRIBUTING.md
Labels: Type: Docs, Type: Enhancement

#4110 feat: auto-generate file `web-types.json` for WebStorm, and files `vetur-tags.json` and `vetur-attributes.json` for Vetur (closes #4107)
  docs/markdown/intro/README.md
  package.json
  scripts/build.sh
  scripts/create-web-types.js
Labels: PR: Minor, Type: Docs, Type: Enhancement

#4216 feat(b-table, b-table-lite): add in head/foot row variant prop (addresses #4215)
  src/components/table/helpers/mixin-tfoot.js
  src/components/table/helpers/mixin-thead.js
  src/components/table/package.json
  src/components/table/tr.js
Labels: PR: Minor, Type: Feature

#4261 fix(docs): broken links and sync layout docs with Bootstrap's
  CHANGELOG.md
  src/components/layout/README.md
  src/components/table/README.md
Labels: PR: Patch, Type: Docs, Type: Enhancement

#4262 chore(docs): remove multiple `in` from table docs
  src/components/table/README.md
Labels: Type: Docs

#4169 feat(b-form-input, b-form-textarea): add `lazy` modifier prop to update v-model on change/blur event
  src/components/form-input/README.md
  src/components/form-input/form-input.spec.js
  src/components/form-input/package.json
  src/components/form-textarea/README.md
  src/components/form-textarea/form-textarea.spec.js
  src/components/form-textarea/package.json
  src/mixins/form-text.js
Labels: PR: Minor, Type: Enhancement

#4269 feat(b-dropdown): add `block` support to toggle button (closes #4266)
  src/components/dropdown/README.md
  src/components/dropdown/dropdown.js
  src/components/dropdown/dropdown.spec.js
  src/components/dropdown/package.json
Labels: Type: Feature

#4271 fix(web-types): update web-types code generation to match schema
  scripts/create-web-types.js
  src/directives/popover/package.json
  src/directives/scrollspy/package.json
  src/directives/tooltip/package.json
Labels: PR: Patch, Type: Enhancement, Type: Fix

#4274 feat(b-tabs): emit cancelable BvEvent before changing tabs via new `activate-tab` event (closes #4273)
  src/components/tabs/README.md
  src/components/tabs/package.json
  src/components/tabs/tabs.js
  src/components/tabs/tabs.spec.js
Labels: Type: Feature

#4277 chore(table meta): `transition-list` => `transition-group`
  src/components/table/package.json
Labels: PR: Patch, Type: Docs

#4276 feat(b-table, b-table-lite): add prop `details-td-class` for applying classes to the details row `<td>`
  src/components/table/helpers/mixin-tbody-row.js
  src/components/table/package.json
  src/components/table/table-row-details.spec.js
Labels: PR: Minor, Type: Feature

#4281 chore(docs): update b-collapse v-model example
  src/components/collapse/README.md
Labels: PR: Patch, Type: Docs

#4283 feat(b-table): add `selectRow()` and `unselectRow()` methods to cell and row-details slot scopes, and new prop `no-select-on-click`
  src/components/table/README.md
  src/components/table/_table.scss
  src/components/table/helpers/mixin-selectable.js
  src/components/table/helpers/mixin-tbody-row.js
  src/components/table/helpers/mixin-tbody.js
  src/components/table/package.json
  src/components/table/table-selectable.spec.js
Labels: PR: Minor, Type: Enhancement, Type: Feature

#4285 chore(table): update event types for native events in package meta
  docs/components/componentdoc.vue
  src/components/table/package.json
Labels: PR: Patch, Type: Docs

#4299 feat(docs): move `@nuxtjs/google-analytics` to `buildModules`
  docs/nuxt.config.js
Labels: PR: Patch, Type: Docs, Type: Enhancement, Type: Perf

#4307 docs(getting started): add note stating tree shaking only applies to JavaScript and not CSS (closes #4297)
  docs/markdown/intro/README.md
Labels: PR: Patch, Type: Docs

#4316 chore(docs): fix minor typos
  src/components/pagination-nav/README.md
  src/components/pagination/README.md
Labels: PR: Patch, Type: Docs

#4314 feat(b-form-input, b-form-textarea): add `v-model` debouncing feature, and deprecate `<b-table>` prop `filter-debounce` (closes #4150)
  docs/markdown/intro/README.md
  src/components/form-input/README.md
  src/components/form-input/form-input.spec.js
  src/components/form-input/package.json
  src/components/form-textarea/README.md
  src/components/form-textarea/package.json
  src/components/table/README.md
  src/components/table/helpers/mixin-filtering.js
  src/components/table/package.json
  src/components/table/table-filtering.spec.js
  src/mixins/form-text.js
Labels: PR: Minor, Type: Feature

#4318 feat(v-b-visible): make `v-b-visible` directive available for public use
  docs/components/section-toc.vue
  src/components/form-textarea/form-textarea.js
  src/components/image/img-lazy.js
  src/directives/index.d.ts
  src/directives/index.js
  src/directives/visible/README.md
  src/directives/visible/index.d.ts
  src/directives/visible/index.js
  src/directives/visible/package.json
  src/directives/visible/visible.js
  src/index.js
Labels: PR: Minor, Type: Feature

#4325 fix(b-pagination, b-pagination-nav): add UP/DOWN keyboard navigation support for JAWS (fixes #4322)
  src/components/pagination-nav/README.md
  src/components/pagination/README.md
  src/components/pagination/pagination.spec.js
  src/mixins/pagination.js
Labels: PR: Patch, Type: Accessibility, Type: Feature, Type: Fix

#4326 fix(b-tabs): allow space to trigger tab activation when `no-key-nav` is enabled (fixes #4323)
  src/components/tabs/README.md
  src/components/tabs/tabs.js
  src/components/tabs/tabs.spec.js
Labels: PR: Patch, Type: Accessibility, Type: Fix

#4332 fix(v-b-tooltip, v-b-popover): ensure reference to trigger element is passed to title/content function (fixes #4331)
  src/directives/popover/popover.js
  src/directives/tooltip/tooltip.js
Labels: PR: Patch, Type: Fix

#4334 docs: fix visible directive examples
  src/directives/visible/README.md
Labels: PR: Patch, Type: Docs, Type: Fix
