Repository bootstrap-vue/bootstrap-vue, pull requests merged in 2019-06, with the labels that each got.

#3429 fix(table): ensure provider is refreshed when filter is an object (closes #3428)
  src/components/table/helpers/mixin-filtering.js
  src/components/table/helpers/mixin-provider.js
Labels: PR: Patch, Type: Fix

#3442 fix(b-tabs): handle cases where `b-tab` has manually specified ID
  src/components/tabs/tabs.js
Labels: Type: Fix

#3444 fix(b-pagination-nav): attempt to auto-detect current page when `pages` array or `number-of-pages` changes (closes #3443)
  src/components/pagination-nav/pagination-nav.js
Labels: Type: Fix

#3459 fix(pagination-nav): fix incorrect name in component package.json file (closes #3458)
  src/components/pagination-nav/package.json
Labels: Type: Fix, Type: Types

#3448 chore(config): updates to config handling
  src/bv-config.js
  src/components/modal/helpers/bv-modal.js
  src/components/toast/helpers/bv-toast.js
  src/index.js
  src/utils/config-defaults.js
  src/utils/config-defaults.spec.js
  src/utils/config-set.js
  src/utils/config.js
  src/utils/config.spec.js
  src/utils/object.js
  src/utils/plugins.js
Labels: Type: Perf, Type: Refactor

#3465 fix(utils/get): handle edge case with inherited object getters (fixes #3463)
  src/utils/get.js
Labels: Type: Enhancement, Type: Fix

#3472 chore(deps): bump handlebars from 4.1.1 to 4.1.2
  yarn.lock
Labels: dependencies

#3473 chore(deps): bump js-yaml from 3.13.0 to 3.13.1
  yarn.lock
Labels: dependencies

#3476 fix(b-dropdown): close when clicking on nested elements inside item with `to` prop (fixes #3474)
  src/components/link/link.js
Labels: Type: Fix

#3479 fix(docs): remove duplicate link to Position
  docs/markdown/reference/utility-classes/README.md
Labels: Type: Docs

#3481 chore(docs): add badge if component is a functional component in component reference sections
  docs/components/componentdoc.vue
Labels: Type: Docs

#3487 fix(types): add BInputGroup to TypeScript definitions
  src/components/input-group/index.d.ts
Labels: Type: Types

#3493 chore(docs): fix prettier warning
  docs/components/componentdoc.vue
Labels: Type: Docs

#3489 fix(modal): fix IE11 issue with copy/paste from modal into MS Word (fixes #3457)
  src/components/modal/modal.js
  src/components/modal/modal.spec.js
Labels: Status: Browser Bug, Type: Fix

#3492 fix(modal): properly render `*-html` props if provided (closes #3491)
  src/components/modal/helpers/bv-modal.js
  src/components/modal/modal.js
  src/components/toast/helpers/bv-toast.js
Labels: Type: Fix

#3495 chore(docs): fix typo in vee-validate example (closes #3494)
  docs/markdown/reference/validation/README.md
Labels: Type: Docs, Type: Fix

#3500 chore(docs): minor updates to pagination/pagination-nav docs
  src/components/pagination-nav/README.md
  src/components/pagination/README.md
Labels: Type: Docs

#3501 fix(form-input, form-textarea): handle case where input has been removed from document (closes #3498)
  src/mixins/form-text.js
Labels: Type: Fix

#3507 chore: update form-input custom range SCSS
  src/components/form-input/_form-input.scss
Labels: Status: Upstream, Type: SCSS

#3520 fix(b-table-lite): add checks to helper mixins for existence of stopIfBusy (closes #3518)
  src/components/table/helpers/mixin-tbody-row.js
  src/components/table/helpers/mixin-thead.js
Labels: Type: Fix

#3519 docs(intro): add prerequisites section
  docs/markdown/intro/README.md
Labels: Type: Docs

#3513 fix(tabs): add detection of when registered tabs change order
  src/components/tabs/tabs.js
Labels: Type: Fix

#3523 fix(nuxt): correct transformAssetUrls value for b-card-img (closes #3521)
  docs/markdown/reference/images/README.md
  nuxt/index.js
Labels: Type: Docs, Type: Fix, Type: Nuxt.js

#3524 chore(docs): add open-collective to navbar
  docs/components/header.vue
Labels: Type: Docs

#3527 docs(intro): mention deprecation of `@babel/polyfill` and suggest using `core-js` instead
  docs/markdown/intro/README.md
Labels: Type: Docs

#3526 fix(config): avoid using `of` operator (closes #3525)
  src/utils/config-set.js
  src/utils/object.js
Labels: Type: Fix

#3515 docs(b-table): remove reference to prop that hasn't been available for many versions (closes #3511)
  src/components/table/README.md
Labels: Type: Docs, Type: Fix

#3512 chore(table): minor tweaks to filtering mixin code
  src/components/table/helpers/mixin-filtering.js
Labels: Type: Refactor

#3530 chore: unify Bootstrap v4 spelling
  CHANGELOG-OLD.md
  CHANGELOG.md
  README.md
  docs/markdown/intro/README.md
  docs/markdown/misc/settings/README.md
  docs/markdown/reference/color-variants/README.md
  docs/markdown/reference/color-variants/meta.json
  docs/markdown/reference/size-props/README.md
  docs/markdown/reference/size-props/meta.json
  docs/markdown/reference/spacing-classes/README.md
  docs/markdown/reference/spacing-classes/meta.json
  docs/markdown/reference/starter-templates/README.md
  docs/markdown/reference/theming/README.md
  docs/markdown/reference/utility-classes/README.md
  docs/markdown/reference/utility-classes/meta.json
  docs/nuxt.config.js
  docs/pages/index.vue
  package.json
  src/components/button/README.md
  src/components/card/README.md
  src/components/form-group/README.md
  src/components/form-input/README.md
  src/components/form-input/_form-input.scss
  src/components/form-select/README.md
  src/components/form/README.md
  src/components/image/README.md
  src/components/input-group/README.md
  src/components/jumbotron/README.md
  src/components/layout/README.md
  src/components/link/README.md
  src/components/modal/README.md
  src/components/modal/_modal.scss
  src/components/navbar/README.md
  src/components/popover/README.md
  src/components/spinner/README.md
  src/components/table/README.md
  src/components/tabs/README.md
  src/components/toast/README.md
  src/components/toast/_toast.scss
  src/directives/popover/README.md
  src/directives/popover/package.json
  src/directives/scrollspy/README.md
  src/directives/tooltip/README.md
  src/mixins/form-radio-check.js
  src/utils/bv-transition.js
Labels: Type: Docs, Type: Enhancement

#3534 fix(b-table): ensure `ctx.sortBy` is an empty string when no sorting (fixes #3532)
  src/components/table/helpers/mixin-sorting.js
Labels: Type: Enhancement, Type: Fix

#3538 chore(docs): add a few more links to Utility Classes reference section
  docs/markdown/reference/utility-classes/README.md
Labels: Type: Docs

#3536 docs(b-form-select): add clarification about `html` limitations in options array
  src/components/form-select/README.md
Labels: Type: Docs

#3537 chore(b-tabs): include attribute 'id' in observeDom config
  src/components/tabs/tabs.js
Labels: Type: Enhancement

#3553 feat(table): don't render `thead` or `tfoot` if no fields (closes #3547)
  src/components/table/helpers/mixin-thead.js
Labels: Type: Accessibility, Type: Enhancement

#3552 chore(docs): mark some elements as `translate="no"`
  docs/components/codemirror.js
  docs/components/componentdoc.vue
  docs/components/importdoc.vue
  docs/markdown/intro/README.md
  docs/markdown/reference/spacing-classes/README.md
  docs/nuxt.config.js
  docs/pages/play.vue
  docs/plugins/play.js
  docs/utils/marked-loader.js
Labels: Type: Docs, Type: Enhancement

#3567 fix(b-input-group): fix kebab-case prop names for `prepend-html` and `append-html` (fixes #3565)
  src/components/input-group/input-group.js
  src/components/input-group/input-group.spec.js
Labels: Type: Fix

#3568 fix(table): adjustments to sort icon positioning SCSS (closes #3563)
  src/_variables.scss
  src/components/table/_table.scss
Labels: Type: Fix, Type: SCSS

#3574 docs: create accessibility reference section
  CHANGELOG.md
  docs/components/header.vue
  docs/markdown/intro/README.md
  docs/markdown/reference/accessibility/README.md
  docs/markdown/reference/accessibility/meta.json
  docs/pages/docs/reference/index.js
  src/components/badge/README.md
  src/components/form-input/README.md
  src/components/pagination-nav/README.md
  src/components/pagination/README.md
  src/components/toast/README.md
Labels: Type: Docs

#3577 feat(b-tabs): emit `changed` event whenever tabs added, removed or re-ordered (closes #3575)
  src/components/tabs/package.json
  src/components/tabs/tabs.js
Labels: Type: Feature

#3583 feat(tooltip, popover): remove need for route watcher
  src/components/popover/popover.js
  src/components/tooltip/tooltip.js
  src/directives/popover/popover.js
  src/directives/tooltip/tooltip.js
  src/utils/tooltip.class.js
Labels: Type: Enhancement

#3586 docs(table): minor update to selectable rows example
  src/components/table/README.md
Labels: Type: Docs

#3585 feat(b-table): sort fields that have a formatter function + support `localCompare` options (closes #3178, #1173)
  src/components/table/README.md
  src/components/table/helpers/default-sort-compare.js
  src/components/table/helpers/default-sort-compare.spec.js
  src/components/table/helpers/mixin-items.js
  src/components/table/helpers/mixin-sorting.js
  src/components/table/helpers/mixin-tbody-row.js
  src/components/table/table-item-formatter.spec.js
  src/components/table/table-sorting.spec.js
  src/components/table/table.spec.js
Labels: Type: Enhancement

#3589 chore: improve CircleCI config
  .circleci/config.yml
  docs/nuxt.config.js
  package.json
  yarn.lock
Labels: Type: Enhancement

#3590 chore: update pagination-nav.spec.js to prevent JSDOM errors.
  src/components/pagination-nav/pagination-nav.spec.js
Labels: Type: Unit Testing
