Repository bootstrap-vue/bootstrap-vue, pull requests merged in 2019-01, with the labels that each got.

#2380 fix(docs): create local marked-loader.js
  docs/nuxt.config.js
  docs/utils/marked-loader.js
  package.json
Labels: Status: Upstream, Type: Docs, Type: Fix, Version: 2.x

#2382 fix(b-img-lazy): better initial inView check + new show prop (fixes #1755)
  src/components/image/fixtures/image.html
  src/components/image/img-lazy.js
Labels: Status: WIP, Type: Enhancement, Type: Fix, Version: 2.x

#2395 chore: add additional test scenarios to popover and tooltip
  src/components/popover/fixtures/popover.html
  src/components/popover/fixtures/popover.js
  src/components/tooltip/fixtures/tooltip.html
  src/components/tooltip/fixtures/tooltip.js
  src/directives/popover/README.md
  src/mixins/toolpop.js
Labels: Type: Unit Testing, Version: 2.x

#2393 feat(table): "Debounce" providerFunction and refresh methods
  src/components/table/README.md
  src/components/table/table-provider.spec.js
  src/components/table/table.js
  src/components/table/table.spec.js
Labels: Type: Enhancement, Version: 2.x

#2398 chore: add navbar tests
  src/components/navbar/navbar-brand.spec.js
  src/components/navbar/navbar-nav.spec.js
  src/components/navbar/navbar-toggle.spec.js
  src/components/navbar/navbar.spec.js
Labels: Status: WIP, Type: Unit Testing, Version: 2.x

#2399 fix(carousel): setInterval memory leak when no slides provided
  src/components/carousel/carousel.js
  src/components/carousel/carousel.spec.js
  src/components/carousel/fixtures/carousel.html
Labels: Type: Fix, Type: Unit Testing, Version: 2.x

#2401 chore: add tests for card sub-components
  src/components/card/card-body.spec.js
  src/components/card/card-footer.spec.js
  src/components/card/card-group.js
  src/components/card/card-group.spec.js
  src/components/card/card-header.spec.js
  src/components/card/card-img.js
  src/components/card/card-img.spec.js
  src/components/card/card-sub-title.js
  src/components/card/card-sub-title.spec.js
  src/components/card/card-title.js
  src/components/card/card-title.spec.js
Labels: Status: WIP, Type: Unit Testing, Version: 2.x

#2384 feat(link): Add support for nuxt-link
  docs/markdown/reference/router-links/README.md
  src/components/link/README.md
  src/components/link/link.js
Labels: Status: WIP, Type: Enhancement, Version: 2.x

#2388 fix(router-link): remove default values for active-class and exact-active-class (Fixes #2387)
  docs/components/nav.vue
  docs/components/sidebar.vue
  src/components/link/link.js
Labels: Status: Breaking Change, Type: Fix, Version: 2.x

#2402 chore: carousel test adjustment
  src/components/carousel/carousel.spec.js
Labels: Status: WIP, Type: Unit Testing, Version: 2.x

#2405 fix(link): use `active` class when manually placed into active state
  src/components/link/fixtures/link.html
  src/components/link/link.js
  src/components/link/link.spec.js
Labels: Type: Fix, Version: 2.x

#2406 feat(carousel): support crossfade animation
  src/components/carousel/README.md
  src/components/carousel/carousel.js
Labels: Type: Enhancement, Type: Feature, Version: 2.x

#2407 feat(carousel): use provide and inject for sub-component communication
  src/components/carousel/carousel-slide.js
  src/components/carousel/carousel-slide.spec.js
  src/components/carousel/carousel.js
  src/components/carousel/carousel.spec.js
Labels: Type: Enhancement, Type: Unit Testing, Version: 2.x

#2409 feat(carousel): add support for swipe on touch screens
  src/components/carousel/README.md
  src/components/carousel/carousel-slide.js
  src/components/carousel/carousel.js
  src/components/carousel/carousel.spec.js
  src/components/carousel/fixtures/carousel.html
  src/components/carousel/fixtures/carousel.js
  src/utils/env.js
Labels: Status: WIP, Type: Enhancement, Type: Feature, Version: 2.x

#2416 fix(table): generate TR key using serialized item or primary key if provided (fixes: #2410)
  src/components/table/README.md
  src/components/table/table.js
Labels: Type: Fix, Version: 2.x

#2415 chore(docs): Remove inconsistencies
  CHANGELOG.md
  docs/markdown/intro/README.md
  docs/markdown/misc/changelog/meta.json
  docs/markdown/reference/color-variants/README.md
  docs/markdown/reference/images/README.md
  docs/markdown/reference/router-links/README.md
  docs/markdown/reference/size-props/README.md
  docs/markdown/reference/spacing-classes/README.md
  docs/markdown/reference/starter-templates/README.md
  docs/markdown/reference/theming/README.md
  docs/markdown/reference/utility-classes/README.md
  docs/markdown/reference/validation/README.md
  docs/nuxt.config.js
  docs/pages/index.vue
  docs/pages/play.vue
Labels: Status: WIP, Type: Docs, Version: 2.x

#2419 perf(utils/dom): use passive event listeners where possible
  src/components/carousel/carousel.js
  src/components/image/img-lazy.js
  src/directives/scrollspy/scrollspy.class.js
  src/directives/scrollspy/scrollspy.js
  src/utils/dom.js
  src/utils/env.js
Labels: Status: WIP, Type: Enhancement, Version: 2.x

#2431 feat(dropdown): use provide and inject
  src/components/dropdown/dropdown-item-button.js
  src/components/dropdown/dropdown-item-button.spec.js
  src/components/dropdown/dropdown-item.js
  src/components/dropdown/dropdown-item.spec.js
  src/components/dropdown/dropdown.js
  src/components/dropdown/dropdown.spec.js
  src/components/nav/nav-item-dropdown.js
  src/mixins/dropdown.js
Labels: Type: Enhancement, Version: 2.x

#2434 feat(dropdown): support for form controls and free flow text
  src/components/dropdown/README.md
  src/components/dropdown/_dropdown-form.scss
  src/components/dropdown/_dropdown-text.scss
  src/components/dropdown/dropdown-form.js
  src/components/dropdown/dropdown-form.spec.js
  src/components/dropdown/dropdown-text.js
  src/components/dropdown/dropdown-text.spec.js
  src/components/dropdown/index.js
  src/components/dropdown/index.scss
  src/components/dropdown/package.json
Labels: Status: WIP, Type: Feature, Version: 2.x

#2425 feat(table): add table row middle click event
  src/components/table/README.md
  src/components/table/package.json
  src/components/table/table.js
  src/components/table/table.spec.js
Labels: Type: Feature, Version: 2.x

#2436 chore(docs): Improve import docs
  docs/components/importdoc.vue
Labels: Type: Docs

#2427 feat(docs): Prettify with `prettier`
  .prettierrc
  CHANGELOG.md
  CONTRIBUTING.md
  docs/markdown/intro/README.md
  docs/markdown/reference/color-variants/README.md
  docs/markdown/reference/images/README.md
  docs/markdown/reference/router-links/README.md
  docs/markdown/reference/size-props/README.md
  docs/markdown/reference/spacing-classes/README.md
  docs/markdown/reference/starter-templates/README.md
  docs/markdown/reference/theming/README.md
  docs/markdown/reference/utility-classes/README.md
  docs/markdown/reference/validation/README.md
  package.json
  src/components/alert/README.md
  src/components/badge/README.md
  src/components/breadcrumb/README.md
  src/components/button-group/README.md
  src/components/button-toolbar/README.md
  src/components/button/README.md
  src/components/card/README.md
  src/components/carousel/README.md
  src/components/collapse/README.md
  src/components/dropdown/README.md
  src/components/embed/README.md
  src/components/form-checkbox/README.md
  src/components/form-file/README.md
  src/components/form-group/README.md
  src/components/form-input/README.md
  src/components/form-radio/README.md
  src/components/form-select/README.md
  src/components/form-textarea/README.md
  src/components/form/README.md
  src/components/image/README.md
  src/components/input-group/README.md
  src/components/jumbotron/README.md
  src/components/layout/README.md
  src/components/link/README.md
  src/components/list-group/README.md
  src/components/media/README.md
  src/components/modal/README.md
  src/components/nav/README.md
  src/components/navbar/README.md
  src/components/pagination-nav/README.md
  src/components/pagination/README.md
  src/components/popover/README.md
  src/components/progress/README.md
  src/components/spinner/README.md
  src/components/table/README.md
  src/components/tabs/README.md
  src/components/tooltip/README.md
  src/directives/popover/README.md
  src/directives/scrollspy/README.md
  src/directives/tooltip/README.md
  yarn.lock
Labels: Type: Docs, Version: 2.x

#2435 perf(events): use passive event listeners where possible
  src/components/collapse/collapse.js
  src/components/modal/modal.js
Labels: Status: WIP, Type: Perf, Version: 2.x

#2442 fix(tabs): various fixes and improvements (Fixes: #2327, #2148. Closes: #2403, #2180)
  src/components/tabs/README.md
  src/components/tabs/tab.js
  src/components/tabs/tab.spec.js
  src/components/tabs/tabs.js
Labels: Status: WIP, Type: Enhancement, Type: Fix, Version: 2.x

#2448 fix(tabs): Fix tab titleLinkClass and titleItemClass handling
  src/components/tabs/tabs.js
Labels: Type: Fix, Version: 2.x

#2450 feat(table): add support for transitions on tbody element (Closes #1821)
  docs/assets/css/styles.css
  src/components/table/README.md
  src/components/table/table.js
Labels: Status: WIP, Type: Feature, Version: 2.x

#2452 chore(lint): prep for prettier update
  docs/components/codemirror.vue
  docs/components/componentdoc.vue
  docs/components/footer.vue
  docs/components/importdoc.vue
  docs/components/jsfiddle.vue
  docs/components/nav.vue
  docs/components/search.vue
  docs/components/sidebar.vue
  docs/components/toc.vue
  docs/layouts/default.vue
  docs/layouts/docs.vue
  docs/pages/docs/index.vue
  docs/pages/docs/misc/_slug.vue
  docs/pages/docs/reference/_slug.vue
  docs/pages/index.vue
  docs/pages/play.vue
  src/components-extra/dropdown-select/dropdown-select.vue
Labels: Status: WIP
