Repository bootstrap-vue/bootstrap-vue, pull requests merged in 2019-08, with the labels that each got.

#3794 feat(form controls): add support for control sizing of `b-form-file`, `b-form-checkbox`, and `b-form-radio` (closes #3745)
  src/_variables.scss
  src/components/form-checkbox/README.md
  src/components/form-checkbox/_form-checkbox.scss
  src/components/form-checkbox/index.scss
  src/components/form-checkbox/package.json
  src/components/form-file/README.md
  src/components/form-file/_form-file.scss
  src/components/form-file/form-file.js
  src/components/form-file/index.scss
  src/components/form-file/package.json
  src/components/form-radio/README.md
  src/components/form-radio/_form-radio.scss
  src/components/form-radio/index.scss
  src/components/form-radio/package.json
  src/components/index.scss
  src/components/input-group/README.md
  src/components/input-group/package.json
  src/components/table/README.md
  src/mixins/form-radio-check.js
Labels: Type: Enhancement

#3799 feat(b-table-simple): new `<table>` wrapper component that allows users to render their own `<thead>`, `<tfoot>`, `<body>`
  src/components/index.esm.js
  src/components/table/README.md
  src/components/table/helpers/constants.js
  src/components/table/helpers/default-sort-compare.js
  src/components/table/helpers/mixin-busy.js
  src/components/table/helpers/mixin-caption.js
  src/components/table/helpers/mixin-stacked.js
  src/components/table/helpers/mixin-table-renderer.js
  src/components/table/index.d.ts
  src/components/table/index.js
  src/components/table/package.json
  src/components/table/table-lite.js
  src/components/table/table-simple.js
  src/components/table/table-simple.spec.js
  src/components/table/table.js
Labels: Type: Feature

#3807 feat(b-table, b-table-lite): place `<tfoot>` after `<tbody>` element per HTML5 spec and for A11Y
  src/components/table/helpers/mixin-table-renderer.js
Labels: Type: Accessibility, Type: Enhancement

#3827 fix(docs): correct typo on intro page (closes #3826)
  docs/markdown/intro/README.md
Labels: Type: Docs

#3808 feat(table): create table child element helper components, plus new `sort-null-last` and `table-variant` props.
  README.md
  docs/pages/index.vue
  src/components/index.esm.js
  src/components/input-group/input-group.js
  src/components/table/README.md
  src/components/table/_table.scss
  src/components/table/helpers/default-sort-compare.js
  src/components/table/helpers/default-sort-compare.spec.js
  src/components/table/helpers/mixin-bottom-row.js
  src/components/table/helpers/mixin-busy.js
  src/components/table/helpers/mixin-caption.js
  src/components/table/helpers/mixin-empty.js
  src/components/table/helpers/mixin-sorting.js
  src/components/table/helpers/mixin-stacked.js
  src/components/table/helpers/mixin-table-renderer.js
  src/components/table/helpers/mixin-tbody-row.js
  src/components/table/helpers/mixin-tbody.js
  src/components/table/helpers/mixin-tfoot.js
  src/components/table/helpers/mixin-thead.js
  src/components/table/helpers/mixin-top-row.js
  src/components/table/helpers/table-cell.js
  src/components/table/index.d.ts
  src/components/table/index.js
  src/components/table/package.json
  src/components/table/table-caption.spec.js
  src/components/table/table-simple.js
  src/components/table/tbody.js
  src/components/table/td.js
  src/components/table/tfoot.js
  src/components/table/th.js
  src/components/table/thead.js
  src/components/table/tr.js
Labels: Type: Accessibility, Type: Enhancement, Type: Feature, Type: Refactor

#3832 fix(tabs): nav item `id` and `aria-controls` (closes #3819)
  src/components/tabs/tabs.js
Labels: Type: Fix

#3831 feat(table): add sticky header support (closes #2085)
  src/_variables.scss
  src/components/table/README.md
  src/components/table/_table.scss
  src/components/table/helpers/mixin-table-renderer.js
  src/components/table/helpers/table-cell.js
  src/components/table/table.spec.js
Labels: Type: Feature

#3836 chore(types): add types for `TableLitePlugin` and `TableSimplePlugin`
  src/components/table/index.d.ts
Labels: Type: Types

#3838 chore(docs): remove deprecated import paths from importdoc.vue
  docs/components/importdoc.vue
Labels: Type: Docs

#3840 chore(docs): minor updates to table docs
  src/components/table/README.md
Labels: Type: Docs

#3841 feat(config): defaults for all `size` properties (closes #3805)
  docs/markdown/misc/settings/README.md
  src/components/button-group/button-group.js
  src/components/button/button.js
  src/components/dropdown/dropdown.js
  src/components/form-file/form-file.js
  src/components/input-group/input-group.js
  src/components/pagination-nav/pagination-nav.js
  src/components/pagination/pagination.js
  src/mixins/form-size.js
  src/mixins/pagination.js
  src/utils/config-defaults.js
Labels: Type: Enhancement, Type: Feature

#3851 chore(docs): add link to changelog on intro page
  docs/markdown/intro/README.md
  docs/pages/docs/index.js
Labels: Type: Docs

#3850 chore(plugin): add NAME option to `vueUse` (closes #3849)
  src/index.js
  src/utils/plugins.js
Labels: Type: Enhancement

#3846 fix(b-modal): prevent page scroll when tabbing to bottom of modal + better tab containment in enforceFocus (closes #3842)
  src/components/modal/README.md
  src/components/modal/modal.js
  src/components/modal/modal.spec.js
Labels: Type: Fix

#3844 feat(b-table): programmatic row selection (closes #3064, #3370)
  src/components/table/README.md
  src/components/table/helpers/mixin-selectable.js
  src/components/table/helpers/mixin-tbody-row.js
  src/components/table/index.d.ts
  src/components/table/table-selectable.spec.js
Labels: Type: Feature

#3847 feat(tables): add support for sticky columns
  docs/markdown/reference/theming/README.md
  src/_variables.scss
  src/components/table/README.md
  src/components/table/_table.scss
  src/components/table/helpers/mixin-tbody-row.js
  src/components/table/helpers/mixin-thead.js
  src/components/table/helpers/table-cell.js
Labels: Type: Feature

#3869 feat(tooltip/popover): remove deprecations
  src/_variables.scss
Labels: Status: Breaking Change, Type: Enhancement

#3864 feat(modal): remove BvModalEvent deprecations
  src/components/modal/helpers/bv-modal-event.class.js
  src/components/modal/helpers/bv-modal-event.class.spec.js
  src/components/modal/index.d.ts
Labels: Status: Breaking Change, Type: Enhancement

#3867 feat(b-nav, b-nav-item-dropdown): remove deprecated slot and props
  src/components/nav/README.md
  src/components/nav/nav-item-dropdown.js
  src/components/nav/nav.js
  src/components/nav/nav.spec.js
  src/components/navbar/README.md
Labels: Status: Breaking Change, Type: Enhancement

#3868 feat(b-dropdown): remove deprecated slot `text`
  src/components/dropdown/dropdown.js
  src/components/dropdown/package.json
Labels: Status: Breaking Change, Type: Enhancement

#3866 feat(table): remove deprecated slot names
  docs/components/componentdoc.vue
  docs/components/importdoc.vue
  src/components/table/README.md
  src/components/table/helpers/mixin-filtering.js
  src/components/table/helpers/mixin-items.js
  src/components/table/helpers/mixin-tbody-row.js
  src/components/table/helpers/mixin-thead.js
  src/components/table/helpers/normalize-fields.js
  src/components/table/helpers/normalize-fields.spec.js
  src/components/table/package.json
  src/components/table/table-row-details.spec.js
  src/components/table/table-tbody-row-events.spec.js
  src/components/table/table-tfoot-events.spec.js
  src/components/table/table-thead-events.spec.js
Labels: Status: Breaking Change, Type: Enhancement

#3863 feat(tabs): remove deprecations
  src/components/tabs/README.md
  src/components/tabs/package.json
  src/components/tabs/tab.js
  src/components/tabs/tabs.js
Labels: Status: Breaking Change, Type: Enhancement

#3876 feat(tables): add support for custom header attributes (closes #2244)
  src/components/table/README.md
  src/components/table/helpers/mixin-tbody-row.js
  src/components/table/helpers/mixin-thead.js
  src/components/table/index.d.ts
  src/components/table/table-lite.spec.js
  src/components/table/table.spec.js
Labels: Type: Enhancement, Type: Feature

#3879 feat(b-form-group): remove deprecated props `horizontal` and `breakpoint`
  src/components/form-group/README.md
  src/components/form-group/form-group.js
Labels: Status: Breaking Change, Type: Enhancement

#3870 feat(docs): remove new/enhances/changed badges
  docs/components/importdoc.vue
  docs/markdown/intro/README.md
  docs/markdown/misc/settings/README.md
  docs/markdown/reference/accessibility/meta.json
  docs/markdown/reference/images/README.md
  docs/markdown/reference/size-props/README.md
  docs/markdown/reference/starter-templates/README.md
  src/components/button/README.md
  src/components/dropdown/README.md
  src/components/form-checkbox/README.md
  src/components/form-checkbox/package.json
  src/components/form-file/README.md
  src/components/form-file/package.json
  src/components/form-input/README.md
  src/components/form-radio/README.md
  src/components/form-radio/package.json
  src/components/form-select/README.md
  src/components/form-textarea/README.md
  src/components/input-group/README.md
  src/components/input-group/package.json
  src/components/modal/README.md
  src/components/modal/package.json
  src/components/nav/README.md
  src/components/nav/package.json
  src/components/popover/README.md
  src/components/popover/package.json
  src/components/table/README.md
  src/components/table/package.json
  src/components/tabs/README.md
  src/components/tabs/package.json
  src/components/tooltip/README.md
  src/components/tooltip/package.json
  src/directives/popover/README.md
  src/directives/popover/package.json
  src/directives/tooltip/README.md
  src/directives/tooltip/package.json
Labels: Type: Docs, Type: Enhancement

#3880 feat(b-form-*) remove supplying a string to `state` prop
  src/components/form-checkbox/README.md
  src/components/form-checkbox/form-checkbox.spec.js
  src/components/form-file/README.md
  src/components/form-group/README.md
  src/components/form-input/README.md
  src/components/form-input/form-input.spec.js
  src/components/form-radio/README.md
  src/components/form-radio/form-radio.spec.js
  src/components/form-select/README.md
  src/components/form-select/form-select.spec.js
  src/components/form-textarea/README.md
  src/components/form-textarea/form-textarea.spec.js
  src/components/form/README.md
  src/mixins/form-state.js
Labels: Status: Breaking Change, Type: Enhancement

#3883 feat(b-nav): add card header support
  src/components/card/README.md
  src/components/nav/README.md
  src/components/nav/nav.js
  src/components/nav/nav.spec.js
  src/components/tabs/tabs.js
  src/directives/scrollspy/README.md
Labels: Type: Enhancement, Type: Feature

#3887 fix(b-table, b-table-lite): render header when not always stacked mode (fixes #3886)
  src/components/table/helpers/mixin-stacked.js
Labels: Type: Fix

#3888 chore(docs): add clarification to `order` and `order-{breakpoint}` section
  src/components/layout/README.md
Labels: Type: Docs

#3889 fix(v-b-toggle): don't override `role` if element has a `role` assigned
  src/directives/toggle/toggle.js
Labels: Type: Accessibility, Type: Enhancement, Type: Fix

#3890 chore(table): minor code adjustments
  src/components/table/helpers/mixin-stacked.js
  src/components/table/helpers/mixin-thead.js
Labels: Type: Enhancement

#3891 feat(b-table): add `filter-debounce` prop for debouncing filter updates
  src/components/table/README.md
  src/components/table/helpers/mixin-filtering.js
  src/components/table/table-filtering.spec.js
Labels: Type: Enhancement, Type: Perf

#3898 feat(b-table): allow field definition properties `filterByFormatted` and `sortByFormatted` accept a formatter function reference (closes #3892)
  src/components/form-checkbox/README.md
  src/components/form-file/README.md
  src/components/form-group/README.md
  src/components/form-input/README.md
  src/components/form-radio/README.md
  src/components/form-select/README.md
  src/components/form-textarea/README.md
  src/components/form/README.md
  src/components/table/README.md
  src/components/table/helpers/mixin-sorting.js
  src/components/table/helpers/sanitize-row.js
  src/components/table/index.d.ts
Labels: Type: Enhancement

#3906 chore(docs): minor updates to the table docs
  src/components/table/README.md
Labels: Type: Docs

#3905 feat(b-carousel): add prop `no-wrap` for disabling wrapping to start/end (closes #3902)
  src/components/carousel/README.md
  src/components/carousel/carousel.js
  src/components/carousel/carousel.spec.js
  src/components/carousel/index.d.ts
Labels: Type: Feature

#3907 feat(b-table): add `selectAllRows()` and `clearSelected()` to thead/tfoot slot scopes (addresses #3901)
  src/components/table/README.md
  src/components/table/helpers/mixin-thead.js
Labels: Type: Enhancement

#3912 fix(docs): remove broken Twitter link (closes #3911)
  docs/markdown/intro/README.md
Labels: Type: Docs, Type: Fix

#3920 fix(b-table, b-table-lite): handle edge case where field slot returns no vNodes (fixes #3919)
  src/components/table/helpers/mixin-tbody-row.js
  src/components/table/helpers/mixin-thead.js
Labels: Type: Fix

#3921 fix(b-modal): ensure non-prop attributes are transferred to the modal outer wrapper `div` (closes #3896)
  src/components/modal/modal.js
Labels: Type: Fix

#3935 chore(docs): add more details about on-demand toast parenting (closes #3934)
  src/components/toast/README.md
Labels: Type: Docs

#3931 chore(docs): minor updates to dropdown docs
  src/components/dropdown/README.md
  src/components/dropdown/package.json
Labels: Type: Docs

#3937 fix(b-form-textarea): handle initial auto-height when in modal, tabs, or other component with transition or which uses `v-show` (fixes #3936, #3702)
  src/components/form-textarea/README.md
  src/components/form-textarea/form-textarea.js
  src/components/form-textarea/form-textarea.spec.js
  src/components/tabs/README.md
  src/directives/visible.js
Labels: Type: Enhancement, Type: Fix

#3950 fix(changelog): correct typos
  CHANGELOG-OLD.md
  CHANGELOG.md
Labels: Type: Fix

#3963 feat(toast): add support for scoped styles
  src/components/toast/toast.js
Labels: Type: Enhancement

#3965 chore(docs): add links to the router-link reference section to all components that support router-links
  src/components/breadcrumb/README.md
  src/components/list-group/README.md
  src/components/navbar/README.md
  src/components/pagination-nav/README.md
Labels: Type: Docs

#3967 chore: improve scoped styles `scopeId` handling
  src/components/card/card-body.js
  src/components/card/card-footer.js
  src/components/card/card-header.js
  src/components/card/card.js
  src/components/modal/modal.js
  src/components/toast/toast.js
  src/components/tooltip/helpers/bv-tooltip-template.js
  src/components/tooltip/helpers/bv-tooltip.js
  src/components/tooltip/tooltip.js
  src/directives/popover/popover.js
  src/directives/tooltip/tooltip.js
  src/mixins/card.js
  src/mixins/scoped-style-attrs.js
  src/utils/get-scope-id.js
Labels: Type: Enhancement

#3968 feat(b-table): new sorting icons using SVG, plus option to place icon on left of header cell (closes #3687, #3696, #3918, #3966)
  src/_variables.scss
  src/components/table/README.md
  src/components/table/_table.scss
  src/components/table/helpers/mixin-sorting.js
Labels: Status: Breaking Change, Type: Enhancement, Type: Fix, Type: SCSS

#3976 fix(b-link): only add the `nativeOn` property to componentData when rendering a router link
  src/components/link/link.js
Labels: Type: Fix

#3977 feat(b-img-lazy): switch IntersectionObserver to use private `v-b-visible` directive
  src/components/card/card-img-lazy.spec.js
  src/components/image/README.md
  src/components/image/img-lazy.js
  src/components/image/img-lazy.spec.js
  src/directives/visible.js
Labels: Status: Breaking Change, Type: Refactor

#3979 feat(modal): add prop for auto focusing one of the built in-buttons once `shown` (closes #3945)
  src/components/modal/README.md
  src/components/modal/modal.js
  src/components/modal/modal.spec.js
Labels: Type: Enhancement

#3983 chore(docs): add an advanced usage section and example for modal message boxes (closes #3982)
  src/components/modal/README.md
  src/components/toast/README.md
  src/mixins/normalize-slot.js
  src/utils/normalize-slot.js
  src/utils/transporter.js
Labels: Type: Docs

#3986 feat(b-table, b-table-lite): switch slot name syntax to use round brackets instead of square brackets
  docs/components/componentdoc.vue
  docs/components/importdoc.vue
  src/components/table/README.md
  src/components/table/helpers/mixin-tbody-row.js
  src/components/table/helpers/mixin-thead.js
  src/components/table/table-row-details.spec.js
  src/components/table/table-tbody-row-events.spec.js
  src/components/table/table-tfoot-events.spec.js
  src/components/table/table-thead-events.spec.js
Labels: Status: Breaking Change, Type: Refactor

#3987 feat(table): add `no-border-collapse` prop and SCSS
  src/components/table/README.md
  src/components/table/_table.scss
  src/components/table/helpers/mixin-table-renderer.js
  src/components/table/table.spec.js
Labels: Type: Enhancement, Type: Feature

#3990 feat(b-pagination): if number of pages changes, try and keep current page active (closes #3716)
  src/components/pagination/pagination.js
  src/components/pagination/pagination.spec.js
Labels: Type: Enhancement

#3991 chore(docs): remove duplicate IDs from dropdown examples
  src/components/dropdown/README.md
Labels: Type: Accessibility, Type: Docs

#3992 feat(b-table, b-table-lite): use `aria-details` rather than `aria-describedby` when details row showing (addresses #3801)
  src/components/table/helpers/mixin-tbody-row.js
Labels: Type: Accessibility, Type: Enhancement

#3993 chore(pagination): change `role="none presentation"` to `role="presentation"` (closes #2921)
  src/components/pagination/pagination.spec.js
  src/mixins/pagination.js
Labels: Type: Accessibility
