Repository bootstrap-vue/bootstrap-vue, pull requests merged in 2019-07, with the labels that each got.

#3602 chore(docs): fix typo in form-group docs (closes #3601)
  src/components/form-group/README.md
Labels: Type: Docs

#3605 fix(docs): correct polyfilling suggestions
  docs/markdown/intro/README.md
  docs/markdown/reference/router-links/README.md
  docs/nuxt.config.js
Labels: Type: Docs, Type: Enhancement

#3606 fix(playground): fix undefined variable error in IE 11
  docs/assets/scss/styles.scss
  docs/pages/play.vue
Labels: Type: Docs, Type: Fix

#3608 fix(b-collapse): fix memory leak from `$root` listener (fixes #3607)
  src/components/collapse/collapse.js
Labels: Type: Fix

#3609 docs(getting started): add section on required HTML tags
  docs/markdown/intro/README.md
Labels: Type: Docs

#3612 docs: use SVG logo on index page
  docs/nuxt.config.js
  docs/pages/index.vue
  docs/static/icon.png
  docs/static/logo.svg
  static/banner.png
  static/logo-padded.png
  static/logo.png
Labels: Type: Docs, Type: Enhancement

#3613 docs: add some pizazz to index page
  docs/assets/scss/styles.scss
  docs/components/codemirror.js
  docs/components/footer.vue
  docs/components/header.vue
  docs/components/importdoc.vue
  docs/markdown/intro/README.md
  docs/nuxt.config.js
  docs/pages/docs/misc/_slug.js
  docs/pages/index.vue
  docs/pages/play.vue
  docs/plugins/play.js
  docs/utils/hljs.js
Labels: Type: Docs

#3621 docs: minor tweaks
  CHANGELOG.md
  docs/assets/scss/styles.scss
  docs/components/footer.vue
  docs/layouts/docs.js
  docs/pages/index.vue
  docs/pages/play.vue
  src/components/list-group/README.md
  src/components/popover/README.md
  src/components/tooltip/README.md
Labels: Type: Docs

#3625 docs: add section on transpiling source code to getting started section
  docs/markdown/intro/README.md
Labels: Type: Docs

#3632 docs: add a few media queries to landing page
  docs/assets/scss/styles.scss
  docs/nuxt.config.js
  docs/pages/index.vue
Labels: Type: Docs

#3636 feat(types): add `noCloseButton` property to `BvToastOptions` type declaration
  src/components/toast/index.d.ts
Labels: Type: Enhancement, Type: Types

#3639 feat(b-dropdown, b-nav-item-dropdown): add new lazy prop (addresses #3634)
  src/components/dropdown/README.md
  src/components/dropdown/dropdown.js
  src/components/dropdown/dropdown.spec.js
  src/components/nav/README.md
  src/components/nav/nav-item-dropdown.js
  src/mixins/dropdown.js
Labels: Type: Enhancement, Type: Feature, Type: Perf

#3637 perf(b-link): convert functional component to regular component (closes #3634)
  src/components/dropdown/dropdown-item.spec.js
  src/components/link/index.d.ts
  src/components/link/link.js
  src/components/link/link.spec.js
  src/utils/router.js
Labels: Type: Fix, Type: Perf

#3641 perf: remove default array/object polyfills
  docs/markdown/intro/README.md
  docs/markdown/reference/starter-templates/README.md
  package.json
  scripts/rollup.config.js
  src/components/nav/README.md
  src/utils/array.js
  src/utils/object.js
  yarn.lock
Labels: Type: Perf

#3643 docs(tabs): fix dynamic tabs example to work with IE 11
  src/components/tabs/README.md
Labels: Type: Docs

#3631 docs: update contributing formatting for logos
  CONTRIBUTING.md
Labels: Type: Docs

#3644 feat(tooltip, popover): add support for contextual variants and custom class (closes #1983, #2075)
  src/_variables.scss
  src/components/index.scss
  src/components/popover/README.md
  src/components/popover/_popover.scss
  src/components/popover/index.scss
  src/components/popover/package.json
  src/components/popover/popover.js
  src/components/popover/popover.spec.js
  src/components/tooltip/README.md
  src/components/tooltip/_tooltip.scss
  src/components/tooltip/index.scss
  src/components/tooltip/package.json
  src/components/tooltip/tooltip.js
  src/components/tooltip/tooltip.spec.js
  src/directives/popover/README.md
  src/directives/popover/package.json
  src/directives/popover/popover.js
  src/directives/tooltip/README.md
  src/directives/tooltip/package.json
  src/directives/tooltip/tooltip.js
  src/directives/tooltip/tooltip.spec.js
  src/mixins/toolpop.js
  src/utils/config-defaults.js
  src/utils/tooltip.class.js
Labels: Type: Feature

#3645 docs: animate logo on load
  docs/pages/index.vue
Labels: Type: Docs

#3648 docs: don't collapses toc sub-sections when position sticky not supported
  docs/assets/scss/styles.scss
Labels: Type: Docs

#3651 docs(table): add `responsive="sm"` to some of the wider table examples
  src/components/table/README.md
Labels: Type: Docs

#3653 feat(tooltip): add in SCSS support for specifying tooltip variant background color level
  docs/markdown/reference/color-variants/README.md
  src/_variables.scss
  src/components/popover/_popover.scss
  src/components/tooltip/_tooltip.scss
Labels: Type: Enhancement, Type: SCSS

#3654 feat(docs): add home and playground links to sidebar navigation
  docs/components/sidebar.vue
Labels: Type: Docs

#3658 docs(carousel): document the `content-visible-up` property
  src/components/carousel/README.md
Labels: Type: Docs

#3662 fix(carousel-slide): do not render `carousel-caption` wrapper if no content
  src/components/carousel/carousel-slide.js
  src/components/carousel/carousel-slide.spec.js
Labels: Type: Fix

#3664 docs: minor tweaks to landing page
  docs/pages/index.vue
Labels: Type: Docs

#3670 docs(router support): add link to router api reference
  docs/markdown/reference/router-links/README.md
Labels: Type: Docs

#3675 chore(docs): remove duplication of "nav-item"
  src/components/tabs/README.md
Labels: Type: Docs

#3677 chore(docs): remove extra dot
  src/components/tabs/README.md
Labels: Type: Docs

#3679 feat(tabs): new named slot `tabs-start` for prepending tab buttons, deprecates `tabs` slot in favour of `tabs-end` (closes #3678)
  src/components/tabs/README.md
  src/components/tabs/package.json
  src/components/tabs/tabs.js
Labels: Status: WIP, Type: Enhancement

#3695 feat(b-dropdown): new `split-button-type` prop to specify split button type (closes #3694)
  src/components/dropdown/README.md
  src/components/dropdown/dropdown.js
  src/components/dropdown/dropdown.spec.js
Labels: Type: Enhancement

#3697 fix(b-table): IE11 edge case where custom inputs were not clickable in clickable/sortable cells (fixes #3693)
  src/components/table/helpers/filter-event.js
  src/components/table/table-tbody-row-events.spec.js
Labels: Type: Fix

#3698 chore(docs/playground): increase debounce timeout on browsers that need transpilation
  docs/components/codemirror.js
  docs/nuxt.config.js
  docs/pages/play.vue
  docs/plugins/codemirror.js
  docs/utils/code-mirror.js
Labels: Status: WIP, Type: Docs, Type: Enhancement

#3704 fix(tooltip, popover): handle case where tooltips are applied to dropdown root elements (closes #3703)
  src/directives/popover/README.md
  src/mixins/dropdown.js
  src/utils/tooltip.class.js
Labels: Type: Enhancement, Type: Fix

#3709 chore(docs): minor updates to toast documentation
  src/components/toast/README.md
Labels: Type: Docs

#3706 fix(b-nav-item-dropdown): clicking toggle a second time should close menu (closes #3707)
  src/components/dropdown/dropdown.spec.js
  src/components/nav/nav-item-dropdown.js
  src/mixins/dropdown.js
Labels: PR: Patch, Type: Fix

#3713 fix(b-modal): ensure header is read for accessibility with JAWS (closes #3712)
  src/components/modal/modal.js
Labels: PR: Patch, Status: WIP, Type: Accessibility, Type: Fix

#3718 chore(docs): minor tweak to landing page
  docs/pages/index.vue
Labels: Type: Docs

#3715 feat(b-modal): for accessibility, read only modal title and not whole header + additional A11Y options (addresses #3712)
  src/components/modal/README.md
  src/components/modal/modal.js
Labels: Type: Accessibility, Type: Enhancement

#3725 chore(docs): add implemetation note on auto-height textarea (closes #3716)
  src/components/form-textarea/README.md
Labels: Type: Docs

#3728 chore(docs): inform where a file should be dropped
  src/components/form-file/README.md
Labels: Type: Docs

#3727 chore(toasts): remove beta status
  src/components/toast/README.md
  src/components/toast/package.json
Labels: PR: Patch, Type: Docs

#3734 fix(carousel): reset `touchDeltaX` to prevent click transformed in swipe
  src/components/carousel/carousel.js
Labels: PR: Patch, Type: Fix

#3735 chore(docs): add aria-labels to navigation regions, add role to search region
  docs/components/search.vue
  docs/components/sidebar.vue
  docs/layouts/docs.js
Labels: PR: Patch, Type: Accessibility, Type: Docs

#3738 chore: prepare for new Bootstrap versions
  .github/renovate.json
  package.json
  renovate.json
  yarn.lock
Labels: Type: Dependencies, Type: Enhancement

#3740 chore(docs): minor fixes to getting started docs
  docs/markdown/intro/README.md
Labels: Type: Docs

#3744 chore(docs/utils): don't match versions preceded by `<`
  docs/markdown/intro/README.md
  docs/pages/docs/index.js
  docs/utils/index.js
Labels: Type: Docs

#3741 feat(b-table, b-table-lite): new field scoped slot naming convention + new fallback scoped slots, deprecated old field slot convention (closes #3731)
  docs/components/componentdoc.vue
  docs/components/importdoc.vue
  src/components/table/README.md
  src/components/table/helpers/mixin-tbody-row.js
  src/components/table/helpers/mixin-thead.js
  src/components/table/package.json
  src/mixins/normalize-slot.js
  src/utils/normalize-slot.js
  src/utils/normalize-slot.spec.js
Labels: PR: Patch, Type: Enhancement

#3748 chore(docs): convert clicks on internal docs links to `$router.push()` or `scrollIntoView`
  docs/components/section.js
  src/components/table/README.md
  src/components/table/package.json
Labels: Type: Docs, Type: Enhancement, Type: Perf

#3754 feat(b-form-file, b-form-checkbox, b-form-radio): make input element inherit non-prop attributes (addresses #3752)
  src/components/form-checkbox/form-checkbox.spec.js
  src/components/form-file/form-file.js
  src/components/form-file/form-file.spec.js
  src/components/form-radio/form-radio.spec.js
  src/mixins/form-radio-check.js
Labels: Type: Enhancement

#3743 chore(docs): automatically add `rel` and `target` attrs to external links + link formatting
  CONTRIBUTING.md
  README.md
  docs/markdown/reference/accessibility/README.md
  docs/markdown/reference/utility-classes/README.md
  docs/nuxt.config.js
  src/components/table/README.md
Labels: Type: Docs

#3763 fix(table): better detection of active text selection during click events (closes #3757)
  src/components/table/helpers/text-selection-active.js
Labels: Type: Fix

#3767 chore(docs): minor tweak to in-page link handling
  docs/components/section.js
Labels: Type: Docs

#3768 chore(bv-modal): make `msgBox` method private
  src/components/modal/helpers/bv-modal.js
  src/components/modal/index.d.ts
Labels: PR: Patch

#3760 chore(docs): update navbar brand logo
  docs/components/header.vue
Labels: Type: Docs

#3775 feat(toast): add SCSS variable for default toast background opacity + standardize a few BootstrapVue SCSS variable names
  src/_variables.scss
  src/components/popover/_popover.scss
  src/components/table/_table.scss
  src/components/toast/README.md
  src/components/toast/_toast.scss
  src/components/tooltip/_tooltip.scss
  src/utils/config-defaults.js
Labels: Type: Feature, Type: SCSS

#3777 chore(docs): correct end tag in example
  src/components/popover/README.md
Labels: Type: Docs

#3776 chore(docs): style tweaks for landing page
  docs/assets/scss/styles.scss
  docs/pages/index.vue
Labels: Type: Docs

#3778 feat(b-table): make sorting by formated value opt-in per field + add TypeScript declarations for locale options
  src/components/table/README.md
  src/components/table/helpers/mixin-sorting.js
  src/components/table/index.d.ts
  src/components/table/table-sorting.spec.js
Labels: Type: Enhancement, Type: Feature, Type: Types

#3785 chore(docs): minor updates to the toast, modal and form-select docs
  CHANGELOG.md
  docs/assets/scss/styles.scss
  docs/markdown/reference/accessibility/README.md
  src/_variables.scss
  src/components/form-select/README.md
  src/components/form-textarea/README.md
  src/components/modal/README.md
  src/components/modal/package.json
  src/components/toast/README.md
  src/components/toast/_toast.scss
  src/components/toast/package.json
Labels: Type: Docs

#3786 feat(b-table): allow users to specify top-level keys to be ignored or included when filtering, + option to filter based on formatted value (closes #3749)
  src/components/table/README.md
  src/components/table/helpers/mixin-filtering.js
  src/components/table/helpers/mixin-items.js
  src/components/table/helpers/sanitize-row.js
  src/components/table/helpers/stringify-record-values.js
  src/components/table/index.d.ts
Labels: Type: Enhancement, Type: Feature

#3788 chore(docs): minor updates and clarification to table docs
  src/components/table/README.md
Labels: Type: Docs

#3790 feat(docs): update to the theming reference section
  docs/markdown/reference/theming/README.md
  docs/pages/index.vue
Labels: Type: Docs, Type: Enhancement
