Repository bootstrap-vue/bootstrap-vue, pull requests merged in 2019-04, with the labels that each got.

#2969 chore(alert): code refactoring (closes #2967)
  src/components/alert/README.md
  src/components/alert/alert.js
  src/components/alert/alert.spec.js
  src/components/alert/package.json
Labels: Type: Enhancement, Type: Fix

#2970 docs(table): make examples work better on small screens
  src/components/table/README.md
Labels: Type: Docs

#2952 feat(docs): algolia powered search
  docs/assets/scss/styles.scss
  docs/components/componentdoc.vue
  docs/components/importdoc.vue
  docs/components/search.vue
  docs/nuxt.config.js
  docs/pages/docs/index.js
  docs/pages/docs/misc/_slug.vue
  docs/pages/docs/reference/_slug.vue
  docs/pages/play.vue
  docs/utils/index.js
Labels: Type: Docs, Type: Enhancement

#2971 chore(unit testing): img, nav and form test conversion
  src/components/form/fixtures/form-row.html
  src/components/form/fixtures/form-row.js
  src/components/form/fixtures/form-text.html
  src/components/form/fixtures/form-text.js
  src/components/form/fixtures/form.html
  src/components/form/fixtures/form.js
  src/components/form/form-row.spec.js
  src/components/form/form-text.spec.js
  src/components/form/form.spec.js
  src/components/image/img-lazy.spec.js
  src/components/image/img.spec.js
  src/components/nav/fixtures/nav.html
  src/components/nav/fixtures/nav.js
  src/components/nav/nav-form.spec.js
  src/components/nav/nav-text.spec.js
  src/components/nav/nav.spec.js
Labels: Type: Unit Testing

#2973 chore(unit testing): convert jumbotron test
  src/components/jumbotron/jumbotron.spec.js
Labels: Type: Unit Testing

#2976 docs: minor update to form lead-in example
  src/components/form/README.md
Labels: Type: Docs

#2974 chore(unit testing): dropdown tests
  src/components/dropdown/dropdown-divider.spec.js
  src/components/dropdown/dropdown-header.spec.js
  src/components/dropdown/dropdown.spec.js
  src/components/dropdown/fixtures/dropdown.html
  src/components/dropdown/fixtures/dropdown.js
  src/mixins/dropdown.js
Labels: Type: Unit Testing

#2979 chore(unit tests): collapse tests
  src/components/collapse/collapse.js
  src/components/collapse/collapse.spec.js
  src/components/collapse/fixtures/collapse.html
  src/components/collapse/fixtures/collapse.js
  src/directives/toggle/toggle.spec.js
Labels: Type: Unit Testing

#2981 chore(docs): adjustments to tooltip/popover docs
  src/directives/tooltip/README.md
Labels: Type: Docs

#2982 fix(utils/get): handle case when nested value is falsy
  src/utils/get.js
  src/utils/get.spec.js
Labels: Type: Fix

#2983 chore(unit testing): convert link tests
  src/components/link/fixtures/link.html
  src/components/link/fixtures/link.js
  src/components/link/link.js
  src/components/link/link.spec.js
Labels: Type: Unit Testing

#2984 chore(unit testing): form-group test conversion
  src/components/form-group/fixtures/form-group.html
  src/components/form-group/fixtures/form-group.js
  src/components/form-group/form-group.js
  src/components/form-group/form-group.spec.js
Labels: Type: Unit Testing

#2991 fix(breadcrumb-item): remove `role="presentation"` (closes #2988)
  src/components/breadcrumb/breadcrumb-item.js
  src/components/breadcrumb/breadcrumb-item.spec.js
Labels: Type: Accessibility, Type: Fix

#2993 fix(pagination): reset to page 1 when total-rows or per-page changes (closes #2987)
  src/components/pagination/pagination.js
  src/components/pagination/pagination.spec.js
  src/components/table/README.md
Labels: Type: Fix

#2994 chore(unit testing): modal test updates
  src/components/modal/fixtures/modal.html
  src/components/modal/fixtures/modal.js
  src/components/modal/modal-defaults.spec.js
  src/components/modal/modal.js
  src/components/modal/modal.spec.js
Labels: Type: Unit Testing

#2997 docs(table): minor updates to table complete example
  src/components/table/README.md
Labels: Type: Docs

#3000 chore(unit testing): convert tooltip and popover tests
  src/components/popover/fixtures/popover.html
  src/components/popover/fixtures/popover.js
  src/components/popover/popover.js
  src/components/popover/popover.spec.js
  src/components/tooltip/fixtures/tooltip.html
  src/components/tooltip/fixtures/tooltip.js
  src/components/tooltip/tooltip.js
  src/components/tooltip/tooltip.spec.js
  src/directives/popover/popover.spec.js
  src/directives/tooltip/tooltip.spec.js
  src/mixins/toolpop.js
  src/utils/popover.class.js
  src/utils/tooltip.class.js
Labels: Type: Unit Testing

#3001 fix(tooltip/popover): prevent double show/shown event emits when .sync modifier used (fixes #1637)
  src/mixins/toolpop.js
  src/utils/tooltip.class.js
Labels: Type: Fix

#3005 fix(docs): fix the closing tag for `<b-table>` in pagination example
  src/components/pagination/README.md
Labels: Type: Docs

#3009 chore(unit testing): convert carousel tests to vue-test-utils
  src/components/carousel/carousel.js
  src/components/carousel/carousel.spec.js
  src/components/carousel/fixtures/carousel.html
  src/components/carousel/fixtures/carousel.js
  src/components/nav/nav-item-dropdown.spec.js
  tests/utils.js
Labels: Type: Unit Testing

#2867 feat(table): add TypeScript definitions for table fields
  docs/markdown/reference/color-variants/README.md
  src/components/table/README.md
  src/index.d.ts
Labels: Type: Enhancement

#3012 fix(form-textarea): improved computedHeight calculation when in auto resize mode
  src/components/form-textarea/form-textarea.js
Labels: Type: Enhancement, Type: Fix

#3021 fix(v-b-toggle/b-collapse): ensure toggle remains in sync with collapse (Closes #3020)
  src/components/collapse/collapse.js
  src/components/navbar/navbar-toggle.js
  src/components/navbar/navbar-toggle.spec.js
  src/directives/toggle/toggle.js
  src/directives/toggle/toggle.spec.js
  src/utils/config.js
Labels: Type: Enhancement, Type: Fix

#3023 fix(modal): z-index adjustments in PR #3017
  docs/plugins/bootstrap-vue.js
  src/components/modal/helpers/modal-manager.js
  src/components/modal/modal.js
  src/components/modal/modal.spec.js
  src/mixins/listen-on-root.js
  src/mixins/listen-on-root.spec.js
  src/utils/config.js
  src/utils/dom.js
Labels: Type: Enhancement

#3017 fix(modal): stacked modal z-index calculations (closes #3015)
  docs/plugins/bootstrap-vue.js
  src/components/modal/helpers/modal-manager.js
  src/components/modal/modal.js
  src/components/modal/modal.spec.js
  src/mixins/listen-on-root.js
  src/mixins/listen-on-root.spec.js
  src/utils/dom.js
Labels: Type: Enhancement, Type: Fix

#3029 fix(modal): prevent close on backdrop when click initiated inside modal content (fixes #3025)
  src/components/modal/modal.js
  src/components/modal/modal.spec.js
Labels: Type: Fix

#3030 chore(docs): fix typo in table complete example
  src/components/table/README.md
Labels: Type: Docs, Type: Fix

#3031 docs: custom marked formatter for lead-in blockquotes
  CHANGELOG.md
  CONTRIBUTING.md
  docs/markdown/misc/settings/README.md
  docs/markdown/reference/theming/README.md
  docs/markdown/reference/validation/README.md
  docs/nuxt.config.js
  src/components/collapse/README.md
  src/components/table/README.md
Labels: Type: Docs

#3024 feat(BvEvent): subclass BvEvent as BvModalEvent
  src/components/modal/README.md
  src/components/modal/helpers/bv-modal-event.class.js
  src/components/modal/helpers/bv-modal-event.class.spec.js
  src/components/modal/modal.js
  src/components/modal/modal.spec.js
  src/components/modal/package.json
  src/utils/bv-event.class.js
  src/utils/bv-event.class.spec.js
Labels: Type: Enhancement

#3033 feat(modal): auto return focus to trigger elements using document.activeElement
  src/components/modal/modal.js
  src/components/modal/modal.spec.js
Labels: Type: Enhancement

#3043 fix(typescript): replaced invalid `mixed` keyword with `any` (fixes #3041)
  src/index.d.ts
Labels: Type: Fix, Type: Types

#3046 fix(build): enable babel option to interop default (fixes #3038)
  babel.config.js
Labels: Type: Fix

#3048 feat(nuxt): add `usePretranspiled` option
  docs/markdown/intro/README.md
  nuxt/index.js
  nuxt/plugin.template.js
Labels: Type: Enhancement, Type: Nuxt.js

#3054 fix(docs): improve <b-modal> prevent closing example (closes #2497)
  src/components/modal/README.md
Labels: Type: Docs, Type: Enhancement

#3060 docs(modal): minor udpates to modal docs
  src/components/modal/README.md
Labels: Type: Docs

#3068 fix(modal): clear internal return_focus value after modal closes (fixes #3067)
  src/components/modal/modal.js
Labels: Type: Fix

#3071 feat(docs/playground): add support for exporting to CodePen and CodeSandbox
  docs/assets/scss/styles.scss
  docs/pages/play.vue
  package.json
  yarn.lock
Labels: Type: Docs, Type: Enhancement

#3081 chore(docs): fix some heading levels and remove necessary blockquote sections that are not the lead in paragraph
  docs/markdown/intro/README.md
  src/components/popover/README.md
  src/components/tooltip/README.md
Labels: Type: Docs

#3078 fix(docs): improve code highlighting + table styles
  CHANGELOG.md
  docs/assets/scss/styles.scss
  docs/components/anchored-heading.js
  docs/components/componentdoc.vue
  docs/components/importdoc.vue
  docs/components/main.js
  docs/components/section.js
  docs/markdown/intro/README.md
  docs/markdown/misc/settings/README.md
  docs/nuxt.config.js
  docs/pages/docs/components/_slug.js
  docs/pages/docs/components/_slug.vue
  docs/pages/docs/directives/_slug.js
  docs/pages/docs/directives/_slug.vue
  docs/pages/docs/index.js
  docs/pages/docs/misc/_slug.js
  docs/pages/docs/misc/_slug.vue
  docs/pages/docs/reference/_slug.js
  docs/pages/docs/reference/_slug.vue
  docs/plugins/play.js
  docs/utils/index.js
  package.json
  src/components/modal/README.md
  yarn.lock
Labels: Type: Docs

#3086 fix(table): prevent hover style on busy/empty row (closes #3079)
  src/components/table/_table.scss
  src/components/table/table.js
Labels: Type: Enhancement

#3087 feat(dropdown): use semantic `<ul>` and `<li>` markup (closes #3072)
  src/components/dropdown/dropdown-divider.js
  src/components/dropdown/dropdown-divider.spec.js
  src/components/dropdown/dropdown-form.js
  src/components/dropdown/dropdown-form.spec.js
  src/components/dropdown/dropdown-header.js
  src/components/dropdown/dropdown-header.spec.js
  src/components/dropdown/dropdown-item-button.js
  src/components/dropdown/dropdown-item-button.spec.js
  src/components/dropdown/dropdown-item.js
  src/components/dropdown/dropdown-item.spec.js
  src/components/dropdown/dropdown-text.js
  src/components/dropdown/dropdown-text.spec.js
  src/components/dropdown/dropdown.js
  src/components/dropdown/dropdown.spec.js
  src/components/nav/nav-item-dropdown.js
  src/mixins/dropdown.js
  src/utils/object.js
Labels: Type: Accessibility, Type: Enhancement

#3084 fix(b-link): ensure href prop is not passed to router-links (fixes #3066)
  src/components/dropdown/dropdown-item.js
  src/components/dropdown/dropdown-item.spec.js
  src/components/dropdown/dropdown.spec.js
  src/components/link/link.js
  src/components/link/link.spec.js
Labels: Type: Fix

#3056 feat(modal): support for optionally scoped slots and new `Vue.prototype.$bvModal` helper
  src/components/modal/README.md
  src/components/modal/helpers/bv-modal-event.class.js
  src/components/modal/helpers/bv-modal.js
  src/components/modal/helpers/bv-modal.spec.js
  src/components/modal/helpers/modal-manager.js
  src/components/modal/index.js
  src/components/modal/modal.js
  src/components/modal/modal.spec.js
  src/components/modal/package.json
  src/utils/env.js
  src/utils/inspect.js
  src/utils/inspect.spec.js
Labels: Type: Enhancement, Type: Feature

#3104 chore: improve issue templates
  .github/ISSUE_TEMPLATE.md
  .github/ISSUE_TEMPLATE/BUG_REPORT_TEMPLATE.md
  .github/ISSUE_TEMPLATE/FEATURE_REQUEST_TEMPLATE.md
Labels: Type: Enhancement

#3101 fix(docs): unify heading casing
  CODE_OF_CONDUCT.md
  docs/markdown/intro/README.md
  docs/markdown/misc/settings/README.md
  docs/markdown/reference/images/README.md
  docs/markdown/reference/router-links/README.md
  docs/markdown/reference/router-links/meta.json
  docs/markdown/reference/size-props/README.md
  docs/markdown/reference/theming/README.md
  docs/markdown/reference/theming/meta.json
  docs/markdown/reference/validation/README.md
  src/components/alert/README.md
  src/components/badge/README.md
  src/components/breadcrumb/README.md
  src/components/breadcrumb/package.json
  src/components/button-toolbar/README.md
  src/components/button/README.md
  src/components/button/package.json
  src/components/card/README.md
  src/components/carousel/README.md
  src/components/collapse/README.md
  src/components/dropdown/README.md
  src/components/embed/README.md
  src/components/form-checkbox/README.md
  src/components/form-file/README.md
  src/components/form-group/README.md
  src/components/form-input/README.md
  src/components/form-radio/README.md
  src/components/form-select/README.md
  src/components/form-textarea/README.md
  src/components/form/README.md
  src/components/image/README.md
  src/components/input-group/README.md
  src/components/jumbotron/README.md
  src/components/layout/README.md
  src/components/link/README.md
  src/components/list-group/README.md
  src/components/media/README.md
  src/components/media/package.json
  src/components/modal/README.md
  src/components/nav/README.md
  src/components/navbar/README.md
  src/components/navbar/package.json
  src/components/pagination-nav/README.md
  src/components/pagination/README.md
  src/components/progress/README.md
  src/components/table/README.md
  src/components/tabs/README.md
  src/components/tooltip/README.md
  src/directives/scrollspy/README.md
Labels: Type: Docs

#3105 fix(form-textarea): improve auto-row height calculation timing (closes #3103)
  src/components/form-textarea/form-textarea.js
Labels: Type: Enhancement, Type: Fix

#3109 chore: stick to `core-js` v2 + better docs polyfill (closes #3108)
  docs/nuxt.config.js
  package.json
  yarn.lock
Labels: Type: Docs, Type: Fix

#3111 chore: revert `yarn.lock` changes
  yarn.lock
Labels: Type: Fix

#3112 chore: fix issue template prose wrap
  .github/ISSUE_TEMPLATE/BUG_REPORT_TEMPLATE.md
  .github/PULL_REQUEST_TEMPLATE.md
  .prettierrc
Labels: Type: Fix

#3114 fix(docs): fix polyfill for IE 11
  docs/markdown/intro/README.md
  docs/nuxt.config.js
Labels: Type: Docs, Type: Fix

#3117 fix(modal): close on click-out for IE11 (closes #3115)
  src/components/modal/modal.js
Labels: Type: Fix

#3121 fix(docs): minor tweaks
  docs/components/sidebar.vue
  docs/markdown/intro/README.md
  src/components/modal/package.json
Labels: Type: Docs

#3122 fix(docs): improve nav social links alignment
  docs/components/nav.vue
Labels: Type: Docs

#3061 feat(tabs): add `fill`, `justified` and active class props (closes #3053, #2518)
  src/components/nav/README.md
  src/components/nav/nav-form.js
  src/components/nav/nav.js
  src/components/nav/nav.spec.js
  src/components/nav/package.json
  src/components/navbar/navbar-nav.js
  src/components/navbar/navbar-nav.spec.js
  src/components/tabs/README.md
  src/components/tabs/package.json
  src/components/tabs/tab.js
  src/components/tabs/tabs.js
  src/components/tabs/tabs.spec.js
Labels: Status: WIP, Type: Enhancement, Type: Feature

#3123 fix(modal): handle HMR when defining property on Vue prototype
  src/components/modal/helpers/bv-modal.js
Labels: Type: Fix

#3093 feat(toast): add Bootstrap v4.3 Toasts
  docs/assets/scss/styles.scss
  docs/components/componentdoc.vue
  docs/content/index.js
  docs/markdown/intro/README.md
  docs/pages/docs/index.js
  package.json
  scripts/rollup.config.js
  src/_variables.scss
  src/components/index.js
  src/components/index.scss
  src/components/modal/modal.spec.js
  src/components/toast/README.md
  src/components/toast/_toast.scss
  src/components/toast/_toaster-transition.scss
  src/components/toast/_toaster.scss
  src/components/toast/helpers/bv-toast.js
  src/components/toast/index.js
  src/components/toast/index.scss
  src/components/toast/package.json
  src/components/toast/toast.js
  src/components/toast/toaster.js
  src/utils/config.js
  yarn.lock
Labels: Type: Feature

#3129 fix(docs): overall improvements
  docs/assets/fonts/Inconsolata-Regular-latin-ext.woff2
  docs/assets/fonts/Inconsolata-Regular-latin.woff2
  docs/assets/fonts/Inconsolata-Regular-vietnamese.woff2
  docs/assets/scss/fonts.scss
  docs/assets/scss/styles.scss
  docs/components/anchored-heading.js
  docs/components/codemirror.js
  docs/components/componentdoc.vue
  docs/components/feedback.js
  docs/components/footer.vue
  docs/components/header.vue
  docs/components/importdoc.vue
  docs/components/jsfiddle.vue
  docs/components/main.js
  docs/components/nav.vue
  docs/components/search.vue
  docs/components/section.js
  docs/components/sidebar.vue
  docs/components/toc.vue
  docs/layouts/default.js
  docs/layouts/default.vue
  docs/layouts/docs.js
  docs/layouts/docs.vue
  docs/pages/docs/components/_slug.js
  docs/pages/docs/directives/_slug.js
  docs/pages/docs/index.js
  docs/pages/docs/misc/_slug.js
  docs/pages/docs/reference/_slug.js
  docs/pages/play.vue
  docs/plugins/codemirror.js
  docs/static/click-confirm.png
  docs/utils/index.js
  src/components/form-file/README.md
  src/components/toast/README.md
Labels: Type: Docs, Type: Enhancement

#3130 fix(toaster): let on-demand toasts know the toaster has been destroyed
  src/_variables.scss
  src/components/toast/README.md
  src/components/toast/_toaster.scss
  src/components/toast/helpers/bv-toast.js
  src/components/toast/package.json
  src/components/toast/toast.js
  src/components/toast/toaster.js
Labels: Type: Fix

#3133 docs: add note about setting up an alias to `vue` in project bundlers
  docs/markdown/intro/README.md
Labels: Type: Docs

#3131 fix(modal): ensure that v-model is updated when show or hide is canceled
  src/components/modal/modal.js
Labels: Type: Fix

#3135 feat(toast): updates to toaster SCSS and structure and enable hover-pause
  src/_variables.scss
  src/components/toast/README.md
  src/components/toast/_toaster.scss
  src/components/toast/toast.js
  src/components/toast/toaster.js
Labels: Type: Enhancement

#3142 fix(nuxt module): ensure that css and transpile are arrays (fixes: #3141)
  nuxt/index.js
Labels: Type: Fix, Type: Nuxt.js

#3140 feat(form-checkbox, form-radio): add `aria-labelledby` prop (closes: #3139)
  src/mixins/form-radio-check.js
Labels: Type: Accessibility, Type: Feature

#3125 fix(col, form-group): implement self overwriting lazy props getter (fixes: #3080)
  src/components/form-group/form-group.js
  src/components/layout/col.js
  src/utils/config.js
Labels: Type: Fix

#3145 fix(docs): info modal in complete <b-table> example (closes #3144)
  src/components/table/README.md
Labels: Type: Docs, Type: Fix

#3147 fix(docs): use regex to normalize URL with better browser support
  docs/components/sidebar.vue
Labels: Type: Docs, Type: Fix

#3149 chore(docs): minor updates to toast docs
  src/components/toast/README.md
Labels: Type: Docs

#3148 feat(table): add new prop `table-class` for applying classes to table root element (closes #3138)
  src/components/table/table.js
Labels: Type: Feature

#3160 fix(toast): use appendChild insated of append for IE 11 support
  src/components/toast/toast.js
Labels: Type: Fix

#3163 fix(docs): typo in ´<strong>´ tags
  src/components/table/README.md
  src/directives/popover/README.md
  src/directives/tooltip/README.md
Labels: Type: Docs

#3157 feat(modal): use PortalVue for modal placement
  src/components/modal/README.md
  src/components/modal/helpers/bv-modal-event.class.js
  src/components/modal/helpers/bv-modal-event.class.spec.js
  src/components/modal/helpers/bv-modal.js
  src/components/modal/helpers/bv-modal.spec.js
  src/components/modal/helpers/modal-manager.js
  src/components/modal/helpers/modal-target.js
  src/components/modal/modal.js
  src/components/modal/modal.spec.js
  src/components/modal/package.json
  src/utils/bv-event.class.js
Labels: Type: Enhancement

#3167 feat(v-b-toggle): make targets reactive to updates (closes #3165)
  src/components/collapse/collapse.js
  src/components/collapse/collapse.spec.js
  src/directives/toggle/toggle.js
  src/utils/target.js
Labels: Type: Enhancement

#3170 feat(toast): add additional options to global config (closes #3169)
  src/components/toast/toast.js
  src/components/toast/toaster.js
  src/utils/config.js
Labels: Type: Enhancement

#3172 fix(form-input): properly handle out-of-sync values (closes #2657)
  src/mixins/form-text.js
Labels: Type: Fix

#3181 chore(docs): minor updates to `<b-table>` docs sort-compare section
  src/components/table/README.md
Labels: Type: Docs

#3175 feat: make more component appearance prop defaults globally configurable (closes #3173)
  src/components/alert/alert.js
  src/components/badge/badge.js
  src/components/button/button-close.js
  src/components/button/button.js
  src/components/card/card-sub-title.js
  src/components/carousel/carousel.js
  src/components/dropdown/dropdown.js
  src/components/form-file/form-file.js
  src/components/form/form-text.js
  src/components/image/img-lazy.js
  src/components/image/img.js
  src/components/jumbotron/jumbotron.js
  src/components/list-group/list-group-item.js
  src/components/modal/modal.js
  src/components/navbar/navbar-toggle.js
  src/components/navbar/navbar.js
  src/components/progress/progress-bar.js
  src/components/progress/progress.js
  src/components/spinner/spinner.js
  src/components/table/helpers/mixin-selectable.js
  src/components/table/helpers/mixin-tfoot.js
  src/components/table/helpers/mixin-thead.js
  src/components/toast/toaster.js
  src/utils/config.js
Labels: Type: Enhancement

#3186 fix(pagination): use unicode escape sequence for default bookend buttons (closes #3179)
  src/mixins/pagination.js
Labels: Type: Fix

#3200 chore: minor updates to navbar docs
  src/components/navbar/README.md
Labels: Type: Docs

#3195 chore: prefer `$scopedSlots` over `$slots` (closes #3193)
  src/components/alert/alert.js
  src/components/button-toolbar/button-toolbar.js
  src/components/button/button-close.js
  src/components/card/card.js
  src/components/carousel/carousel-slide.js
  src/components/carousel/carousel.js
  src/components/collapse/collapse.js
  src/components/dropdown/dropdown-item-button.js
  src/components/dropdown/dropdown-item.js
  src/components/dropdown/dropdown.js
  src/components/form-group/form-group.js
  src/components/form-select/form-select.js
  src/components/form/form-datalist.js
  src/components/input-group/input-group.js
  src/components/jumbotron/jumbotron.js
  src/components/media/media.js
  src/components/modal/modal.js
  src/components/nav/nav-item-dropdown.js
  src/components/navbar/navbar-toggle.js
  src/components/popover/popover.js
  src/components/progress/progress-bar.js
  src/components/progress/progress.js
  src/components/spinner/spinner.js
  src/components/table/helpers/mixin-thead.js
  src/components/tabs/tab.js
  src/components/tabs/tabs.js
  src/components/tooltip/tooltip.js
  src/mixins/form-radio-check-group.js
  src/mixins/form-radio-check.js
  src/mixins/normalize-slot.js
  src/utils/normalize-slot.js
Labels: Type: Enhancement

#3196 feat(dropdown): additional semantic markup optimizations for A11Y
  src/components/dropdown/README.md
  src/components/dropdown/dropdown-divider.js
  src/components/dropdown/dropdown-form.js
  src/components/dropdown/dropdown-group.js
  src/components/dropdown/dropdown-group.spec.js
  src/components/dropdown/dropdown-header.js
  src/components/dropdown/dropdown-header.spec.js
  src/components/dropdown/dropdown-item-button.js
  src/components/dropdown/dropdown-item.js
  src/components/dropdown/dropdown-text.js
  src/components/dropdown/index.js
  src/components/dropdown/package.json
Labels: Type: Accessibility, Type: Enhancement

#3203 test(collapse): testing use of show class check
  src/components/collapse/collapse.js
Labels: Status: WIP

#3199 fix(collapse): `is-nav` link click behaviour - check if collapse has `display: block !important` before attempting to close collapse
  docs/components/feedback.js
  docs/components/sidebar.vue
  docs/layouts/docs.js
  src/components/collapse/collapse.js
  src/components/collapse/collapse.spec.js
Labels: Type: Enhancement

#3207 fix(modal): return focus edge case bug in IE11 (fixes #3206)
  src/components/modal/modal.js
Labels: Type: Fix

#3202 chore: new logo and minor docs update
  README.md
  docs/pages/index.vue
  docs/pages/play.vue
  docs/static/icon.png
  static/banner.png
  static/logo-padded.png
  static/logo-padded.svg
  static/logo.png
  static/logo.svg
Labels: Type: Docs

#3208 chore(docs): landing page - add `<abbr>` tag and tooltip to WAI-ARIA
  docs/pages/index.vue
Labels: Type: Docs

#3214 feat(button): add prop `pill` for pill style buttons
  src/components/button/README.md
  src/components/button/button.js
  src/components/button/button.spec.js
Labels: Type: Enhancement
