Repository bootstrap-vue/bootstrap-vue, pull requests merged in 2019-02, with the labels that each got.

#2526 fix(pagination): set default total rows to 0 (fixes #2498)
  src/components/pagination/pagination.js
Labels: Type: Fix, Version: 2.x

#2529 fix(pagination): adjust aria label defaults. Fixes #2508
  src/components/pagination-nav/package.json
  src/components/pagination/package.json
  src/mixins/pagination.js
Labels: Type: Accessibility, Type: Fix, Version: 2.x

#2530 fix(tabs): Emit click on b-tab instance when button clicked. Fixes #2512
  src/components/tabs/package.json
  src/components/tabs/tabs.js
Labels: Type: Enhancement, Type: Fix, Version: 2.x

#2456 chore: Prettify and improve code markup
  docs/components/codemirror.vue
  docs/components/componentdoc.vue
  docs/components/footer.vue
  docs/components/importdoc.vue
  docs/components/jsfiddle.vue
  docs/components/nav.vue
  docs/components/search.vue
  docs/components/sidebar.vue
  docs/components/toc.vue
  docs/layouts/docs.vue
  docs/markdown/reference/router-links/README.md
  docs/markdown/reference/size-props/README.md
  docs/markdown/reference/starter-templates/README.md
  docs/markdown/reference/theming/README.md
  docs/markdown/reference/validation/README.md
  docs/pages/docs/index.vue
  docs/pages/index.vue
  docs/pages/play.vue
  src/components-extra/dropdown-select/dropdown-select.vue
  src/components/alert/README.md
  src/components/badge/README.md
  src/components/breadcrumb/README.md
  src/components/button-group/README.md
  src/components/button-toolbar/README.md
  src/components/button/README.md
  src/components/card/README.md
  src/components/carousel/README.md
  src/components/collapse/README.md
  src/components/dropdown/README.md
  src/components/embed/README.md
  src/components/form-checkbox/README.md
  src/components/form-file/README.md
  src/components/form-group/README.md
  src/components/form-input/README.md
  src/components/form-radio/README.md
  src/components/form-select/README.md
  src/components/form-textarea/README.md
  src/components/form/README.md
  src/components/image/README.md
  src/components/input-group/README.md
  src/components/jumbotron/README.md
  src/components/layout/README.md
  src/components/link/README.md
  src/components/list-group/README.md
  src/components/media/README.md
  src/components/modal/README.md
  src/components/nav/README.md
  src/components/navbar/README.md
  src/components/pagination-nav/README.md
  src/components/pagination/README.md
  src/components/popover/README.md
  src/components/progress/README.md
  src/components/spinner/README.md
  src/components/table/README.md
  src/components/tabs/README.md
  src/components/tooltip/README.md
  src/directives/popover/README.md
  src/directives/scrollspy/README.md
  src/directives/tooltip/README.md
Labels: Type: Docs, Type: Enhancement, Version: 2.x

#2535 feat(modal): add support for scrollable dialog content
  src/components/modal/README.md
  src/components/modal/modal.js
Labels: Type: Feature, Version: 2.x

#2536 feat(list-group): support horizontal layout
  src/components/list-group/README.md
  src/components/list-group/fixtures/list-group.html
  src/components/list-group/fixtures/list-group.js
  src/components/list-group/list-group.js
  src/components/list-group/list-group.spec.js
Labels: Type: Feature, Version: 2.x

#2540 perf(progress): use provide and inject for inter component communication
  src/components/progress/progress-bar.js
  src/components/progress/progress.js
Labels: Type: Enhancement, Version: 2.x

#2541 fix(pagination): Component name in `package.json`
  src/components/pagination/package.json
Labels: Type: Bug, Type: Docs

#2542 perf: only call vueUse in main index.js entrypoint
  src/components/alert/index.js
  src/components/badge/index.js
  src/components/breadcrumb/index.js
  src/components/button-group/index.js
  src/components/button-toolbar/index.js
  src/components/button/index.js
  src/components/card/index.js
  src/components/carousel/index.js
  src/components/collapse/index.js
  src/components/dropdown/index.js
  src/components/embed/index.js
  src/components/form-checkbox/index.js
  src/components/form-file/index.js
  src/components/form-group/index.js
  src/components/form-input/index.js
  src/components/form-radio/index.js
  src/components/form-select/index.js
  src/components/form-textarea/index.js
  src/components/form/index.js
  src/components/image/index.js
  src/components/input-group/index.js
  src/components/jumbotron/index.js
  src/components/layout/index.js
  src/components/link/index.js
  src/components/list-group/index.js
  src/components/media/index.js
  src/components/modal/index.js
  src/components/nav/index.js
  src/components/navbar/index.js
  src/components/pagination-nav/index.js
  src/components/pagination/index.js
  src/components/popover/index.js
  src/components/progress/index.js
  src/components/spinner/index.js
  src/components/table/index.js
  src/components/tabs/index.js
  src/components/tooltip/index.js
  src/directives/modal/index.js
  src/directives/popover/index.js
  src/directives/scrollspy/index.js
  src/directives/toggle/index.js
  src/directives/tooltip/index.js
Labels: Status: WIP, Type: Perf, Version: 2.x

#2544 fix(table): allow filtering on false values. Fixes #2485
  src/components/table/table.js
Labels: Status: WIP, Type: Fix, Version: 2.x

#2569 fix(deps): Add @babel/runtime to devDependencies
  package.json
  yarn.lock
Labels: Type: Fix, Version: 2.x

#2572 feat(table): don't show empty row slot if table busy and busy slot provided (Closes #2565)
  src/components/table/table.js
Labels: Type: Enhancement, Version: 2.x

#2589 docs(table): add additional info about primary-key prop (Closes #2580)
  src/components/table/README.md
Labels: Type: Docs, Version: 2.x

#2592 fix(docs): correct typos
  .github/ISSUE_TEMPLATE.md
  CONTRIBUTING.md
  docs/assets/css/styles.css
  docs/markdown/intro/README.md
  docs/markdown/reference/color-variants/README.md
  docs/markdown/reference/router-links/README.md
  docs/markdown/reference/size-props/README.md
  docs/markdown/reference/spacing-classes/README.md
  docs/markdown/reference/starter-templates/README.md
  docs/markdown/reference/theming/README.md
  docs/nuxt.config.js
  src/components/alert/README.md
  src/components/button-toolbar/README.md
  src/components/button/button.js
  src/components/card/README.md
  src/components/carousel/README.md
  src/components/collapse/README.md
  src/components/collapse/collapse.js
  src/components/dropdown/README.md
  src/components/form-checkbox/README.md
  src/components/form-file/README.md
  src/components/form-file/form-file.js
  src/components/form-group/README.md
  src/components/form-group/form-group.js
  src/components/form-input/README.md
  src/components/form-input/package.json
  src/components/form-radio/README.md
  src/components/form-select/README.md
  src/components/form-select/form-select.js
  src/components/form-textarea/README.md
  src/components/form-textarea/package.json
  src/components/image/README.md
  src/components/jumbotron/README.md
  src/components/layout/README.md
  src/components/link/README.md
  src/components/list-group/README.md
  src/components/modal/README.md
  src/components/navbar/README.md
  src/components/pagination-nav/README.md
  src/components/pagination-nav/pagination-nav.js
  src/components/pagination/README.md
  src/components/pagination/pagination.js
  src/components/popover/README.md
  src/components/progress/README.md
  src/components/spinner/README.md
  src/components/table/README.md
  src/components/tabs/README.md
  src/components/tabs/tabs.js
  src/directives/popover/README.md
  src/directives/scrollspy/README.md
  src/directives/tooltip/README.md
  src/mixins/dropdown.js
  src/utils/stable-sort.js
  src/utils/tooltip.class.js
Labels: Type: Docs, Version: 2.x

#2598 fix(docs): fix broken link in form-textarea docs
  src/components/form-textarea/README.md
Labels: Type: Docs

#2595 fix(build): fix docs generation and cleanup devDependencies
  babel.config.js
  package.json
  scripts/rollup.config.esm.js
  scripts/rollup.config.js
  yarn.lock
Labels: Type: Fix, Version: 2.x

#2608 fix(modal): better backdrop clickout handling (Closes: #2597)
  src/components/modal/modal.js
Labels: Type: Fix

#2611 feat(forms): add state prop to invalid and valid feedback + docs update
  src/components/form-checkbox/README.md
  src/components/form-group/form-group.js
  src/components/form-radio/README.md
  src/components/form/README.md
  src/components/form/form-invalid-feedback.js
  src/components/form/form-invalid-feedback.spec.js
  src/components/form/form-valid-feedback.js
  src/components/form/form-valid-feedback.spec.js
Labels: Type: Docs, Type: Enhancement

#2613 chore(playground): remove excess whitespace from playground log
  docs/pages/play.vue
Labels: Type: Docs, Type: Fix

#2618 fix(nuxt plugin): fix typo with bootstrap vue css import properties
  nuxt/index.js
Labels: Type: Fix

#2619 docs(table): add warning about circular references in items row data (Closes #2474)
  src/components/table/README.md
Labels: Type: Docs

#2617 docs(intro): Document alternative way to import plugins
  docs/components/importdoc.vue
  docs/markdown/intro/README.md
  src/index.js
Labels: Type: Docs

#2624 fix(utils/get): handle calse where passed object is null (Fixes #2623)
  src/utils/get.js
Labels: Status: On Hold, Type: Fix, Version: 2.x

#2639 docs(modal): correct issue in prevent closing example (Closes #2633)
  src/components/modal/README.md
Labels: Type: Docs, Type: Fix

#2607 fix: temporary fix for validation icon positioning (Closes #2599)
  src/components/form-input/_form-input.scss
Labels: Status: Upstream, Type: Temporary Fix

#2641 feat(table): add support for scoped empty slots
  src/components/table/README.md
  src/components/table/table.js
Labels: Type: Enhancement

#2640 fix(utils): Make `looseEqual()` util handle File's comparison correctly
  src/utils/loose-equal.js
  src/utils/loose-equal.spec.js
Labels: Type: Fix, Type: Perf

#2620 chore(release): Bump version number and update changelog
  CHANGELOG.md
  package.json
Labels: Status: WIP

#2647 feat(card-img-lazy): new card-img-lazy sub-component
  docs/markdown/reference/images/README.md
  src/components/card/README.md
  src/components/card/card-img-lazy.js
  src/components/card/card-img-lazy.spec.js
  src/components/card/index.js
  src/components/card/package.json
  src/utils/object.js
Labels: Status: WIP, Type: Feature

#2676 fix(table): fix class name for fixed table layout
  src/components/table/_table.scss
Labels: Type: Fix

#2689 fix(utils): add back array notation support to `get()` util
  src/utils/get.js
  src/utils/get.spec.js
  src/utils/loose-equal.js
  src/utils/object.js
Labels: Type: Enhancement, Type: Fix

#2688 feat(modal): add modal-backdrop slot
  src/components/modal/modal.js
  src/components/modal/package.json
Labels: Type: Enhancement

#2650 fix(docs): correct and validate component meta information (closes #2665)
  docs/components/componentdoc.vue
  docs/components/importdoc.vue
  docs/markdown/intro/meta.json
  docs/markdown/misc/changelog/meta.json
  docs/markdown/misc/contributing/meta.json
  docs/markdown/reference/color-variants/meta.json
  docs/markdown/reference/images/meta.json
  docs/markdown/reference/router-links/meta.json
  docs/markdown/reference/size-props/meta.json
  docs/markdown/reference/spacing-classes/meta.json
  docs/markdown/reference/starter-templates/meta.json
  docs/markdown/reference/utility-classes/meta.json
  docs/markdown/reference/validation/meta.json
  docs/pages/docs/components/_slug.vue
  package.json
  scripts/build.sh
  scripts/check-plugin-meta.js
  scripts/docs-publish.sh
  src/components/alert/package.json
  src/components/badge/package.json
  src/components/breadcrumb/package.json
  src/components/button-group/package.json
  src/components/button-toolbar/package.json
  src/components/button/package.json
  src/components/card/package.json
  src/components/carousel/package.json
  src/components/collapse/package.json
  src/components/dropdown/package.json
  src/components/embed/package.json
  src/components/form-checkbox/package.json
  src/components/form-file/package.json
  src/components/form-group/package.json
  src/components/form-input/package.json
  src/components/form-radio/package.json
  src/components/form-select/package.json
  src/components/form-textarea/package.json
  src/components/form/package.json
  src/components/input-group/package.json
  src/components/jumbotron/package.json
  src/components/layout/package.json
  src/components/link/package.json
  src/components/list-group/package.json
  src/components/media/package.json
  src/components/modal/package.json
  src/components/nav/package.json
  src/components/navbar/package.json
  src/components/pagination-nav/package.json
  src/components/pagination/package.json
  src/components/popover/package.json
  src/components/progress/package.json
  src/components/spinner/package.json
  src/components/table/package.json
  src/components/tabs/package.json
  src/components/tooltip/package.json
  src/directives/popover/package.json
  src/directives/scrollspy/package.json
  src/directives/tooltip/package.json
  yarn.lock
Labels: Type: Docs, Type: Enhancement, Type: Fix

#2681 fix(modal): modal stacking position fix (Closes #2677)
  src/components/modal/modal.js
Labels: Type: Fix

#2651 fix(utils): make `looseEqual()` util compliant with Vue.js spec
  src/utils/loose-equal.js
  src/utils/loose-equal.spec.js
Labels: Type: Enhancement, Type: Perf

#2694 feat(table): Add IDs to tbody > tr elements if primary-key provided (Closes #2693)
  src/components/table/README.md
  src/components/table/table-primarykey.spec.js
  src/components/table/table.js
Labels: Type: Feature

#2695 fix(form-file): fix v-model update watcher
  src/components/form-file/fixtures/form-file.html
  src/components/form-file/fixtures/form-file.js
  src/components/form-file/form-file.js
  src/components/form-file/form-file.spec.js
Labels: Type: Fix

#2666 feat(form-textarea): add `noAutoShrink` prop (closes #2664)
  src/components/form-textarea/README.md
  src/components/form-textarea/form-textarea.js
Labels: Type: Enhancement

#2701 fix(nuxt-module): fix default inclusion of CSS files (closes #2629)
  nuxt/index.js
Labels: Type: Fix

#2654 feat(nuxt-module): add tree-shaking support to Nuxt module
  docs/markdown/intro/README.md
  nuxt/index.js
  nuxt/plugin.template.js
Labels: Type: Enhancement, Type: Nuxt.js

#2698 feat(docs): add heading anchor links
  docs/assets/css/fonts.css
  docs/assets/scss/fonts.scss
  docs/assets/scss/styles.scss
  docs/nuxt.config.js
Labels: Type: Docs

#2661 fix(tabs): fix initial value handling (closes #2656)
  src/components/tabs/README.md
  src/components/tabs/fixtures/tabs.html
  src/components/tabs/fixtures/tabs.js
  src/components/tabs/tabs.js
  src/components/tabs/tabs.spec.js
Labels: Type: Fix, Type: Unit Testing

#2699 fix(pagination): correct pagination props/slots/event docs and fix ellipsis slot
  src/components/pagination-nav/README.md
  src/components/pagination/README.md
  src/mixins/pagination.js
Labels: Type: Docs

#2709 feat(modal): add toggle method and root event (Closes #2708)
  src/components/modal/README.md
  src/components/modal/modal.js
  src/components/modal/package.json
Labels: Type: Feature

#2710 docs(components): add in missing reference to root event listeners
  docs/components/componentdoc.vue
  docs/pages/docs/components/_slug.vue
  src/components/collapse/package.json
  src/components/modal/package.json
  src/components/popover/package.json
  src/components/table/package.json
  src/components/tooltip/package.json
Labels: Type: Docs

#2714 fix(dom-utils): check for `el.classList` existence (closes #2713)
  src/utils/dom.js
Labels: Type: Fix

#2653 feat(table): added `thead-top` slot to table (closes #2489)
  src/components/table/README.md
  src/components/table/package.json
  src/components/table/table.js
Labels: Type: Enhancement

#2721 feat(form-checkbox/radio): code improvements, test suites, and docs update (Closes #2718)
  src/components/form-checkbox/README.md
  src/components/form-checkbox/form-checkbox-group.js
  src/components/form-checkbox/form-checkbox-group.spec.js
  src/components/form-checkbox/form-checkbox.js
  src/components/form-checkbox/form-checkbox.spec.js
  src/components/form-radio/README.md
  src/components/form-radio/form-radio-group.js
  src/components/form-radio/form-radio-group.spec.js
  src/components/form-radio/form-radio.js
  src/components/form-radio/form-radio.spec.js
  src/mixins/form-radio-check-group.js
  src/mixins/form-radio-check.js
Labels: Type: Docs, Type: Enhancement, Type: Unit Testing

#2738 fix(form-input): allow number type for form-inputs (via form-text mixin)
  src/components/form-input/form-input.js
  src/components/form-input/form-input.spec.js
  src/mixins/form-text.js
Labels: Status: WIP, Type: Fix

#2733 feat(table): better default rendering of unformatted object values
  src/components/table/table.js
  src/utils/object.js
  src/utils/to-string.js
Labels: Type: Enhancement
