Repository bootstrap-vue/bootstrap-vue, pull requests merged in 2020-06, with the labels that each got.

#5450 chore(docs): Update all bootstrap doc links to latest version
  docs/markdown/intro/README.md
  docs/markdown/reference/accessibility/README.md
  docs/markdown/reference/starter-templates/README.md
  docs/markdown/reference/theming/README.md
  docs/markdown/reference/utility-classes/README.md
  src/components/form-group/README.md
  src/components/form/README.md
  src/components/layout/README.md
Labels: PR: Patch, Type: Docs

#5469 chore(b-avatar): convert line endings to Unix
  src/components/avatar/_avatar.scss
  src/components/avatar/index.scss
Labels: Type: Chore

#5474 chore: convert all line endings to Unix (closes #5472, #5473)
  docs/assets/vercel.svg
  src/components/aspect/README.md
  src/components/aspect/aspect.js
  src/components/aspect/aspect.spec.js
  src/components/aspect/index.d.ts
  src/components/aspect/index.js
  src/components/aspect/package.json
  src/components/avatar/README.md
  src/components/avatar/avatar.spec.js
  src/components/avatar/index.d.ts
  src/components/avatar/index.js
  src/components/avatar/package.json
  src/components/form-rating/README.md
  src/components/form-rating/_form-rating.scss
  src/components/form-rating/form-rating.js
  src/components/form-rating/form-rating.spec.js
  src/components/form-rating/index.d.ts
  src/components/form-rating/index.js
  src/components/form-rating/index.scss
  src/components/form-rating/package.json
  src/components/overlay/index.d.ts
  src/components/overlay/index.js
  src/components/overlay/overlay.js
  src/components/overlay/overlay.spec.js
  src/components/overlay/package.json
  src/components/sidebar/README.md
  src/components/sidebar/_sidebar.scss
  src/components/sidebar/index.d.ts
  src/components/sidebar/index.js
  src/components/sidebar/index.scss
  src/components/sidebar/package.json
  src/components/sidebar/sidebar.js
  src/components/sidebar/sidebar.spec.js
  src/directives/toggle/README.md
  src/directives/toggle/package.json
  static/logo-padded.svg
  static/logo.svg
Labels: Type: Chore

#5462 fix(b-carousel): transition when controls are inside slides (closes #5361)
  src/components/carousel/carousel.js
Labels: PR: Patch, Type: Fix

#5510 chore(docs): fix typo in sidebar README (fixes #5494)
  src/components/sidebar/README.md
Labels: Type: Docs

#5526 chore: update auto format config
  package.json
Labels: Type: Chore
