Repository bootstrap-vue/bootstrap-vue, pull requests merged in 2020-10, with the labels that each got.

#5845 fix(b-carousel): fix glitching when switching slides fast (closes #5810)
  src/components/carousel/carousel.js
Labels: PR: Patch, Type: Fix

#5846 chore(docs): fix sidebar documentation typo
  src/components/sidebar/README.md
Labels: Type: Docs

#5863 fix(b-sekelton): animation overflow issue for Safari (closes #5809)
  src/components/skeleton/_skeleton.scss
Labels: PR: Patch, Type: Fix, Type: SCSS

#5864 chore(docs): add example for `<b-toast>` with custom close button (closes #5837)
  src/components/toast/README.md
Labels: Type: Docs

#5862 chore(docs): simplify `<b-form-group>` validation message example (closes #5850)
  src/components/form-group/README.md
Labels: Type: Docs

#5872 fix(b-card): properly support header/footer with body image overlay (closes #5828)
  src/components/card/card.js
Labels: PR: Patch, Type: Fix

#5885 docs(b-navbar): specify support of sidebar + array
  src/components/navbar/README.md
  src/components/navbar/navbar-toggle.js
  src/components/navbar/package.json
Labels: PR: Patch, Type: Docs

#5876 fix(b-link): `href` handling inconsistencies to `<router-link>` (closes #5820)
  src/components/link/link.js
  src/components/pagination-nav/pagination-nav.js
  src/constants/regex.js
  src/utils/router.js
  src/utils/router.spec.js
Labels: PR: Patch, Type: Fix

#5882 fix(v-tooltip, v-popover): render data-* attributes on root components (closes #5836)
  src/components/form-datepicker/form-datepicker.spec.js
  src/components/popover/popover.spec.js
  src/components/tooltip/helpers/bv-popper.js
  src/components/tooltip/helpers/bv-tooltip-template.js
  src/components/tooltip/helpers/bv-tooltip.js
  src/components/tooltip/tooltip.js
Labels: PR: Patch, Type: Fix

#5889 chore(docs): capitalize all descriptions for table provide function props
  src/components/table/README.md
Labels: Type: Docs

#5892 chore(docs): fix `<b-form-datepicker>` locale typo
  src/components/form-datepicker/README.md
Labels: Type: Docs

#5895 chore(docs): use new slot syntax everywhere
  src/components/avatar/README.md
  src/components/card/README.md
  src/components/carousel/README.md
  src/components/dropdown/README.md
  src/components/form-checkbox/README.md
  src/components/form-radio/README.md
  src/components/form-select/README.md
  src/components/form-tags/README.md
  src/components/input-group/README.md
  src/components/jumbotron/README.md
  src/components/media/README.md
  src/components/modal/README.md
  src/components/navbar/README.md
  src/components/overlay/README.md
  src/components/pagination-nav/README.md
  src/components/pagination/README.md
  src/components/popover/README.md
  src/components/sidebar/README.md
  src/components/skeleton/README.md
  src/components/table/README.md
  src/components/tabs/README.md
  src/components/toast/README.md
  src/icons/README.md
Labels: PR: Patch, Type: Docs

#5894 chore: update `core-js` to v3
  .github/renovate.json
  babel.config.js
  package.json
  yarn.lock
Labels: PR: Patch, Type: Chore, Type: Dependencies

#5898 chore(docs): fix closing span tag
  src/components/avatar/README.md
Labels: Type: Docs

#5899 chore: update dependencies
  package.json
  yarn.lock
Labels: PR: Patch, Type: Dependencies

#5907 chore(deps): allow dependabot to check GitHub actions daily
  .github/dependabot.yml
Labels: CI, Type: Dependencies

#5883 feat(b-calendar): add `no-key-nav` property (closes #5861)
  src/components/calendar/calendar.js
  src/components/calendar/calendar.spec.js
  src/components/calendar/package.json
Labels: PR: Minor, Type: Feature

#5911 fix(b-calendar): month formatting for certain dates (closes #5818)
  src/components/calendar/calendar.js
Labels: PR: Patch, Type: Fix

#5923 chore(docs): correct Bootstrap SCSS imports (closes #5920)
  docs/markdown/intro/README.md
Labels: Type: Docs

#5924 chore: bump version to v2.18.0
  CHANGELOG.md
  package.json
Labels: Type: Chore

#5935 chore(docs): add example on how to alias Vue.js with Vue CLI
  docs/markdown/intro/README.md
Labels: Type: Docs

#5933 fix(b-form-group): content element ID handling (closes #5930)
  src/components/form-group/form-group.js
Labels: PR: Patch, Type: Fix

#5934 fix(b-link): `href` handling with live router (closes #5927)
  src/components/link/link.js
  src/components/pagination-nav/pagination-nav.js
  src/utils/router.js
  src/utils/router.spec.js
Labels: PR: Patch, Type: Fix

#5939 fix(b-icon): local component lookup (closes #5937)
  src/icons/icon.js
Labels: PR: Patch, Type: Fix

#5940 chore: bump version to v2.18.1
  CHANGELOG.md
  package.json
Labels: Type: Chore

#5941 chore: release v2.18.1
  CHANGELOG.md
  docs/markdown/intro/README.md
  package.json
  src/components/form-group/form-group.js
  src/components/link/link.js
  src/components/pagination-nav/pagination-nav.js
  src/icons/icon.js
  src/utils/router.js
  src/utils/router.spec.js
  yarn.lock
Labels: Type: Chore

#5951 chore(docs): fix missing ` in carousel documentation
  src/components/carousel/README.md
Labels: Type: Docs

#5963 fix(b-avatar): prevent avatar from being squished (fixes #5962)
  src/components/avatar/_avatar.scss
Labels: PR: Patch, Type: Fix

#5971 chore(docs): correct typo in theming section
  docs/markdown/reference/theming/README.md
Labels: Type: Docs

#5965 feat(b-media): improve aside right handling
  src/components/index.scss
  src/components/media/README.md
  src/components/media/_media.scss
  src/components/media/index.scss
  src/components/media/media-aside.js
  src/components/media/media-aside.spec.js
  src/components/media/media-body.js
  src/components/media/media-body.spec.js
  src/components/media/media.js
  src/components/media/media.spec.js
  src/components/media/package.json
Labels: PR: Minor, Type: Enhancement, Type: Fix

#5975 fix(b-avatar): badge `z-index` handling (closes #5964)
  src/components/avatar/README.md
  src/components/avatar/_avatar.scss
Labels: PR: Patch, Type: Fix

#5978 chore(docs): replace `<b-input>` with `<b-form-input>`
  src/components/form-input/README.md
  src/components/form/README.md
Labels: Type: Docs

#5984 chore: correct typo in `rollup.config.js`
  scripts/rollup.config.js
Labels: Type: Chore
