Repository bootstrap-vue/bootstrap-vue, pull requests merged in 2020-12, with the labels that each got.

#6113 fix: user supplied prop function detection (closes #6112)
  src/components/calendar/calendar.js
  src/components/calendar/calendar.spec.js
  src/components/form-file/form-file.js
  src/components/form-spinbutton/form-spinbutton.js
  src/components/form-tags/form-tags.js
  src/components/table/helpers/mixin-filtering.js
  src/mixins/form-text.js
Labels: PR: Patch, Type: Fix

#6115 chore: bump version to v2.20.1
  CHANGELOG.md
  package.json
Labels: Type: Chore

#6116 chore: release v2.20.1
  CHANGELOG.md
  package.json
  src/components/calendar/calendar.js
  src/components/calendar/calendar.spec.js
  src/components/form-file/form-file.js
  src/components/form-spinbutton/form-spinbutton.js
  src/components/form-tags/form-tags.js
  src/components/table/helpers/default-sort-compare.js
  src/components/table/helpers/mixin-filtering.js
  src/mixins/form-text.js
Labels: PR: Patch, Type: Chore

#6148 chore(docs): update `highlight.js` to v10
  .github/dependabot.yml
  docs/nuxt.config.js
  docs/utils/hljs.js
  package.json
  yarn.lock
Labels: Type: Dependencies, Type: Docs, Type: Security

#6153 fix(table): default sort compare logic for date strings (closes #6129)
  src/components/alert/alert.js
  src/components/avatar/avatar.js
  src/components/table/helpers/default-sort-compare.spec.js
  src/utils/inspect.js
  src/utils/inspect.spec.js
Labels: PR: Patch, Type: Fix

#6159 fix(b-form-datepicker): `valueAsDate` prop handling (closes #6138)
  src/components/form-datepicker/form-datepicker.js
Labels: PR: Patch, Type: Fix

#6154 fix(b-tabs): cleanup rendering logic
  src/components/tabs/tab.js
  src/components/tabs/tab.spec.js
  src/components/tabs/tabs.js
  src/components/tabs/tabs.spec.js
  src/constants/events.js
  src/constants/safe-types.js
  src/utils/dom.js
Labels: PR: Patch, Type: Enhancement

#6163 feat(b-form-tags): add `no-tags-remove` prop (closes #6162)
  src/components/form-tags/README.md
  src/components/form-tags/form-tag.js
  src/components/form-tags/form-tag.spec.js
  src/components/form-tags/form-tags.js
  src/components/form-tags/form-tags.spec.js
  src/components/form-tags/package.json
Labels: PR: Minor, Type: Feature request

#6179 feat(b-sidebar): add `header` slot (closes #6177)
  src/components/sidebar/README.md
  src/components/sidebar/package.json
  src/components/sidebar/sidebar.js
  src/components/sidebar/sidebar.spec.js
  src/mixins/normalize-slot.js
Labels: PR: Minor, Type: Enhancement, Type: Feature request

#6180 chore(icons): update Bootstrap Icons to v1.2.0
  .bundlewatch.config.json
  docs/content.js
  package.json
  src/icons/README.md
  src/icons/icons.d.ts
  src/icons/icons.js
  src/icons/package.json
  src/icons/plugin.js
  yarn.lock
Labels: Bootstrap Icons, PR: Minor, Type: Dependencies

#6181 chore(docs): correct typo in `<b-list-group>` documentation
  src/components/list-group/README.md
Labels: Type: Docs

#6178 feat(b-form-group): add `content-cols` props and scoped `default` slot (closes #6095, #6118)
  src/components/calendar/README.md
  src/components/form-checkbox/README.md
  src/components/form-datepicker/README.md
  src/components/form-group/README.md
  src/components/form-group/form-group.js
  src/components/form-group/form-group.spec.js
  src/components/form-group/package.json
  src/components/form-input/README.md
  src/components/form-radio/README.md
  src/components/form-tags/README.md
  src/components/form-textarea/README.md
  src/components/form-timepicker/README.md
  src/components/form/README.md
  src/components/modal/README.md
  src/components/overlay/README.md
  src/components/table/README.md
  src/components/time/README.md
  src/mixins/form-radio-check-group.js
  src/utils/array.js
Labels: PR: Minor, Type: Enhancement, Type: Feature request

#6186 fix(b-form-datepicker/b-form-timepicker): label styles when in `button-only` mode (closes #6172)
  src/components/form-btn-label-control/bv-form-btn-label-control.js
  src/components/form-datepicker/form-datepicker.js
  src/components/form-datepicker/form-datepicker.spec.js
  src/components/form-timepicker/form-timepicker.js
  src/components/form-timepicker/form-timepicker.spec.js
Labels: PR: Patch, Type: Fix

#6194 chore(icons): update Bootstrap Icons to v1.2.1
  package.json
  src/icons/icons.d.ts
  src/icons/icons.js
  src/icons/package.json
  src/icons/plugin.js
  yarn.lock
Labels: Bootstrap Icons, PR: Patch, Type: Dependencies

#6195 chore: bump version to v2.21.0
  CHANGELOG.md
  package.json
Labels: PR: Patch, Type: Chore

#6198 fix(b-dropdown): root events (closes #6197)
  src/components/modal/modal.js
  src/components/tooltip/helpers/bv-tooltip.js
  src/mixins/dropdown.js
Labels: PR: Patch, Type: Fix

#6200 fix(b-pagination): don't set initial page count twice (closes #6199)
  src/components/pagination/pagination.js
Labels: PR: Patch, Type: Fix

#6206 chore(docs): fix `<b-form-timepicker>` "Button only mode" example markup
  src/components/form-timepicker/README.md
Labels: PR: Patch, Type: Docs

#6217 fix(b-badge): attribute inheritance (closes #6209)
  src/components/badge/badge.js
Labels: PR: Patch, Type: Fix

#6208 fix(b-tabs): restore correct active tab detection logic (closes #6205)
  src/components/tabs/tabs.js
  src/components/tabs/tabs.spec.js
Labels: PR: Patch, Type: Fix

#6220 chore: bump version to v2.21.1
  CHANGELOG.md
  package.json
Labels: PR: Patch, Type: Chore

#6221 chore: release v2.21.1
  .github/workflows/build.yml
  .github/workflows/test.yml
  CHANGELOG.md
  package.json
  src/components/badge/badge.js
  src/components/form-timepicker/README.md
  src/components/modal/modal.js
  src/components/pagination/pagination.js
  src/components/tabs/tabs.js
  src/components/tabs/tabs.spec.js
  src/components/tooltip/helpers/bv-tooltip.js
  src/mixins/dropdown.js
  yarn.lock
Labels: PR: Patch, Type: Chore

#6226 fix: environment detection based on `userAgent` (closes #6225)
  src/constants/env.js
Labels: PR: Patch, Type: Fix

#6227 chore: add Nuxt.js CodeSandbox CI template
  .codesandbox/ci.json
Labels: PR: Patch, Type: CI, Type: Chore

#6222 chore(docs): improve Bootstrap/BootstrapVue style import guide in "Getting started" docs
  docs/markdown/intro/README.md
Labels: Type: Docs

#6231 chore(docs): fix typos in `<b-dropdown>` docs
  src/components/dropdown/README.md
Labels: Type: Docs

#6232 chore(docs): remove `label-for` from `<b-form-group>`'s with `<b-form-file>` component (closes #6229)
  src/components/form-file/README.md
Labels: Type: Docs

#6233 fix(b-icon): title render handling (closes #6223)
  src/icons/helpers/icon-base.js
Labels: Bootstrap Icons, PR: Patch, Type: Fix

#6234 fix(b-sidebar): make sure to not exceed 100% in height (closes #6176)
  src/components/sidebar/_sidebar.scss
Labels: PR: Patch, Type: Fix

#6244 chore(docs): fix typos in `<b-form-select>` and `<b-form-textarea>` docs
  src/components/form-select/package.json
  src/components/form-textarea/package.json
Labels: Type: Docs

#6249 fix(b-form-datepicker/b-form-timepicker): control size (closes #6246)
  src/components/form-btn-label-control/_form-btn-label-control.scss
  src/components/form-btn-label-control/bv-form-btn-label-control.js
Labels: PR: Patch, Type: Fix

#6251 fix(b-table): only set `aria-describedby` when caption really exists (closes #6250)
  src/components/table/helpers/mixin-caption.js
  src/components/table/helpers/mixin-table-renderer.js
Labels: PR: Patch, Type: Fix

#6252 chore(icons): update Bootstrap Icons to v1.2.2
  package.json
  src/icons/icons.d.ts
  src/icons/icons.js
  src/icons/package.json
  src/icons/plugin.js
  yarn.lock
Labels: Bootstrap Icons, PR: Patch, Type: Dependencies

#6263 chore(docs): correct typos and improve wording in theming section
  docs/markdown/reference/theming/README.md
Labels: Type: Docs

#6265 fix: clean up props inheritance
  src/components/collapse/helpers/bv-collapse.js
  src/components/dropdown/dropdown-item.js
  src/components/nav/nav-form.js
  src/components/nav/nav-item.js
  src/icons/helpers/make-icon.js
  src/icons/icon.js
  src/icons/iconstack.js
Labels: PR: Patch, Type: Fix

#6266 fix(b-table): allow `responsive` and `stacked` props together (closes #6261)
  src/components/table/README.md
  src/components/table/helpers/mixin-table-renderer.js
  src/components/table/table-lite.spec.js
  src/components/table/table.spec.js
Labels: PR: Patch, Type: Fix

#6274 fix(b-dropdown): only apply `heading` role to header when not a `header` tag (closes #6273)
  src/components/dropdown/dropdown-group.js
  src/components/dropdown/dropdown-header.js
Labels: PR: Patch, Type: Accessibility, Type: Fix

#6275 chore(deps): regenerate lockfile
  yarn.lock
Labels: Type: Chore, Type: Dependencies
