Repository bootstrap-vue/bootstrap-vue, pull requests merged in 2020-07, with the labels that each got.

#5554 fix(b-table): prevent endless reevaluation when using v-model and object/array literal prop values (fixes #5461)
  src/components/table/helpers/mixin-items.js
Labels: PR: Patch, Type: Fix

#5545 fix(b-img): Allow empty `alt` prop (fixes #5524)
  src/components/avatar/avatar.js
  src/components/avatar/avatar.spec.js
  src/components/card/card-img-lazy.spec.js
  src/components/card/card-img.js
  src/components/card/card-img.spec.js
  src/components/image/img.js
  src/components/image/img.spec.js
Labels: PR: Patch, Type: Fix

#5429 feat(b-form-tags): add `ignoreInputFocusSelector` prop to make input focus behavior configurable (closes #5425)
  src/components/form-tags/form-tags.js
  src/components/form-tags/package.json
Labels: PR: Minor, Type: Enhancement, Type: Feature

#5537 chore(docs): add an example to `<b-input-group>`'s using icons
  src/components/input-group/README.md
Labels: Type: Docs

#5544 fix(b-tags): replace spacing utility with static CSS (fixes #5523)
  src/components/form-tags/_form-tags.scss
  src/components/form-tags/form-tag.js
  src/components/form-tags/form-tags.js
Labels: PR: Patch, Type: Fix

#5579 chore(docs): improve icons page
  README.md
  docs/components/icons-table.vue
  docs/content/index.js
  docs/pages/docs/icons/index.js
  docs/pages/docs/index.js
  docs/pages/index.vue
  package.json
  src/icons/README.md
Labels: Type: Docs, Type: Enhancement

#5585 chore: regenerate `yarn.lock`
  yarn.lock
Labels: Type: Chore, Type: Security

#5586 fix(b-form-tags): unit test
  src/components/form-tags/form-tags.spec.js
Labels: Type: Fix, Type: Unit Testing

#5549 feat(docs): launch themes page with first BootstrapVue theme
  docs/components/footer.vue
  docs/components/header.vue
  docs/components/sidebar.vue
  docs/content.js
  docs/content/themes/argon-dashboard-pro.yaml
  docs/markdown/intro/README.md
  docs/markdown/reference/theming/README.md
  docs/nuxt.config.js
  docs/pages/index.vue
  docs/pages/themes.vue
  package.json
  yarn.lock
Labels: Type: Docs

#5564 fix: properly handle special characters in user-provided IDs (closes #4927, #5561)
  src/components/form-group/form-group.js
  src/components/form-group/form-group.spec.js
  src/components/form-tags/form-tags.js
  src/components/form-tags/form-tags.spec.js
  src/utils/css-escape.js
  src/utils/css-escape.spec.js
Labels: PR: Patch, Type: Fix

#5580 chore(ci): update `actions/cache` to v2
  .github/workflows/build.yml
  .github/workflows/test.yml
Labels: CI, Type: Chore

#5596 chore: replace `packagequality` badge with `codacy` in README
  README.md
Labels: Type: Chore

#5606 fix: remove redundant `height` declaration for `.b-sidebar` (fixes #5605)
  src/components/sidebar/_sidebar.scss
Labels: PR: Patch, Type: Fix, Type: SCSS

#5612 chore: add script to generate release notes
  .gitignore
  package.json
  scripts/release-notes.js
  yarn.lock
Labels: Type: Chore

#5620 chore: update `yarn.lock`
  yarn.lock
Labels: Type: Chore, Type: Dependencies, Type: Security

#5619 feat(docs): add free version of bootstrap-vue-argon-dashboard-pro
  docs/content/themes/argon-dashboard.yaml
Labels: Themes, Type: Docs
