Repository bootstrap-vue/bootstrap-vue, pull requests merged in 2020-05, with the labels that each got.

#5290 chore(docs): improve page load time by pre-parsing README.md at build time
  docs/components/carbon-ad.js
  docs/components/header.vue
  docs/components/main-docs.js
  docs/components/reload.js
  docs/components/sidebar.vue
  docs/nuxt.config.js
  docs/pages/docs/components/_slug.js
  docs/pages/docs/directives/_slug.js
  docs/pages/docs/icons/index.js
  docs/pages/docs/index.js
  docs/pages/docs/reference/_slug.js
  docs/plugins/docs-mixin.js
  docs/utils/docs-loader.js
  docs/utils/index.js
  src/_custom-controls.scss
  src/components/aspect/README.md
  src/components/avatar/README.md
  src/components/form-rating/README.md
  src/components/tooltip/README.md
  src/directives/tooltip/README.md
  src/icons/README.md
Labels: PR: Patch, Type: Docs, Type: Perf

#5305 chore: bump version and update changelog
  CHANGELOG.md
  package.json
Labels: PR: Patch

#5281 release: 2.13.1
  CHANGELOG.md
  README.md
  docs/assets/vercel.svg
  docs/components/carbon-ad.js
  docs/components/contributors.vue
  docs/components/header.vue
  docs/components/main-docs.js
  docs/components/reload.js
  docs/components/sidebar.vue
  docs/nuxt.config.js
  docs/pages/docs/components/_slug.js
  docs/pages/docs/directives/_slug.js
  docs/pages/docs/icons/index.js
  docs/pages/docs/index.js
  docs/pages/docs/reference/_slug.js
  docs/pages/index.vue
  docs/pages/themes.vue
  docs/plugins/docs-mixin.js
  docs/utils/docs-loader.js
  docs/utils/index.js
  package.json
  src/_custom-controls.scss
  src/components/aspect/README.md
  src/components/avatar/README.md
  src/components/calendar/calendar.js
  src/components/card/card-img-lazy.spec.js
  src/components/card/card-img.spec.js
  src/components/form-datepicker/README.md
  src/components/form-rating/README.md
  src/components/form-rating/form-rating.spec.js
  src/components/form-spinbutton/README.md
  src/components/form-timepicker/README.md
  src/components/form-timepicker/form-timepicker.js
  src/components/modal/modal.spec.js
  src/components/popover/README.md
  src/components/sidebar/README.md
  src/components/table/README.md
  src/components/table/_table.scss
  src/components/table/helpers/mixin-thead.js
  src/components/table/table-filtering.spec.js
  src/components/table/table-sorting.spec.js
  src/components/table/tbody.js
  src/components/table/td.js
  src/components/table/tfoot.js
  src/components/table/th.js
  src/components/table/thead.js
  src/components/table/tr.js
  src/components/time/README.md
  src/components/toast/README.md
  src/components/tooltip/README.md
  src/components/tooltip/helpers/bv-tooltip.js
  src/directives/tooltip/README.md
  src/icons/README.md
  src/mixins/dropdown.js
  src/mixins/form-text.js
  src/mixins/has-listener.js
  src/utils/bv-collapse.js
  src/utils/config-defaults.js
  src/utils/observe-dom.js
  yarn.lock
Labels: PR: Patch

#5306 chore: add dedicated documentation for `v-b-toggle` directive and additional popover/tooltip docs updates (closes #5262)
  docs/nuxt.config.js
  src/components/collapse/README.md
  src/components/collapse/index.js
  src/components/collapse/package.json
  src/components/popover/README.md
  src/components/tooltip/README.md
  src/directives/toggle/README.md
  src/directives/toggle/package.json
Labels: PR: Patch, Type: Docs

#5307 chore: show example of `b-table` provider `async/await` (closes #4849)
  src/components/table/README.md
Labels: PR: Patch, Type: Docs

#5272 feat(b-avatar-group): new helper component b-avatar-group
  src/components/avatar/README.md
  src/components/avatar/_avatar.scss
  src/components/avatar/avatar-group.js
  src/components/avatar/avatar-group.spec.js
  src/components/avatar/avatar.js
  src/components/avatar/avatar.spec.js
  src/components/avatar/index.d.ts
  src/components/avatar/index.js
  src/components/avatar/package.json
  src/index.js
Labels: PR: Minor, Type: Custom Component, Type: Feature

#5327 chore: ignore test utils/stub components for coverage
  tests/components/TransitionGroupStub.js
  tests/components/TransitionStub.js
Labels: CI, PR: Patch

#5333 chore(docs): update grid layout docs (closes #5332)
  src/components/layout/README.md
  src/components/layout/package.json
Labels: PR: Patch, Type: Docs

#5341 chore(docs): fix broken link
  src/components/input-group/README.md
Labels: Type: Docs

#5336 feat(v-b-toggle): support specifying target ID via directive argument, and array of target IDs via directive value (closes #4834)
  src/components/collapse/README.md
  src/components/modal/package.json
  src/components/navbar/README.md
  src/components/navbar/navbar-toggle.js
  src/components/navbar/navbar-toggle.spec.js
  src/components/sidebar/README.md
  src/directives/toggle/README.md
  src/directives/toggle/package.json
  src/directives/toggle/toggle.js
  src/directives/toggle/toggle.spec.js
  src/utils/target.js
Labels: PR: Minor, Status: WIP, Type: Accessibility, Type: Enhancement, Type: Feature, Type: Refactor

#4825 fix(perf): avoid useless re-renders of component on parent update
  src/components/calendar/calendar.js
  src/components/dropdown/dropdown-item-button.js
  src/components/dropdown/dropdown-item.js
  src/components/form-file/form-file.js
  src/components/form-input/form-input.js
  src/components/form-spinbutton/form-spinbutton.js
  src/components/form-textarea/form-textarea.js
  src/components/link/link.js
  src/components/modal/helpers/bv-modal.js
  src/components/modal/modal.js
  src/components/sidebar/sidebar.js
  src/components/table/helpers/mixin-table-renderer.js
  src/components/table/table.js
  src/components/table/tbody.js
  src/components/table/td.js
  src/components/table/tfoot.js
  src/components/table/thead.js
  src/components/table/tr.js
  src/components/toast/helpers/bv-toast.js
  src/components/toast/toast.js
  src/directives/scrollspy/scrollspy.class.js
  src/mixins/attrs.js
  src/mixins/attrs.spec.js
  src/mixins/form-radio-check.js
  src/mixins/listeners.js
  src/mixins/listeners.spec.js
  src/utils/cache.js
Labels: PR: Patch, Type: Enhancement, Type: Perf

#5346 chore(utils/dom): add new utils for focus/blur handling
  src/components/button-toolbar/button-toolbar.js
  src/components/calendar/calendar.js
  src/components/carousel/carousel.js
  src/components/form-datepicker/form-datepicker.js
  src/components/form-group/form-group.js
  src/components/form-input/form-input.js
  src/components/form-rating/form-rating.js
  src/components/form-select/form-select.js
  src/components/form-spinbutton/form-spinbutton.js
  src/components/form-tags/form-tags.js
  src/components/form-timepicker/form-timepicker.js
  src/components/link/link.js
  src/components/modal/modal.js
  src/components/pagination-nav/pagination-nav.js
  src/components/pagination/pagination.js
  src/components/sidebar/sidebar.js
  src/components/table/helpers/mixin-tbody.js
  src/components/tabs/tabs.js
  src/components/time/time.js
  src/components/tooltip/helpers/bv-tooltip.js
  src/mixins/dropdown.js
  src/mixins/form-radio-check.js
  src/mixins/form-text.js
  src/mixins/form.js
  src/mixins/pagination.js
  src/utils/bv-form-btn-label-control.js
  src/utils/dom.js
Labels: PR: Patch, Type: Refactor

#5344 feat(b-nav-item-dropdown): improve default handling of dropdown toggle link (closes #3942)
  src/components/nav/README.md
  src/components/nav/nav-item-dropdown.js
  src/components/nav/nav-item-dropdown.spec.js
  src/mixins/id.js
Labels: PR: Minor, Type: Accessibility, Type: Enhancement

#5348 chore(docs): update sitemap module config
  docs/nuxt.config.js
Labels: PR: Patch, Type: Docs

#5345 fix(b-modal): remove `role="document"` from `.modal-content`
  src/components/modal/modal.js
  src/components/modal/modal.spec.js
Labels: PR: Patch, Type: Accessibility, Type: Enhancement

#5353 chore(docs): fix collapse accordion example to not use `href="#"` on buttons (closes #5352)
  src/components/collapse/README.md
  src/directives/toggle/README.md
Labels: PR: Patch, Type: Docs

#5355 feat: support `<nuxt-link>`'s `prefetch` property (closes #5125)
  docs/common-props.json
  docs/markdown/reference/router-links/README.md
  src/components/avatar/avatar.js
  src/components/link/link.js
  src/components/pagination-nav/README.md
  src/components/pagination-nav/pagination-nav.js
Labels: PR: Minor, Type: Enhancement, Type: Feature

#5357 fix(b-link): default new `<nuxt-link>` prop `prefetch` to `null` for true tri-state prop
  docs/common-props.json
  docs/markdown/reference/router-links/README.md
  src/components/badge/badge.js
  src/components/breadcrumb/breadcrumb-link.js
  src/components/button/button.js
  src/components/dropdown/dropdown-item.js
  src/components/link/link.js
  src/components/list-group/list-group-item.js
  src/components/nav/nav-item.js
  src/components/navbar/navbar-brand.js
Labels: PR: Patch, Type: Fix

#5356 chore: tests cleanup
  src/components/alert/alert.spec.js
  src/components/avatar/avatar.spec.js
  src/components/button-toolbar/button-toolbar.spec.js
  src/components/carousel/carousel-slide.spec.js
  src/components/carousel/carousel.spec.js
  src/components/collapse/collapse.spec.js
  src/components/dropdown/dropdown-item.spec.js
  src/components/dropdown/dropdown.spec.js
  src/components/form-checkbox/form-checkbox-group.spec.js
  src/components/form-radio/form-radio-group.spec.js
  src/components/link/link.spec.js
  src/components/modal/helpers/bv-modal.spec.js
  src/components/modal/modal.spec.js
  src/components/overlay/overlay.spec.js
  src/components/pagination-nav/pagination-nav.spec.js
  src/components/popover/popover.spec.js
  src/components/sidebar/sidebar.spec.js
  src/components/table/table-tbody-transition.spec.js
  src/components/tabs/tab.spec.js
  src/components/tabs/tabs.spec.js
  src/components/toast/helpers/bv-toast.spec.js
  src/components/toast/toast.spec.js
  src/components/toast/toaster.spec.js
  src/components/tooltip/tooltip.spec.js
  src/directives/hover/hover.spec.js
  src/directives/modal/modal.spec.js
  src/directives/popover/popover.spec.js
  src/directives/toggle/toggle.spec.js
  src/directives/tooltip/tooltip.spec.js
  src/icons/icons.spec.js
  src/mixins/click-out.spec.js
  src/mixins/focus-in.spec.js
  src/mixins/listen-on-document.spec.js
  src/mixins/listen-on-root.spec.js
  src/mixins/listen-on-window.spec.js
  src/utils/config.spec.js
  src/utils/dom.spec.js
  src/utils/transporter.spec.js
  tests/setup.js
Labels: Type: Refactor, Type: Unit Testing

#5362 fix: ensure all intervals/timeouts/observers are cleared when component is destroyed
  src/components/carousel/carousel.js
  src/components/form-spinbutton/form-spinbutton.js
  src/components/modal/modal.js
  src/components/table/helpers/mixin-filtering.js
  src/components/table/helpers/mixin-tbody.js
  src/components/tabs/tabs.js
  src/components/tooltip/helpers/bv-popper.js
  src/components/tooltip/helpers/bv-tooltip.js
  src/components/tooltip/tooltip.js
  src/directives/scrollspy/scrollspy.class.js
  src/directives/visible/visible.js
  src/mixins/dropdown.js
  src/mixins/form-text.js
  src/utils/transporter.js
Labels: PR: Patch, Type: Fix

#5374 feat(types): create declarations for `<b-calendar>` and `<b-time>` context event objects (closes #5366)
  src/components/calendar/index.d.ts
  src/components/time/index.d.ts
Labels: Type: Enhancement, Type: Types

#5358 feat(b-link): add support 3rd party router links such as Gridsome's `<g-link>` (closes #2627)
  docs/common-props.json
  docs/markdown/reference/router-links/README.md
  src/components/avatar/avatar.js
  src/components/badge/badge.js
  src/components/breadcrumb/breadcrumb-link.js
  src/components/button/button.js
  src/components/dropdown/dropdown-item.js
  src/components/dropdown/package.json
  src/components/link/README.md
  src/components/link/link.js
  src/components/link/link.spec.js
  src/components/link/package.json
  src/components/list-group/list-group-item.js
  src/components/nav/nav-item.js
  src/components/navbar/navbar-brand.js
  src/components/navbar/navbar.js
  src/components/pagination-nav/pagination-nav.js
  src/components/table/td.js
  src/components/toast/toast.js
  src/utils/config-defaults.js
  src/utils/dom.js
  src/utils/router.js
Labels: PR: Minor, Type: Enhancement, Type: Feature

#5365 fix: properly handle HTML props render order (closes #5363)
  .github/workflows/test.yml
  src/components/avatar/avatar.js
  src/components/badge/badge.js
  src/components/breadcrumb/breadcrumb-link.js
  src/components/button/button.js
  src/components/card/card-body.js
  src/components/card/card-footer.js
  src/components/card/card-header.js
  src/components/card/card.js
  src/components/carousel/carousel-slide.js
  src/components/dropdown/dropdown.js
  src/components/dropdown/dropdown.spec.js
  src/components/form-select/form-select-option-group.js
  src/components/form-select/form-select.js
  src/components/form/form-datalist.js
  src/components/input-group/input-group.js
  src/components/jumbotron/jumbotron.js
  src/components/jumbotron/jumbotron.spec.js
  src/components/layout/col.js
  src/components/layout/row.js
  src/components/link/link.js
  src/components/list-group/list-group-item.js
  src/components/modal/modal.js
  src/components/modal/modal.spec.js
  src/components/nav/nav-item-dropdown.js
  src/components/navbar/navbar-brand.js
  src/components/navbar/navbar-nav.js
  src/components/pagination-nav/pagination-nav.js
  src/components/progress/progress-bar.js
  src/components/table/helpers/mixin-caption.js
  src/components/table/helpers/mixin-empty.js
  src/components/table/helpers/mixin-thead.js
  src/components/toast/toast.js
  src/mixins/form-radio-check-group.js
  src/utils/copy-props.js
  src/utils/html.js
  src/utils/pluck-props.js
  src/utils/prefix-prop-name.js
  src/utils/props.js
  src/utils/props.spec.js
  src/utils/suffix-prop-name.js
  src/utils/unprefix-prop-name.js
Labels: PR: Patch, Type: Fix

#5381 chore: fix CodeSandbox export from playground and CI template
  .codesandbox/ci.json
  docs/pages/play.vue
Labels: CI, PR: Patch, Type: Docs, Type: Fix

#5396 fi(v-b-toggle): don't check for `evt.defaultPrevened` (closes #5391)
  src/directives/toggle/README.md
  src/directives/toggle/toggle.js
Labels: PR: Patch, Type: Fix

#5397 feat(b-navbar-toggle): add `disabled` prop
  src/components/navbar/navbar-toggle.js
  src/components/navbar/navbar-toggle.spec.js
  src/components/navbar/package.json
Labels: PR: Minor, Type: Feature

#5398 feat(v-b-toggle): check for target ID via `href` if a link
  src/directives/toggle/README.md
  src/directives/toggle/toggle.js
  src/directives/toggle/toggle.spec.js
Labels: PR: Minor, Type: Enhancement

#5395 feat: update Bootstrap to v4.5
  package.json
  yarn.lock
Labels: Bootstrap v4, PR: Minor, Type: Dependencies

#5402 chore(docs): updated VeeValidate v3 documentation url
  docs/markdown/reference/validation/README.md
Labels: Type: Docs

#5411 feat(b-sidebar): add prop `backdrop-variant`
  src/components/sidebar/README.md
  src/components/sidebar/_sidebar.scss
  src/components/sidebar/package.json
  src/components/sidebar/sidebar.js
  src/components/sidebar/sidebar.spec.js
  src/utils/config-defaults.js
Labels: PR: Minor, Type: Enhancement

#5419 chore: bump bundlewatch thresholds due to new icons
  .bundlewatch.config.json
Labels: PR: Patch

#5422 chore(docs): remove any old Carbonads scripts from `<head>`
  docs/components/carbon-ad.js
Labels: PR: Patch, Type: Docs

#5420 feat(icons): upgrade to Bootstrap Icons 1.0.0-alpha4
  README.md
  docs/pages/index.vue
  src/icons/README.md
  src/icons/icons.d.ts
  src/icons/icons.js
  src/icons/package.json
  src/icons/plugin.js
Labels: PR: Minor, Type: Feature

#5432 fix(b-form-checkbox-group): only emit `input` when value loosely changes
  src/components/form-checkbox/form-checkbox-group.spec.js
  src/mixins/form-radio-check-group.js
  src/utils/loose-equal.js
Labels: PR: Patch, Type: Fix

#5447 chore(docs): Change Bootstrap v4.3.x to 4.5.x in README
  README.md
Labels: Type: Chore
