Repository bootstrap-vue/bootstrap-vue, pull requests merged in 2020-11, with the labels that each got.

#5995 chore(docs): add gull & dexam themes
  docs/content/themes/dexam-startup-and-product-landing-page.yaml
  docs/content/themes/gull-admin-dashboard.yaml
Labels: Themes, Type: Docs

#6001 chore(ci): update Node.js versions
  .github/workflows/build.yml
  .github/workflows/test.yml
Labels: CI

#6002 chore: add `SECURITY.md`
  SECURITY.md
Labels: Type: Chore

#6003 chore(ci): add CodeQL action
  .github/workflows/codeql.yml
Labels: Type: CI

#6004 chore(ci): move to Dependabot for all dependency updates
  .github/dependabot.yml
  .github/renovate.json
Labels: Type: CI, Type: Dependencies

#6014 chore(docs): improve component name formatting
  docs/components/componentdoc.vue
  docs/components/importdoc.vue
  docs/utils/index.js
Labels: Type: Docs

#6008 fix(b-form-checkbox/b-form-radio): `change` event timing (closes #6005)
  src/components/form-checkbox/form-checkbox.js
  src/components/form-radio/form-radio.js
Labels: PR: Patch, Type: Fix

#6006 fix(b-form-group): accessibility when `label-for` prop not set (closes #5918)
  src/components/form-group/form-group.js
  src/components/form-group/form-group.spec.js
Labels: PR: Patch, Type: Accessibility, Type: Fix

#6015 chore: unify interval/timeout handling
  docs/plugins/docs-mixin.js
  src/components/alert/alert.js
  src/components/toast/toast.js
  src/components/toast/toast.spec.js
Labels: Type: Chore

#6009 fix(b-dropdown): click handling on close (closes #5982)
  src/mixins/dropdown.js
Labels: PR: Patch, Type: Fix

#6019 chore(docs): add another `pageOptions` setting example
  src/components/table/README.md
Labels: Type: Docs

#6025 chore: bump version to v2.19.0
  CHANGELOG.md
  package.json
Labels: Type: Chore

#6040 chore(docs): fix gull & dexam preview image link
  docs/content/themes/dexam-startup-and-product-landing-page.yaml
  docs/content/themes/gull-admin-dashboard.yaml
Labels: Type: Docs, Type: Themes

#6043 chore(docs): update "Can I use" links
  docs/markdown/reference/router-links/README.md
  src/components/avatar/_avatar.scss
  src/components/form-file/README.md
  src/components/form-input/README.md
  src/components/form-textarea/README.md
  src/components/table/README.md
Labels: Type: Docs

#6077 chore(deps): remove deprecated `eslint-plugin-standard`
  package.json
  yarn.lock
Labels: Type: Dependencies

#6084 fix(b-form-input/b-form-textarea): v-model handling (closes #6078)
  src/mixins/form-text.js
Labels: PR: Patch, Type: Fix

#6070 fix: user supplied prop function detection (closes #6069)
  src/components/calendar/calendar.js
  src/components/form-file/form-file.js
  src/components/form-spinbutton/form-spinbutton.js
  src/components/form-tags/form-tags.js
  src/components/table/helpers/mixin-filtering.js
  src/mixins/form-text.js
Labels: PR: Patch, Type: Fix

#6091 chore(deps): regenerate lockfile
  yarn.lock
Labels: Type: Dependencies

#6102 fix(b-table): only set `tabindex="0"` for sortable fields (closes #6097)
  src/components/table/helpers/mixin-thead.js
  src/components/table/table-sorting.spec.js
Labels: PR: Patch, Type: Fix

#6101 fix(b-form-spinbutton): button markup (closes #6099)
  src/components/form-spinbutton/form-spinbutton.js
Labels: PR: Patch, Type: Fix

#6100 chore(refactor): improved code sharing between form components
  src/components/form-checkbox/form-checkbox-group.js
  src/components/form-checkbox/form-checkbox-group.spec.js
  src/components/form-group/form-group.js
  src/components/form-radio/form-radio-group.js
  src/components/form-radio/form-radio-group.spec.js
  src/components/form-select/form-select.js
  src/mixins/form-radio-check-group.js
  src/mixins/form-state.js
  src/mixins/form-text.js
Labels: PR: Patch, Type: Chore, Type: Refactor

#6103 fix(b-form-tags): required handling (closes #6094)
  src/components/form-tags/form-tags.js
  src/components/form-tags/form-tags.spec.js
Labels: PR: Patch, Type: Fix

#6104 feat(b-form-tags): add `reset` method
  src/components/form-tags/README.md
  src/components/form-tags/form-tags.js
  src/components/form-tags/form-tags.spec.js
  src/components/form-tags/index.d.ts
  src/components/form-tags/package.json
Labels: PR: Minor, Type: Enhancement, Type: Feature

#6105 fix(b-table): sort handling for numeric string values (closes #6092)
  src/components/table/helpers/default-sort-compare.js
  src/components/table/helpers/default-sort-compare.spec.js
  src/components/table/helpers/mixin-sorting.js
  src/components/table/helpers/stringify-record-values.js
  src/components/table/table-sorting.spec.js
  src/utils/stringify-object-values.js
  src/utils/stringify-object-values.spec.js
Labels: PR: Patch, Type: Fix

#6110 chore: bump version to v2.20.0
  CHANGELOG.md
  package.json
Labels: Type: Chore

#6111 chore: release v2.20.0
  CHANGELOG.md
  docs/content/themes/dexam-startup-and-product-landing-page.yaml
  docs/content/themes/gull-admin-dashboard.yaml
  docs/markdown/intro/README.md
  docs/markdown/reference/router-links/README.md
  package.json
  src/components/avatar/_avatar.scss
  src/components/calendar/calendar.js
  src/components/form-checkbox/form-checkbox-group.js
  src/components/form-checkbox/form-checkbox-group.spec.js
  src/components/form-file/README.md
  src/components/form-file/form-file.js
  src/components/form-group/form-group.js
  src/components/form-input/README.md
  src/components/form-radio/form-radio-group.js
  src/components/form-radio/form-radio-group.spec.js
  src/components/form-select/form-select.js
  src/components/form-spinbutton/form-spinbutton.js
  src/components/form-tags/README.md
  src/components/form-tags/form-tags.js
  src/components/form-tags/form-tags.spec.js
  src/components/form-tags/index.d.ts
  src/components/form-tags/package.json
  src/components/form-textarea/README.md
  src/components/table/README.md
  src/components/table/helpers/default-sort-compare.js
  src/components/table/helpers/default-sort-compare.spec.js
  src/components/table/helpers/mixin-filtering.js
  src/components/table/helpers/mixin-sorting.js
  src/components/table/helpers/mixin-thead.js
  src/components/table/helpers/stringify-record-values.js
  src/components/table/table-sorting.spec.js
  src/mixins/form-radio-check-group.js
  src/mixins/form-state.js
  src/mixins/form-text.js
  src/utils/stringify-object-values.js
  src/utils/stringify-object-values.spec.js
  yarn.lock
Labels: Type: Chore
