Repository bootstrap-vue/bootstrap-vue, pull requests merged in 2020-08, with the labels that each got.

#5632 fix(b-form-input): fix debounce when value does not change
  src/components/form-input/form-input.spec.js
  src/mixins/form-text.js
Labels: PR: Patch, Type: Fix

#5636 chore(docs): fix typo in card docs
  src/components/card/README.md
Labels: Type: Docs

#5646 chore: correct typo in layout code comment
  src/components/layout/index.d.ts
Labels: Type: Chore

#5651 chore: update dependencies
  package.json
  yarn.lock
Labels: Bootstrap v4, Type: Dependencies, Type: Security

#5670 feat(b-dropdown-text) adds `text-class` prop (closes #5669)
  src/components/dropdown/dropdown-item.js
  src/components/dropdown/dropdown-text.js
  src/components/dropdown/dropdown-text.spec.js
  src/components/dropdown/package.json
Labels: PR: Minor, Type: Enhancement

#5674 fix(b-table): make sure to apply all formatters of field configuration (closes #5672)
  .bundlewatch.config.json
  src/components/table/helpers/sanitize-row.js
  src/components/table/table-filtering.spec.js
Labels: PR: Patch, Type: Fix

#5675 fix(b-avatar): image fit and scale (closes #5610, #5655)
  src/components/avatar/_avatar.scss
Labels: PR: Patch, Type: Fix, Type: SCSS

#5575 feat(b-skeleton): add skeleton components (closes #5413)
  docs/assets/scss/styles.scss
  src/_variables.scss
  src/components/aspect/package.json
  src/components/avatar/package.json
  src/components/form-rating/package.json
  src/components/index.d.ts
  src/components/index.js
  src/components/index.scss
  src/components/sidebar/README.md
  src/components/sidebar/package.json
  src/components/skeleton/README.md
  src/components/skeleton/_skeleton.scss
  src/components/skeleton/index.d.ts
  src/components/skeleton/index.js
  src/components/skeleton/index.scss
  src/components/skeleton/package.json
  src/components/skeleton/skeleton-icon.js
  src/components/skeleton/skeleton-icon.spec.js
  src/components/skeleton/skeleton-img.js
  src/components/skeleton/skeleton-img.spec.js
  src/components/skeleton/skeleton-table.js
  src/components/skeleton/skeleton-table.spec.js
  src/components/skeleton/skeleton-wrapper.js
  src/components/skeleton/skeleton-wrapper.spec.js
  src/components/skeleton/skeleton.js
  src/components/skeleton/skeleton.spec.js
  src/index.js
  src/utils/array.js
  src/utils/config-defaults.js
Labels: PR: Minor, Type: Custom Component, Type: Feature

#5683 chore(docs): fix a small typo in `b-table` docs
  src/components/table/README.md
Labels: Type: Docs

#5685 fix(b-form-file): drop handling for huge amounts of files (closes #5615)
  package.json
  scripts/create-web-types.js
  src/components/form-file/form-file.js
  yarn.lock
Labels: PR: Patch, Type: Fix

#5690 fix(v-b-toggle): handle component updates on click listeners (closes #5475)
  src/components/navbar/navbar-toggle.spec.js
  src/directives/toggle/toggle.js
  src/directives/toggle/toggle.spec.js
Labels: PR: Patch, Type: Fix
