Repository bootstrap-vue/bootstrap-vue, pull requests merged in 2020-02, with the labels that each got.

#4678 chore: release v2.4.0
  CHANGELOG.md
  package.json
  src/components/dropdown/README.md
  src/components/dropdown/dropdown-item-button.js
  src/components/dropdown/dropdown-item.js
  src/components/dropdown/dropdown.js
  src/components/form-input/README.md
  src/components/form-textarea/README.md
  src/components/modal/README.md
  src/components/modal/modal.js
  src/components/modal/modal.spec.js
  src/components/modal/package.json
  src/components/nav/nav-item-dropdown.js
  src/components/nav/package.json
  src/components/navbar/navbar.js
  src/components/navbar/navbar.spec.js
  src/components/table/README.md
  src/icons/README.md
  src/mixins/click-out.js
  src/mixins/dropdown.js
  src/mixins/form-text.js
  yarn.lock
Labels: PR: Minor

#4727 fix(b-tooltip): fix arrow margin (closes #4721)
  src/components/popover/README.md
  src/components/tooltip/README.md
  src/components/tooltip/_tooltip.scss
  src/directives/popover/README.md
  src/directives/tooltip/README.md
Labels: PR: Patch, Type: Fix

#4729 docs(homepage): show sponsors on homepage
  README.md
  docs/components/anchored-heading.js
  docs/components/backers-donors.vue
  docs/components/componentdoc.vue
  docs/components/contributors-container.js
  docs/components/contributors.vue
  docs/components/doc-breadcrumbs.vue
  docs/components/feedback.js
  docs/components/importdoc.vue
  docs/components/main.js
  docs/components/quick-links.vue
  docs/components/search.vue
  docs/components/section.js
  docs/components/sidebar.vue
  docs/components/toc.vue
  docs/pages/index.vue
Labels: PR: Patch, Type: Docs, Type: Enhancement

#4742 docs(form-radio): add clarification to v-model section (closes #4736)
  src/components/form-radio/README.md
Labels: PR: Patch, Type: Docs

#4740 chore(readme): comment out package quality link as it is broken
  README.md
Labels: PR: Patch

#4739 fix(b-form-input, b-form-textarea): handle change event for all mobile device keyboards (closes #4724)
  src/components/form-input/README.md
  src/components/form-radio/README.md
  src/mixins/form-text.js
Labels: PR: Patch, Type: Docs, Type: Fix

#4728 chore: patch release v2.4.1
  CHANGELOG.md
  README.md
  docs/components/anchored-heading.js
  docs/components/backers-donors.vue
  docs/components/componentdoc.vue
  docs/components/contributors-container.js
  docs/components/contributors.vue
  docs/components/doc-breadcrumbs.vue
  docs/components/feedback.js
  docs/components/importdoc.vue
  docs/components/main.js
  docs/components/quick-links.vue
  docs/components/search.vue
  docs/components/section.js
  docs/components/sidebar.vue
  docs/components/toc.vue
  docs/pages/index.vue
  package.json
  src/components/form-input/README.md
  src/components/form-radio/README.md
  src/components/popover/README.md
  src/components/tooltip/README.md
  src/components/tooltip/_tooltip.scss
  src/directives/popover/README.md
  src/directives/tooltip/README.md
  src/mixins/form-text.js
  yarn.lock
Labels: PR: Patch

#4759 chore: create BVHoverSwap utility helper component
  src/utils/bv-hover-swap.js
  src/utils/bv-hover-swap.spec.js
  src/utils/bv-transition.js
Labels: PR: Patch, Type: Enhancement

#4763 fix(events): correct `capture` value of `EVENT_OPTIONS_NO_CAPTURE`
  src/utils/events.js
Labels: PR: Patch, Type: Fix

#4764 chore: properly ignore `browser.js` and browser-icons.js` during esm modular build
  scripts/build.sh
Labels: PR: Patch, Type: Fix

#4766 fix(b-modal): transition timing (closes #4761)
  src/components/modal/modal.js
Labels: PR: Patch, Type: Fix

#4767 docs(popovers, tooltips): add info about focus only trigger and cross platform behaviour
  src/components/popover/README.md
  src/components/tooltip/README.md
  src/directives/popover/README.md
  src/directives/tooltip/README.md
Labels: Type: Docs

#4768 fix(b-button): when `href` is "#" add `role=button` and appropriate keydown handlers for A11Y
  src/components/button/button.js
  src/components/button/button.spec.js
  src/components/link/link.js
Labels: PR: Patch, Type: Accessibility, Type: Fix

#4770 docs(b-button): add accessibility section
  src/components/button/README.md
Labels: PR: Patch, Type: Docs

#4772 chore: delete hoverswap private util component in favor of `v-b-hover` directive
  src/utils/bv-hover-swap.js
  src/utils/bv-hover-swap.spec.js
Labels: PR: Patch

#4771 feat(v-b-hover): new directive for reacting to hover changes
  src/directives/hover/README.md
  src/directives/hover/hover.js
  src/directives/hover/hover.spec.js
  src/directives/hover/index.d.ts
  src/directives/hover/index.js
  src/directives/hover/package.json
  src/directives/index.d.ts
  src/directives/index.js
  src/index.js
  src/utils/bv-hover-swap.js
  src/utils/bv-hover-swap.spec.js
Labels: PR: Minor, Type: Feature

#4712 feat(b-calendar, b-form-datepicker): new components `b-calendar` and `b-form-datepicker` (closes #3676, #1428)
  CHANGELOG.md
  docs/common-props.json
  docs/markdown/intro/README.md
  docs/markdown/misc/third-party/README.md
  docs/pages/index.vue
  package.json
  src/components/calendar/README.md
  src/components/calendar/_calendar.scss
  src/components/calendar/calendar.js
  src/components/calendar/calendar.spec.js
  src/components/calendar/index.d.ts
  src/components/calendar/index.js
  src/components/calendar/index.scss
  src/components/calendar/package.json
  src/components/dropdown/dropdown.js
  src/components/form-datepicker/README.md
  src/components/form-datepicker/_form-datepicker.scss
  src/components/form-datepicker/form-datepicker.js
  src/components/form-datepicker/form-datepicker.spec.js
  src/components/form-datepicker/index.d.ts
  src/components/form-datepicker/index.js
  src/components/form-datepicker/index.scss
  src/components/form-datepicker/package.json
  src/components/index.d.ts
  src/components/index.js
  src/components/index.scss
  src/components/modal/modal.js
  src/components/nav/nav-item-dropdown.js
  src/components/table/README.md
  src/components/table/helpers/filter-event.js
  src/components/toast/_toaster.scss
  src/index.js
  src/mixins/dropdown.js
  src/utils/config-defaults.js
  src/utils/date.js
  src/utils/date.spec.js
Labels: PR: Minor, Type: Feature

#4777 fix(b-modal): additional fixes for show transition behaviour (closes #4761)
  src/components/modal/modal.js
Labels: PR: Patch, Type: Fix

#4744 feat(b-form-spinbutton): new form control component `b-form-spinbutton`
  src/components/calendar/calendar.js
  src/components/form-datepicker/README.md
  src/components/form-spinbutton/README.md
  src/components/form-spinbutton/_spinbutton.scss
  src/components/form-spinbutton/form-spinbutton.js
  src/components/form-spinbutton/form-spinbutton.spec.js
  src/components/form-spinbutton/index.d.ts
  src/components/form-spinbutton/index.js
  src/components/form-spinbutton/index.scss
  src/components/form-spinbutton/package.json
  src/components/index.d.ts
  src/components/index.js
  src/components/index.scss
  src/index.js
  src/utils/config-defaults.js
Labels: PR: Minor, Type: Feature

#4775 fix(b-form-tags): improve accessibility for screen reader users
  src/components/button/README.md
  src/components/form-tags/README.md
  src/components/form-tags/form-tag.js
  src/components/form-tags/form-tags.js
  src/components/form-tags/package.json
  src/utils/config-defaults.js
Labels: PR: Minor, Type: Accessibility

#4784 chore(b-form-spinbutton): add two missing props
  src/components/form-spinbutton/form-spinbutton.js
  src/components/form-spinbutton/package.json
Labels: PR: Patch, Type: Docs

#4785 chore: remove beta tags from calendar and datepicker
  src/components/calendar/package.json
  src/components/form-datepicker/package.json
Labels: PR: Minor

#4788 chore(b-form-tags): remove new tag from package.json meta
  src/components/form-tags/package.json
Labels: PR: Patch, Type: Docs

#4787 docs: improve anchored heading accessibility
  docs/components/anchored-heading.js
  docs/nuxt.config.js
Labels: PR: Patch, Type: Accessibility, Type: Docs

#4791 fix(docs): error in tooltips directive example
  src/components/tooltip/README.md
Labels: Type: Docs

#4800 chore(b-datepicker): minor code optimizations for better minification
  src/components/form-datepicker/form-datepicker.js
Labels: PR: Minor, PR: Patch, Type: Refactor

#4802 fix(b-form-spinbutton): prevent buttons from re-ordering when parent element is RTL
  src/components/form-spinbutton/_spinbutton.scss
  src/components/form-spinbutton/form-spinbutton.js
  src/components/form-spinbutton/form-spinbutton.spec.js
Labels: PR: Patch

#4809 docs: add links to new inputs in form docs
  src/components/form/README.md
Labels: PR: Patch, Type: Docs

#4807 chore(docs): tweak backers/donors
  docs/components/contributors-container.js
  docs/components/contributors.vue
Labels: PR: Patch, Type: Docs

#4812 chore: minor tweaks to docs for SEO, etc.
  package.json
  src/components/calendar/package.json
  src/components/form-datepicker/package.json
  src/components/form-spinbutton/package.json
  src/icons/package.json
Labels: PR: Patch, Type: Docs

#4810 feat(b-pagination, b-pagination-nav): improve aria accessibility (closes: #4811, #4160)
  src/components/form-tags/README.md
  src/components/pagination-nav/README.md
  src/components/pagination-nav/pagination-nav.spec.js
  src/components/pagination/pagination.js
  src/components/pagination/pagination.spec.js
  src/mixins/pagination.js
Labels: PR: Minor, Type: Accessibility, Type: Enhancement

#4806 feat(b-tabs): add ability to provide custom tab button attributes (closes: #4803)
  src/components/tabs/package.json
  src/components/tabs/tab.js
  src/components/tabs/tabs.js
Labels: PR: Minor, Type: Feature

#4795 feat(b-form-datepicker): add `button-content` optionally scoped slot for icon
  src/components/form-datepicker/form-datepicker.js
  src/components/form-datepicker/form-datepicker.spec.js
  src/components/form-datepicker/package.json
Labels: PR: Minor, Type: Enhancement

#4822 feat(b-form-datepicker): add calendar-width prop (closes #4817)
  src/components/calendar/_calendar.scss
  src/components/calendar/calendar.js
  src/components/form-datepicker/form-datepicker.js
  src/components/form-datepicker/package.json
Labels: PR: Minor, Type: Enhancement

#4824 fix(b-form-datepicker): menu focus handling for Firefox and Safari on MacOS (closes #4814)
  src/components/calendar/calendar.js
  src/components/form-datepicker/form-datepicker.js
Labels: PR: Patch, Type: Fix

#4836 chore(docs): componentdoc - allow object prop defaults to wrap
  docs/components/componentdoc.vue
Labels: PR: Minor

#4835 feat(b-calendar, b-form-datepicker): allow customization of in-component displayed date format (closes #4797)
  src/components/calendar/README.md
  src/components/calendar/calendar.js
  src/components/calendar/package.json
  src/components/form-datepicker/README.md
  src/components/form-datepicker/form-datepicker.js
  src/components/form-datepicker/package.json
Labels: PR: Minor, Type: Enhancement, Type: Feature

#4841 docs: always use array format for `<b-form-select>` options
  src/components/form/README.md
Labels: Type: Docs, Type: Fix

#4842 fix(b-form-spinbutton): prevent double increment/decrement on mobile (fixes #4838)
  src/components/form-spinbutton/form-spinbutton.js
Labels: PR: Patch, Type: Fix
