Repository bootstrap-vue/bootstrap-vue, pull requests merged in 2020-01, with the labels that each got.

#4545 chore: update copyright year to 2020
  LICENSE
  src/components/table/helpers/default-sort-compare.spec.js
  src/icons/icons.d.ts
  src/icons/icons.js
  src/icons/plugin.js
  src/utils/loose-equal.spec.js
Labels: PR: Patch, Type: Enhancement

#4541 chore(docs): add `b-breadcrumb-item` usage example
  src/components/breadcrumb/README.md
Labels: PR: Patch, Type: Docs

#4551 fix(docs): correct spelling error in `b-form-file` property description
  src/components/form-file/package.json
Labels: Type: Docs, Type: Fix

#4552 feat(chore): configure pre-commit hook (fixes #4532)
  package.json
  yarn.lock
Labels: PR: Patch, Type: Enhancement

#4542 feat(docs): make more concise and explain how to hide `b-toast` title
  src/components/toast/README.md
Labels: Type: Docs

#4566 chore(docs): disable autocomplete on the icons search field
  docs/components/icons-table.vue
Labels: PR: Patch, Type: Docs

#4567 chore(docs): minor updates to the icons docs
  src/icons/README.md
Labels: PR: Patch, Type: Docs

#4563 feat(b-tooltip): add `noninteractive` prop (closes #4556)
  src/components/popover/_popover.scss
  src/components/tooltip/README.md
  src/components/tooltip/_tooltip.scss
  src/components/tooltip/helpers/bv-tooltip-template.js
  src/components/tooltip/helpers/bv-tooltip.js
  src/components/tooltip/package.json
  src/components/tooltip/tooltip.js
  src/components/tooltip/tooltip.spec.js
  src/directives/tooltip/README.md
  src/directives/tooltip/package.json
  src/directives/tooltip/tooltip.js
  src/directives/tooltip/tooltip.spec.js
  src/icons/package.json
Labels: PR: Minor, Type: Feature

#4576 chore(docs): use icons on landing page
  docs/pages/index.vue
Labels: Type: Docs

#4579 fix(utils): correct `identity` spelling error
  src/utils/get.js
  src/utils/normalize-slot.js
Labels: Type: Fix

#4584 feat(docs): improve form validation examples (closes #4550)
  docs/markdown/reference/validation/README.md
Labels: PR: Patch, Type: Docs, Type: Enhancement

#4582 chore(docs): add example of using dropdown in form-tags custom rendering (closes #1794)
  src/components/form-tags/README.md
Labels: PR: Patch, Type: Docs

#4583 docs: add utilities section to layout docs + update docs links to bootstrap docs v4.4
  docs/markdown/intro/README.md
  docs/markdown/misc/third-party/README.md
  docs/markdown/reference/accessibility/README.md
  docs/markdown/reference/theming/README.md
  docs/markdown/reference/utility-classes/README.md
  docs/pages/index.vue
  src/components/form/README.md
  src/components/layout/README.md
Labels: PR: Patch, Type: Docs

#4587 chore: add configuration for the "Stale" GitHub app
  .github/stale.yml
Labels: PR: Patch

#4590 fix(typescript): include named export `BootstrapVue` in type declaration file
  src/index.d.ts
Labels: PR: Patch, Type: Fix, Type: Types

#4595 fix(types): add missing declarations for `b-form-select-option` and `b-form-select-option-group`
  src/components/form-select/index.d.ts
Labels: PR: Patch, Type: Fix, Type: Types

#4605 docs(modal): update modal prevent closing example
  src/components/modal/README.md
Labels: PR: Patch, Type: Docs

#4608 fix(icons): make icon transform props work with IE11 (closes #4607)
  src/icons/README.md
  src/icons/helpers/make-icon.js
  src/icons/icons.spec.js
Labels: PR: Patch, Type: Fix

#4604 fix(modal, tooltips, popovers): remove no longer needed `nextTick` delay when updating content in transporter portal (closes #4589)
  src/components/modal/modal.spec.js
  src/utils/transporter.js
  src/utils/transporter.spec.js
Labels: Type: Enhancement, Type: Fix

#4596 chore: bump version and update changelog
  CHANGELOG.md
  package.json
Labels: Status: WIP

#4585 chore: patch release v2.2.1
  .github/stale.yml
  CHANGELOG.md
  README.md
  docs/markdown/intro/README.md
  docs/markdown/misc/third-party/README.md
  docs/markdown/reference/accessibility/README.md
  docs/markdown/reference/theming/README.md
  docs/markdown/reference/utility-classes/README.md
  docs/markdown/reference/validation/README.md
  docs/pages/index.vue
  package.json
  src/components/form-select/index.d.ts
  src/components/form-tags/README.md
  src/components/form/README.md
  src/components/layout/README.md
  src/components/modal/README.md
  src/components/modal/modal.spec.js
  src/components/table/package.json
  src/icons/README.md
  src/icons/helpers/make-icon.js
  src/icons/icons.spec.js
  src/index.d.ts
  src/utils/get.js
  src/utils/normalize-slot.js
  src/utils/transporter.js
  src/utils/transporter.spec.js
  yarn.lock
Labels: PR: Patch

#4624 fix(nuxt module): remove unnecessary export statements
  nuxt/index.js
Labels: PR: Patch, Type: Fix

#4630 chore(docs): Fix variant text capitalisation
  docs/markdown/reference/color-variants/README.md
Labels: Type: Docs, Type: Fix

#4628 chore: bump version to 2.2.2 and update changelog
  CHANGELOG.md
  package.json
Labels: PR: Patch

#4625 chore: release v2.2.2
  CHANGELOG.md
  docs/markdown/reference/color-variants/README.md
  nuxt/index.js
  package.json
  src/components/form-tags/README.md
  yarn.lock
Labels: PR: Patch

#4647 fix(utils): pass all Array/Object util shortcuts as functions, for handling late loaded polyfills
  src/utils/array.js
  src/utils/dom.js
  src/utils/object.js
Labels: PR: Patch, Type: Enhancement, Type: Fix, Type: Refactor

#4574 feat(b-button-close): add `content` prop (closes #4527)
  src/components/button/button-close.js
  src/components/button/button-close.spec.js
  src/components/button/package.json
  src/components/modal/modal.js
  src/components/modal/package.json
  src/utils/config-defaults.js
Labels: PR: Minor, Type: Feature

#4645 feat(form-tags): new option to specify input type (closes #4644)
  src/components/form-tags/README.md
  src/components/form-tags/form-tags.js
  src/components/form-tags/form-tags.spec.js
  src/components/form-tags/package.json
Labels: PR: Minor, Type: Enhancement

#4664 chore(docs): correct use of `its` vs. `it's` and minor tweaks
  docs/markdown/reference/starter-templates/README.md
  docs/markdown/reference/validation/README.md
  docs/pages/play.vue
  src/components/button/package.json
  src/components/card/README.md
  src/components/dropdown/README.md
  src/components/dropdown/_dropdown-form.scss
  src/components/dropdown/package.json
  src/components/form-input/README.md
  src/components/form-input/_form-input.scss
  src/components/form-select/README.md
  src/components/form-tags/README.md
  src/components/form/README.md
  src/components/image/README.md
  src/components/image/package.json
  src/components/jumbotron/README.md
  src/components/layout/README.md
  src/components/link/link.js
  src/components/modal/modal.js
  src/components/modal/package.json
  src/components/pagination-nav/README.md
  src/components/pagination/README.md
  src/components/progress/README.md
  src/components/spinner/README.md
  src/components/table/README.md
  src/components/tabs/tabs.js
  src/components/toast/README.md
  src/components/tooltip/helpers/bv-tooltip.js
  src/components/tooltip/tooltip.spec.js
  src/directives/scrollspy/scrollspy.class.js
  src/directives/toggle/toggle.js
  src/icons/README.md
  src/mixins/dropdown.js
  src/utils/dom.js
  src/utils/transporter.js
Labels: PR: Patch, Type: Docs, Type: Enhancement

#4658 feat(icons): add stacking support
  docs/content/index.js
  docs/pages/docs/icons/index.js
  scripts/create-icons.js
  src/icons/README.md
  src/icons/helpers/make-icon.js
  src/icons/icon.js
  src/icons/icons.d.ts
  src/icons/icons.js
  src/icons/iconstack.js
  src/icons/iconstack.spec.js
  src/icons/index.d.ts
  src/icons/index.js
  src/icons/package.json
  src/icons/plugin.js
  src/index.js
Labels: PR: Minor, Type: Feature

#4640 chore(build): export the icons plugin direct from icons/plugin.js
  src/icons/helpers/icon-base.js
  src/icons/helpers/make-icon.js
  src/icons/icon.js
  src/icons/iconstack.js
  src/index.js
Labels: Type: Refactor

#4667 chore(pagination): tweaks to pagination PR #4622
  src/components/pagination/pagination.spec.js
  src/mixins/pagination.js
Labels: Type: Accessibility, Type: Refactor

#4622 feat(b-pagination, b-pagination-nav): add page button class props and option to show first/last page numbers (closes #4597, #4533)
  docs/markdown/intro/README.md
  src/components/dropdown/dropdown.js
  src/components/modal/README.md
  src/components/pagination-nav/README.md
  src/components/pagination-nav/package.json
  src/components/pagination/README.md
  src/components/pagination/package.json
  src/components/pagination/pagination.spec.js
  src/mixins/dropdown.js
  src/mixins/pagination.js
  src/utils/config-set.js
Labels: PR: Minor, Type: Feature

#4672 fix(v-b-modal): only unbind/rebind if trigger element or modal ID changes (closes #4669)
  src/directives/modal/modal.js
Labels: PR: Patch, Type: Fix

#4677 chore(docs): mention in table docs that `fixed` and `responsive` do not work well with each other (closes #4598)
  src/components/table/README.md
Labels: Type: Docs

#4680 fix(docs): add missing close tags for `<b-icon>` components
  src/icons/README.md
Labels: Type: Docs, Type: Fix

#4691 feat(b-nav-item-dropdown): add `boundary` prop, applicable when not in `b-navbar` (closes #4684)
  src/components/dropdown/dropdown.js
  src/components/nav/package.json
  src/mixins/dropdown.js
Labels: PR: Minor, Type: Enhancement, Type: Feature

#4426 fix(b-dropdown): focus-in handling for Safari and Firefox on macOS/iOS (closes #4328)
  src/components/dropdown/README.md
  src/components/dropdown/dropdown-item-button.js
  src/components/dropdown/dropdown-item.js
  src/components/dropdown/dropdown.js
  src/components/nav/nav-item-dropdown.js
  src/components/navbar/navbar.js
  src/components/navbar/navbar.spec.js
  src/mixins/click-out.js
  src/mixins/dropdown.js
Labels: PR: Patch, Type: Fix

#4701 fix(b-form-input, b-form-textarea): properly handle out-of-sync values (closes #4695)
  src/components/form-input/README.md
  src/components/form-textarea/README.md
  src/mixins/form-text.js
Labels: PR: Patch, Type: Fix

#4702 feat(b-modal): add `ignore-enforce-focus-selector` prop (closes #4537)
  src/components/modal/README.md
  src/components/modal/modal.js
  src/components/modal/modal.spec.js
  src/components/modal/package.json
Labels: PR: Minor, Type: Feature

#4708 chore(docs): minor update to modal docs re TinyMCE
  src/components/modal/README.md
Labels: Type: Docs
