Repository bootstrap-vue/bootstrap-vue, pull requests merged in 2020-09, with the labels that each got.

#5705 feat(b-calendar): add `nav-button-variant` prop (closes #5702)
  src/components/calendar/README.md
  src/components/calendar/calendar.js
  src/components/calendar/calendar.spec.js
  src/components/calendar/package.json
  src/components/form-datepicker/README.md
  src/components/form-datepicker/form-datepicker.js
  src/components/form-datepicker/package.json
  src/utils/config-defaults.js
Labels: PR: Minor, Type: Enhancement

#5716 fix(b-form-checkbox): `change` event value when in multiple mode (closes #5697)
  src/components/form-checkbox/form-checkbox-group.js
  src/components/form-checkbox/form-checkbox-group.spec.js
  src/components/form-checkbox/form-checkbox.js
  src/components/form-checkbox/form-checkbox.spec.js
  src/mixins/form-radio-check-group.js
  src/mixins/form-radio-check.js
Labels: PR: Patch, Type: Fix

#5724 feat(b-icon): add proper `title` support (closes #5711)
  src/icons/helpers/icon-base.js
  src/icons/helpers/make-icon.js
  src/icons/icons.d.ts
  src/icons/icons.js
  src/icons/icons.spec.js
  src/icons/iconstack.spec.js
  src/icons/package.json
  src/icons/plugin.js
Labels: PR: Minor, Type: Accessibility, Type: Enhancement

#5730 chore(docs): fix minor typo in color variants documentation
  docs/markdown/reference/color-variants/README.md
Labels: Type: Docs

#5734 feat(b-sidebar): add `noEnforceFocus` prop (closes #5707)
  src/components/sidebar/README.md
  src/components/sidebar/package.json
  src/components/sidebar/sidebar.js
Labels: PR: Minor, Type: Accessibility, Type: Enhancement

#5737 fix(b-button-toolbar): allow focus to leave toolbar by keyboard when `key-nav` enabled (closes #5733)
  src/components/button-toolbar/button-toolbar.js
Labels: PR: Patch, Type: Accessibility, Type: Fix

#5723 fix(ssr): avoid tree missmatches by either using `domProps` or `children` (closes #5453, #5557)
  src/components/dropdown/dropdown.js
  src/components/modal/modal.js
  src/components/progress/README.md
  src/components/progress/progress-bar.js
  src/utils/html.js
Labels: PR: Patch, Type: Fix, Type: Nuxt.js, Type: SSR

#5743 chore: regenerate lockfile
  yarn.lock
Labels: Type: Chore, Type: Dependencies, Type: Security

#5746 feat(b-table): add `sortKey` option for `no-local-sorting` events
  src/components/table/README.md
  src/components/table/helpers/mixin-sorting.js
  src/components/table/index.d.ts
  src/components/table/table-sorting.spec.js
Labels: PR: Minor, Type: Enhancement, Type: Feature

#5543 feat(b-tags): add `limit` prop
  docs/markdown/reference/color-variants/README.md
  src/components/form-tags/README.md
  src/components/form-tags/form-tags.js
  src/components/form-tags/form-tags.spec.js
  src/components/form-tags/package.json
  src/icons/README.md
  src/utils/config-defaults.js
Labels: PR: Minor, Type: Feature

#5749 fix: component destroy handling on parent destroy (closes #5747)
  src/components/modal/helpers/bv-modal.js
  src/components/toast/helpers/bv-toast.js
  src/components/tooltip/helpers/bv-popper.js
  src/components/tooltip/helpers/bv-tooltip.js
Labels: PR: Patch, Type: Fix

#5752 fix(b-form-tags): ensure same height with or without tags (closes #5750)
  src/components/form-tags/_form-tags.scss
  src/components/form-tags/form-tags.js
Labels: PR: Patch, Type: Accessibility, Type: Fix, Type: SCSS

#5754 fix(b-pagination-nav) don't set `aria-posinset` and `aria-setsize` attributes for page links (closes #5449)
  src/mixins/pagination.js
Labels: PR: Patch, Type: Accessibility, Type: Fix

#5753 fix(perf): reactivity issues with `bvAttrs` and `bvListeners` (closes #5520)
  src/utils/cache.js
Labels: PR: Patch, Type: Fix, Type: Perf

#5755 feat(b-pagination/b-pagination-nav): allow page change to be prevented (closes #5679)
  src/components/pagination-nav/README.md
  src/components/pagination-nav/package.json
  src/components/pagination-nav/pagination-nav.js
  src/components/pagination-nav/pagination-nav.spec.js
  src/components/pagination/README.md
  src/components/pagination/package.json
  src/components/pagination/pagination.js
  src/components/pagination/pagination.spec.js
  src/mixins/pagination.js
Labels: PR: Minor, Type: Enhancement, Type: Feature

#5727 feat(b-form-file): improved drag and drop handling (closes #3673)
  .eslintrc.js
  docs/common-props.json
  docs/components/contributors.vue
  docs/pages/play.vue
  package.json
  scripts/create-icons.js
  scripts/create-web-types.js
  src/components/button-toolbar/button-toolbar.js
  src/components/button/button-close.js
  src/components/button/button.js
  src/components/calendar/calendar.js
  src/components/carousel/carousel-slide.js
  src/components/carousel/carousel.js
  src/components/form-file/README.md
  src/components/form-file/_form-file.scss
  src/components/form-file/form-file.js
  src/components/form-file/form-file.spec.js
  src/components/form-file/index.d.ts
  src/components/form-file/package.json
  src/components/form-input/form-input.js
  src/components/form-rating/form-rating.js
  src/components/form-spinbutton/form-spinbutton.js
  src/components/form-tags/form-tags.js
  src/components/image/img-lazy.spec.js
  src/components/image/img.js
  src/components/link/link.js
  src/components/pagination-nav/pagination-nav.js
  src/components/table/helpers/mixin-bottom-row.js
  src/components/table/helpers/mixin-busy.js
  src/components/table/helpers/mixin-colgroup.js
  src/components/table/helpers/mixin-tbody-row.js
  src/components/table/helpers/mixin-tbody.js
  src/components/table/helpers/mixin-thead.js
  src/components/table/helpers/mixin-top-row.js
  src/components/table/helpers/normalize-fields.js
  src/components/table/helpers/normalize-fields.spec.js
  src/components/table/table-sticky-column.spec.js
  src/components/table/td.js
  src/components/tabs/tab.js
  src/components/tabs/tabs.js
  src/components/time/time.js
  src/components/toast/toast.js
  src/mixins/dropdown.js
  src/mixins/form-text.js
  src/mixins/pagination.js
  src/utils/array.js
  src/utils/bv-form-btn-label-control.js
  src/utils/config-defaults.js
  src/utils/date.js
  src/utils/events.js
  yarn.lock
Labels: PR: Minor, Type: Enhancement, Type: Fix

#5760 chore(docs): fix typo
  docs/markdown/reference/settings/README.md
  src/components/link/README.md
Labels: PR: Patch, Type: Chore, Type: Docs

#5761 feat(docs): auto-detect `settings` props in component reference
  docs/common-props.json
  docs/components/componentdoc.vue
  src/components/alert/package.json
  src/components/avatar/package.json
  src/components/badge/package.json
  src/components/button/package.json
  src/components/calendar/package.json
  src/components/card/package.json
  src/components/carousel/package.json
  src/components/dropdown/package.json
  src/components/form-checkbox/package.json
  src/components/form-datepicker/package.json
  src/components/form-file/package.json
  src/components/form-input/package.json
  src/components/form-radio/package.json
  src/components/form-rating/package.json
  src/components/form-select/package.json
  src/components/form-spinbutton/package.json
  src/components/form-tags/package.json
  src/components/form-textarea/package.json
  src/components/form-timepicker/package.json
  src/components/form/package.json
  src/components/image/package.json
  src/components/input-group/package.json
  src/components/jumbotron/package.json
  src/components/list-group/package.json
  src/components/modal/package.json
  src/components/navbar/package.json
  src/components/pagination-nav/package.json
  src/components/pagination/package.json
  src/components/popover/package.json
  src/components/progress/package.json
  src/components/spinner/package.json
  src/components/table/package.json
  src/components/time/package.json
  src/components/toast/package.json
  src/components/tooltip/package.json
Labels: Type: Docs, Type: Enhancement

#5762 chore(docs): clarify note on non-text-like input `formatter` functions (closes #5518)
  .github/PULL_REQUEST_TEMPLATE.md
  CHANGELOG.md
  docs/markdown/intro/README.md
  docs/markdown/reference/settings/README.md
  docs/markdown/reference/theming/README.md
  docs/nuxt.config.js
  scripts/build.sh
  src/components/aspect/README.md
  src/components/avatar/README.md
  src/components/calendar/calendar.js
  src/components/form-checkbox/README.md
  src/components/form-datepicker/form-datepicker.js
  src/components/form-input/README.md
  src/components/form-radio/README.md
  src/components/form-select/README.md
  src/components/form-tags/README.md
  src/components/form-timepicker/README.md
  src/components/jumbotron/README.md
  src/components/modal/modal.spec.js
  src/components/popover/README.md
  src/components/progress/README.md
  src/components/sidebar/README.md
  src/components/table/README.md
  src/components/time/README.md
  src/components/tooltip/README.md
  src/directives/popover/README.md
  src/directives/tooltip/README.md
  src/utils/number.js
  src/utils/observe-dom.js
Labels: Type: Chore, Type: Docs

#5763 fix: don't display warning messages when in production (closes #5598)
  docs/markdown/reference/settings/README.md
  src/components/pagination/pagination.js
  src/components/tooltip/helpers/bv-tooltip.js
  src/components/tooltip/tooltip.spec.js
  src/utils/env.js
Labels: PR: Patch, Type: Fix

#5764 fix(b-form-checkbox/b-form-radio): remove `autocomplete="off"` attribute (closes #4230)
  src/mixins/form-radio-check.js
Labels: PR: Patch, Type: Fix

#5765 fix(b-form-datepicker/b-form-timepicker/b-nav-item-dropdown): dropdown positioning handling (closes #5700, #5630)
  src/components/dropdown/README.md
  src/components/dropdown/dropdown.js
  src/components/form-datepicker/README.md
  src/components/form-timepicker/README.md
  src/components/nav/README.md
  src/components/nav/nav-item-dropdown.js
  src/mixins/dropdown.js
  src/utils/bv-form-btn-label-control.js
  src/utils/events.js
  src/utils/object.js
  src/utils/object.spec.js
Labels: PR: Patch, Type: Docs, Type: Fix

#5768 feat(b-avatar): add size classes for `sm` and `lg` sizes (closes #5592)
  src/_variables.scss
  src/components/avatar/_avatar.scss
  src/components/avatar/avatar-group.spec.js
  src/components/avatar/avatar.js
  src/components/avatar/avatar.spec.js
Labels: PR: Minor, Type: Enhancement, Type: Feature

#5769 fix(v-b-toggle): prevent scroll anchoring behavior (closes #5715)
  src/components/collapse/README.md
  src/components/form-textarea/form-textarea.js
  src/components/modal/helpers/modal-manager.js
  src/directives/toggle/toggle.js
  src/utils/bv-collapse.js
  src/utils/dom.js
  src/utils/dom.spec.js
Labels: PR: Patch, Type: Fix

#5771 fix(b-modal): solve body padding not being removed
  src/components/modal/helpers/modal-manager.js
Labels: PR: Patch, Type: Fix

#5780 fix(b-table): properly handle empty included/excluded filter fields (closes #5775)
  src/components/table/README.md
  src/components/table/helpers/mixin-filtering.js
  src/components/table/helpers/sanitize-row.js
  src/components/table/table-filtering.spec.js
Labels: PR: Patch, Type: Fix

#5782 chore: lock `postcss` and `autoprefixer` for now (closes #5774)
  .github/renovate.json
  package.json
  yarn.lock
Labels: Type: Chore, Type: Dependencies

#5786 chore: bump version to v2.17.1
  CHANGELOG.md
  package.json
Labels: Type: Chore

#5793 fix(b-tooltip, b-popover): fix `title` not being reset on hide
  src/components/tooltip/helpers/bv-tooltip.js
  src/components/tooltip/tooltip.spec.js
Labels: PR: Patch, Type: Fix

#5794 fix(b-nav-item-dropdown): `boundary` handling in `<b-navbar>` (closes #5789)
  docs/common-props.json
  src/components/nav/nav-item-dropdown.js
  src/components/nav/nav-item-dropdown.spec.js
  src/components/nav/package.json
  src/mixins/dropdown.js
Labels: PR: Patch, Type: Docs, Type: Fix

#5796 chore(docs): fix unmatched quote in form-tags wrapper example
  src/components/form-tags/README.md
Labels: Type: Docs

#5801 chore(docs): fix typo in `b-form-rating` docs
  src/components/form-rating/README.md
Labels: Type: Docs

#5806 fix(b-skeleton): add missing component exports (closes #5804)
  src/components/skeleton/index.js
  src/index.js
Labels: PR: Patch, Type: Fix

#5807 chore(docs): correct `placement` description
  src/components/popover/package.json
  src/components/tooltip/package.json
Labels: Type: Chore, Type: Docs

#5805 chore: bump version to v2.17.2
  CHANGELOG.md
  package.json
Labels: Type: Chore

#5808 chore: release v2.17.2
  .versionrc
  CHANGELOG.md
  docs/common-props.json
  package.json
  src/components/form-rating/README.md
  src/components/form-tags/README.md
  src/components/nav/nav-item-dropdown.js
  src/components/nav/nav-item-dropdown.spec.js
  src/components/nav/package.json
  src/components/popover/package.json
  src/components/skeleton/index.js
  src/components/tooltip/helpers/bv-tooltip.js
  src/components/tooltip/package.json
  src/components/tooltip/tooltip.spec.js
  src/index.js
  src/mixins/dropdown.js
  yarn.lock
Labels: Type: Chore

#5834 chore(docs): fix typos in locale attribute
  src/components/form-timepicker/README.md
Labels: Type: Docs
