Repository bootstrap-vue/bootstrap-vue, pull requests merged in 2020-03, with the labels that each got.

#4783 feat(b-time, b-form-timepicker): new components `b-time` and `b-form-timepicker`
  docs/components/icons-table.vue
  docs/markdown/misc/third-party/README.md
  src/_custom-controls.scss
  src/components/calendar/README.md
  src/components/calendar/_calendar.scss
  src/components/calendar/calendar.js
  src/components/calendar/calendar.spec.js
  src/components/form-datepicker/README.md
  src/components/form-datepicker/_form-datepicker.scss
  src/components/form-datepicker/form-datepicker.js
  src/components/form-datepicker/index.scss
  src/components/form-datepicker/package.json
  src/components/form-spinbutton/_spinbutton.scss
  src/components/form-spinbutton/form-spinbutton.js
  src/components/form-spinbutton/form-spinbutton.spec.js
  src/components/form-timepicker/README.md
  src/components/form-timepicker/form-timepicker.js
  src/components/form-timepicker/form-timepicker.spec.js
  src/components/form-timepicker/index.js
  src/components/form-timepicker/package.json
  src/components/form/README.md
  src/components/index.d.ts
  src/components/index.js
  src/components/index.scss
  src/components/time/README.md
  src/components/time/_time.scss
  src/components/time/index.d.ts
  src/components/time/index.js
  src/components/time/index.scss
  src/components/time/package.json
  src/components/time/time.js
  src/components/time/time.spec.js
  src/index.js
  src/index.scss
  src/mixins/dropdown.js
  src/utils/bv-form-btn-label-control.js
  src/utils/config-defaults.js
  src/utils/locale.js
Labels: PR: Minor, Type: Feature

#4865 chore(docs): Fix typo `bart` -> `part`
  src/components/collapse/package.json
Labels: Type: Docs, Type: Fix

#4867 chore(docs): fix typo
  docs/markdown/intro/README.md
Labels: Type: Docs

#4880 chore(docs): show live examples of all positioning for tooltip and popover directives (closes #4877)
  src/components/popover/README.md
  src/components/tooltip/README.md
  src/directives/popover/README.md
  src/directives/tooltip/README.md
Labels: PR: Patch, Type: Docs

#4882 docs: improve code examples and enhance wording (closes #4859)
  CHANGELOG.md
  docs/assets/scss/styles.scss
  docs/markdown/intro/README.md
  docs/nuxt.config.js
  docs/plugins/play.js
  src/components/form-checkbox/_form-checkbox.scss
  src/components/form-input/README.md
  src/components/form-radio/_form-radio.scss
  src/components/table/README.md
  src/icons/README.md
Labels: PR: Patch, Type: Docs, Type: Enhancement

#4885 fix(b-form-spinbutton): respect step value for initial decrement when `wrap` enabled (closes #4884)
  src/components/form-spinbutton/form-spinbutton.js
Labels: PR: Patch, Type: Fix

#4890 docs(b-calendar, b-form-datepicker): fix mistake in date formatting examples
  src/components/calendar/README.md
  src/components/form-datepicker/README.md
Labels: PR: Patch, Type: Docs

#4895 chore(docs): fix typo in README
  src/components/calendar/README.md
Labels: PR: Patch, Type: Docs

#4891 docs: add Carbon ads
  docs/assets/scss/styles.scss
  docs/components/ad.js
  docs/components/quick-links.vue
  docs/layouts/docs.js
  docs/pages/index.vue
  docs/plugins/docs-mixin.js
Labels: PR: Patch, Type: Docs

#4896 docs(a11y): add references to reduced motion for certain component animations
  src/components/carousel/README.md
  src/components/collapse/README.md
  src/components/form-timepicker/package.json
  src/components/modal/README.md
  src/components/popover/README.md
  src/components/progress/README.md
  src/components/tooltip/README.md
Labels: PR: Patch, Type: Docs

#4897 chore(docs): add carbon ad to playground
  docs/components/anchored-heading.js
  docs/components/breadcrumbs.vue
  docs/components/code-mirror.js
  docs/components/componentdoc.vue
  docs/components/contributors-container.js
  docs/components/contributors.vue
  docs/components/feedback.js
  docs/components/footer.vue
  docs/components/header.vue
  docs/components/icons-table.vue
  docs/components/importdoc.vue
  docs/components/main.js
  docs/components/quick-links.vue
  docs/components/search.vue
  docs/components/section-toc.vue
  docs/components/section.js
  docs/components/sidebar.vue
  docs/components/toc.vue
  docs/layouts/default.js
  docs/layouts/docs.js
  docs/pages/index.vue
  docs/pages/play.vue
Labels: PR: Patch, Type: Docs

#4902 chore(docs): minor CSS tweak for playground
  docs/pages/play.vue
Labels: PR: Patch, Type: Docs

#4887 chore: patch release v2.6.1
  CHANGELOG.md
  docs/assets/scss/styles.scss
  docs/components/ad.js
  docs/components/anchored-heading.js
  docs/components/breadcrumbs.vue
  docs/components/code-mirror.js
  docs/components/componentdoc.vue
  docs/components/contributors-container.js
  docs/components/contributors.vue
  docs/components/feedback.js
  docs/components/footer.vue
  docs/components/header.vue
  docs/components/icons-table.vue
  docs/components/importdoc.vue
  docs/components/main.js
  docs/components/quick-links.vue
  docs/components/search.vue
  docs/components/section-toc.vue
  docs/components/section.js
  docs/components/sidebar.vue
  docs/components/toc.vue
  docs/layouts/default.js
  docs/layouts/docs.js
  docs/markdown/intro/README.md
  docs/nuxt.config.js
  docs/pages/index.vue
  docs/pages/play.vue
  docs/plugins/docs-mixin.js
  docs/plugins/play.js
  package.json
  src/components/calendar/README.md
  src/components/carousel/README.md
  src/components/collapse/README.md
  src/components/form-checkbox/_form-checkbox.scss
  src/components/form-datepicker/README.md
  src/components/form-input/README.md
  src/components/form-radio/_form-radio.scss
  src/components/form-spinbutton/form-spinbutton.js
  src/components/form-timepicker/package.json
  src/components/modal/README.md
  src/components/popover/README.md
  src/components/progress/README.md
  src/components/table/README.md
  src/components/tooltip/README.md
  src/directives/popover/README.md
  src/directives/tooltip/README.md
  src/icons/README.md
  yarn.lock
Labels: PR: Patch

#4908 docs: minor fixes to form-spinbutton meta json
  src/components/form-spinbutton/package.json
Labels: PR: Patch, Type: Docs

#4913 fix(b-form-file): fix value prop validation when using directory mode (fixes #4912)
  src/components/form-file/form-file.js
Labels: PR: Patch, Type: Fix

#4907 feat(`b-overlay`): new component `b-overlay`
  src/components/index.d.ts
  src/components/index.js
  src/components/overlay/README.md
  src/components/overlay/index.d.ts
  src/components/overlay/index.js
  src/components/overlay/overlay.js
  src/components/overlay/overlay.spec.js
  src/components/overlay/package.json
  src/index.js
Labels: PR: Minor, Type: Custom Component, Type: Feature

#4906 feat(b-calendar, b-for-datepicker): add new `initial-date` prop, and constrain today/current month buttons between `min` and `max` (closes #4899)
  src/components/calendar/README.md
  src/components/calendar/calendar.js
  src/components/calendar/package.json
  src/components/form-datepicker/README.md
  src/components/form-datepicker/form-datepicker.js
  src/components/form-datepicker/package.json
  src/components/form-timepicker/package.json
  src/components/time/package.json
  src/utils/date.js
  src/utils/date.spec.js
Labels: PR: Minor, Type: Enhancement, Type: Feature

#4915 feat(b-form-datepicker, b-form-timepicker): add support for icon button only mode (closes #4888)
  src/components/form-datepicker/README.md
  src/components/form-datepicker/form-datepicker.js
  src/components/form-datepicker/form-datepicker.spec.js
  src/components/form-datepicker/package.json
  src/components/form-timepicker/README.md
  src/components/form-timepicker/form-timepicker.js
  src/components/form-timepicker/form-timepicker.spec.js
  src/components/form-timepicker/package.json
  src/utils/bv-form-btn-label-control.js
Labels: PR: Minor, Type: Feature

#4923 docs(b-overlay): add additional usage examples
  docs/markdown/misc/third-party/README.md
  docs/markdown/reference/color-variants/README.md
  src/components/overlay/README.md
  src/components/overlay/package.json
Labels: PR: Patch, Type: Docs

#4930 docs: better PR detection for docs header
  docs/components/header.vue
  docs/nuxt.config.js
Labels: PR: Patch, Type: Docs

#4932 docs(list-group): update utility classes link to 4.4
  src/components/list-group/README.md
Labels: Type: Docs

#4933 chore(b-overlay): add notes on using in `<b-modal>`
  src/components/overlay/README.md
Labels: PR: Patch, Type: Docs

#4936 fix(b-form-file): make sure to catch all errors when resetting the input (closes #4837)
  src/components/form-file/form-file.js
Labels: PR: Patch, Status: Browser Bug, Type: Fix

#4934 feature(b-icon): add animated icon options (closes #4720)
  docs/nuxt.config.js
  scripts/build.sh
  scripts/icons.scss
  scripts/index.scss
  src/_variables.scss
  src/components/spinner/README.md
  src/icons.scss
  src/icons/README.md
  src/icons/_icons.scss
  src/icons/helpers/icon-base.js
  src/icons/icons.d.ts
  src/icons/icons.js
  src/icons/icons.spec.js
  src/icons/package.json
  src/icons/plugin.js
  src/index.scss
Labels: PR: Minor, Type: Feature

#4945 chore(icons): updates to CSS animations
  src/_variables.scss
  src/icons/README.md
  src/icons/_icons.scss
Labels: PR: Patch, Type: Enhancement

#4917 chore: release v2.7.0
  CHANGELOG-OLD.md
  CHANGELOG.md
  docs/components/footer.vue
  docs/components/header.vue
  docs/markdown/misc/third-party/README.md
  docs/markdown/reference/color-variants/README.md
  docs/nuxt.config.js
  package.json
  scripts/build.sh
  scripts/icons.scss
  scripts/index.scss
  src/_variables.scss
  src/components/calendar/README.md
  src/components/calendar/calendar.js
  src/components/calendar/package.json
  src/components/form-datepicker/README.md
  src/components/form-datepicker/form-datepicker.js
  src/components/form-datepicker/form-datepicker.spec.js
  src/components/form-datepicker/package.json
  src/components/form-file/form-file.js
  src/components/form-spinbutton/package.json
  src/components/form-timepicker/README.md
  src/components/form-timepicker/form-timepicker.js
  src/components/form-timepicker/form-timepicker.spec.js
  src/components/form-timepicker/package.json
  src/components/index.d.ts
  src/components/index.js
  src/components/list-group/README.md
  src/components/overlay/README.md
  src/components/overlay/index.d.ts
  src/components/overlay/index.js
  src/components/overlay/overlay.js
  src/components/overlay/overlay.spec.js
  src/components/overlay/package.json
  src/components/spinner/README.md
  src/components/time/package.json
  src/icons.scss
  src/icons/README.md
  src/icons/_icons.scss
  src/icons/helpers/icon-base.js
  src/icons/icons.d.ts
  src/icons/icons.js
  src/icons/icons.spec.js
  src/icons/package.json
  src/icons/plugin.js
  src/index.js
  src/index.scss
  src/utils/bv-form-btn-label-control.js
  src/utils/date.js
  src/utils/date.spec.js
  static/avatar.png
  yarn.lock
Labels: PR: Minor

#4951 chore(readme): packagequality is back online now
  README.md
Labels: PR: Patch

#4952 chore: use `https://` for links wherever possible
  CODE_OF_CONDUCT.md
  README.md
  src/components/breadcrumb/README.md
  src/components/dropdown/README.md
  src/components/form-file/README.md
  src/components/form-file/form-file.js
  src/components/form-group/README.md
  src/components/table/README.md
  src/components/toast/README.md
  src/utils/observe-dom.js
Labels: PR: Patch, Type: Docs

#4953 chore: regen `yarn.lock` and ensure new line in icons `package.json`
  scripts/create-icons.js
  yarn.lock
Labels: PR: Patch

#4954 chore(docs): add popper version to getting started
  docs/content/index.js
  docs/markdown/intro/README.md
  docs/pages/docs/index.js
Labels: PR: Patch, Type: Docs

#4961 chore(docs): fix typo in b-overlay docs
  src/components/overlay/README.md
Labels: PR: Patch, Type: Docs

#4966 feat: upgrade to bootstrap icons alpha 3
  .prettierignore
  README.md
  docs/components/icons-table.vue
  docs/pages/index.vue
  package.json
  scripts/create-icons.js
  src/components/overlay/README.md
  src/icons/README.md
  src/icons/_icons.scss
  src/icons/helpers/icon-base.js
  src/icons/icons.d.ts
  src/icons/icons.js
  src/icons/icons.spec.js
  src/icons/iconstack.spec.js
  src/icons/package.json
  src/icons/plugin.js
  yarn.lock
Labels: Bootstrap Icons, PR: Minor, Type: Enhancement

#4963 feat(b-form-spinbutton): add slots for increment and decrement button content (closes #4958)
  src/components/form-spinbutton/_spinbutton.scss
  src/components/form-spinbutton/form-spinbutton.js
  src/components/form-spinbutton/package.json
  src/components/form-timepicker/README.md
  src/components/time/time.js
Labels: PR: Minor, Type: Enhancement

#4973 chore(b-calendar): use new double chevron icons
  src/components/calendar/calendar.js
  src/components/form-datepicker/form-datepicker.js
  src/components/form-timepicker/form-timepicker.js
Labels: PR: Patch

#4974 feat(b-avatar): new b-avatar component
  docs/markdown/intro/README.md
  docs/markdown/reference/images/README.md
  nuxt/index.js
  src/components/avatar/README.md
  src/components/avatar/_avatar.scss
  src/components/avatar/avatar.js
  src/components/avatar/avatar.spec.js
  src/components/avatar/index.d.ts
  src/components/avatar/index.js
  src/components/avatar/index.scss
  src/components/avatar/package.json
  src/components/index.d.ts
  src/components/index.js
  src/components/index.scss
  src/components/overlay/README.md
  src/index.js
  src/utils/config-defaults.js
Labels: PR: Minor, Type: Custom Component, Type: Feature

#4981 docs(b-overlay): add no-center example
  src/components/overlay/README.md
Labels: PR: Patch, Type: Docs

#4987 chore(docs): note changes from alpha2 to alpha3 icons
  src/icons/README.md
Labels: Bootstrap Icons, Type: Docs

#4991 feat(b-avatar): add `alt` prop for adding alt attribute to image and icon avatars (closes #4990)
  src/components/avatar/avatar.js
  src/components/avatar/package.json
Labels: PR: Minor, Type: Enhancement

#4996 chore(docs): minor update to homepage icons
  docs/pages/index.vue
Labels: PR: Patch, Type: Docs

#4995 feat(b-navbar-toggle): make default slot scoped
  src/components/collapse/collapse.js
  src/components/navbar/README.md
  src/components/navbar/navbar-toggle.js
  src/components/navbar/navbar-toggle.spec.js
  src/components/navbar/package.json
  src/directives/toggle/toggle.js
Labels: PR: Minor, Type: Enhancement

#5003 fix(docs): ensure that the IconsPlugin is imported when exporting from playground to CodePen, CodeSandbox, and JsFiddle
  docs/pages/play.vue
Labels: PR: Patch, Type: Docs, Type: Fix

#5004 feat(b-form-datepicker, b-form-timepicker): emit `shown` and `hidden` events
  src/components/form-datepicker/form-datepicker.js
  src/components/form-datepicker/package.json
  src/components/form-timepicker/form-timepicker.js
  src/components/form-timepicker/package.json
Labels: PR: Minor, Type: Feature

#5007 chore(docs): fix a few minor issues with some examples
  src/components/form-datepicker/README.md
Labels: Type: Docs

#5011 chore(docs): use docs issue template when reporting docs issue
  .github/ISSUE_TEMPLATE/DOCS_ISSUE_TEMPLATE.md
  docs/components/feedback.js
Labels: PR: Patch, Type: Docs

#5008 feat(b-aspect): new custom component `<b-aspect>`
  src/components/aspect/README.md
  src/components/aspect/aspect.js
  src/components/aspect/aspect.spec.js
  src/components/aspect/index.d.ts
  src/components/aspect/index.js
  src/components/aspect/package.json
  src/components/embed/README.md
  src/components/form-spinbutton/README.md
  src/components/form-spinbutton/package.json
  src/components/index.d.ts
  src/components/index.js
  src/index.js
Labels: PR: Minor, Type: Custom Component, Type: Feature

#5014 feat(b-drodpown-item-button, b-drodpown-item-button): add `button-class` and `link-class` prop
  src/components/dropdown/dropdown-item-button.js
  src/components/dropdown/dropdown-item-button.spec.js
  src/components/dropdown/dropdown-item.js
  src/components/dropdown/dropdown-item.spec.js
  src/components/dropdown/package.json
Labels: PR: Minor, Type: Feature

#5013 chore(docs): minor updates to modal props meta
  src/components/modal/package.json
Labels: PR: Patch, Type: Docs

#4993 chore: release v2.9.0
  .github/ISSUE_TEMPLATE/DOCS_ISSUE_TEMPLATE.md
  CHANGELOG.md
  docs/components/feedback.js
  docs/pages/index.vue
  docs/pages/play.vue
  package.json
  src/components/aspect/README.md
  src/components/aspect/aspect.js
  src/components/aspect/aspect.spec.js
  src/components/aspect/index.d.ts
  src/components/aspect/index.js
  src/components/aspect/package.json
  src/components/avatar/avatar.js
  src/components/avatar/package.json
  src/components/collapse/collapse.js
  src/components/dropdown/dropdown-item-button.js
  src/components/dropdown/dropdown-item-button.spec.js
  src/components/dropdown/dropdown-item.js
  src/components/dropdown/dropdown-item.spec.js
  src/components/dropdown/package.json
  src/components/embed/README.md
  src/components/form-datepicker/README.md
  src/components/form-datepicker/form-datepicker.js
  src/components/form-datepicker/package.json
  src/components/form-spinbutton/README.md
  src/components/form-spinbutton/package.json
  src/components/form-timepicker/form-timepicker.js
  src/components/form-timepicker/package.json
  src/components/index.d.ts
  src/components/index.js
  src/components/modal/package.json
  src/components/navbar/README.md
  src/components/navbar/navbar-toggle.js
  src/components/navbar/navbar-toggle.spec.js
  src/components/navbar/package.json
  src/directives/toggle/toggle.js
  src/index.js
  yarn.lock
Labels: PR: Minor

#5036 fix(types): add missing declaration for `b-form-timepicker` (closes #5035)
  src/components/form-datepicker/index.d.ts
  src/components/form-spinbutton/index.d.ts
  src/components/form-timepicker/index.d.ts
  src/components/index.d.ts
  src/components/time/index.d.ts
Labels: PR: Patch, Type: Fix

#5039 fix(b-card): handle `header-html` and `footer-html` props correctly (fixes #5038)
  src/components/card/card.js
Labels: PR: Patch, Type: Fix

#5021 feat(b-sidebar): new custom component `<b-sidebar>` (closes #3324, #3210, #1702)
  docs/assets/scss/styles.scss
  src/_variables.scss
  src/components/form-timepicker/form-timepicker.js
  src/components/index.d.ts
  src/components/index.js
  src/components/index.scss
  src/components/modal/modal.js
  src/components/sidebar/README.md
  src/components/sidebar/_sidebar.scss
  src/components/sidebar/index.d.ts
  src/components/sidebar/index.js
  src/components/sidebar/index.scss
  src/components/sidebar/package.json
  src/components/sidebar/sidebar.js
  src/components/sidebar/sidebar.spec.js
  src/components/tooltip/helpers/bv-tooltip.js
  src/index.js
  src/utils/config-defaults.js
Labels: PR: Minor, Type: Custom Component, Type: Feature

#5030 feat: use `emitOnRoot()` wherever possible and remove unused chainable support
  src/components/collapse/collapse.js
  src/components/navbar/navbar-toggle.js
  src/components/toast/toast.js
  src/mixins/listen-on-root.js
Labels: PR: Patch, Type: Enhancement

#5049 chore(docs): fix typo in toast docs
  src/components/toast/README.md
Labels: Type: Docs
