Repository bootstrap-vue/bootstrap-vue, pull requests merged in 2020-04, with the labels that each got.

#5056 fix(b-avatar): remove duplicate button variant class
  src/components/avatar/avatar.js
Labels: PR: Patch, Type: Fix

#5059 chore(docs): update dev docs url to `bootstrap-vue.netlify.app`
  docs/components/header.vue
Labels: PR: Patch, Type: Docs

#5063 chore(docs): minor update to the sidebar docs
  src/components/sidebar/README.md
Labels: PR: Patch, Type: Docs

#5067 fix(table): fix `currentPage` value in slot `context` (closes #5065)
  src/components/table/helpers/mixin-items.js
Labels: PR: Patch, Type: Fix

#5064 feat(b-avatar): if img `src` fails to load, show icon or text or fallback icon
  src/components/avatar/README.md
  src/components/avatar/avatar.js
  src/components/avatar/avatar.spec.js
  src/components/avatar/package.json
Labels: PR: Minor, Type: Enhancement

#5076 fix(b-avatar): remove default padding when in button mode (fixes #5073)
  src/components/avatar/_avatar.scss
Labels: PR: Patch, Type: Fix, Type: SCSS

#5077 chore: patch release 2.10.1
  CHANGELOG.md
  package.json
  src/components/avatar/_avatar.scss
  src/components/sidebar/README.md
  src/components/table/helpers/mixin-items.js
  yarn.lock
Labels: PR: Patch

#5091 chore(docs): expand button-only example to show use of context event
  src/components/form-datepicker/README.md
Labels: PR: Patch, Type: Docs

#5094 chore: regenerate `yarn.lock` to fix potential security vulnerability
  yarn.lock
Labels: PR: Patch, Type: Security

#5103 fi(tooltip/popover): handle `click blur` on iOS webkit browsers (fixes #5099)
  src/components/tooltip/helpers/bv-tooltip.js
Labels: PR: Patch, Status: Browser Bug, Type: Fix

#5104 chore(tooltip, popover): add tests for modal close event
  src/components/tooltip/helpers/bv-tooltip.js
  src/components/tooltip/tooltip.spec.js
Labels: PR: Patch, Type: Unit Testing

#5106 chore(docs): update tabs docs examples for additional ARIA markup
  docs/components/header.vue
  src/components/card/README.md
  src/components/tabs/README.md
Labels: Type: Accessibility, Type: Docs

#5107 fix(b-link): don't render `target` or `rel` attrs when `router-tag` other than `a` or `area` provided
  src/components/link/link.js
Labels: PR: Patch, Type: Fix

#5079 feat(b-avatar): if img `src` fails to load, then show icon, text or fallback icon
  src/components/avatar/README.md
  src/components/avatar/avatar.js
  src/components/avatar/avatar.spec.js
  src/components/avatar/package.json
Labels: PR: Minor, Type: Feature

#5108 fix(b-calendar, b-form-datepicker): handle keyboard navigation when selected date is out of range (fixes #5057)
  src/components/calendar/calendar.js
Labels: Type: Accessibility, Type: Fix

#5109 docs: fixed documentation typos for Hover directive
  src/directives/hover/README.md
Labels: PR: Patch, Type: Docs

#5112 feat(b-calendar, b-form-datepicker): add optional decade navigation buttons (addresses #4976)
  src/components/avatar/README.md
  src/components/button-toolbar/README.md
  src/components/button/README.md
  src/components/calendar/README.md
  src/components/calendar/calendar.js
  src/components/calendar/calendar.spec.js
  src/components/calendar/package.json
  src/components/dropdown/README.md
  src/components/form-datepicker/README.md
  src/components/form-datepicker/form-datepicker.js
  src/components/form-datepicker/package.json
  src/components/form-tags/README.md
  src/components/form-timepicker/README.md
  src/components/modal/README.md
  src/components/overlay/README.md
  src/components/pagination-nav/README.md
  src/components/pagination/README.md
  src/components/popover/README.md
  src/components/sidebar/README.md
  src/components/table/README.md
  src/components/tabs/README.md
  src/directives/popover/README.md
  src/utils/config-defaults.js
  src/utils/date.js
  src/utils/date.spec.js
Labels: PR: Minor, Type: Feature

#5116 chore(b-form-file): additional unit tests
  src/components/form-file/form-file.js
  src/components/form-file/form-file.spec.js
Labels: PR: Patch, Type: Unit Testing

#5113 chore: bump version and update changelog
  CHANGELOG.md
  package.json
Labels: PR: Minor

#5105 chore: release 2.11.0
  CHANGELOG.md
  docs/components/header.vue
  package.json
  src/components/avatar/README.md
  src/components/avatar/avatar.js
  src/components/avatar/avatar.spec.js
  src/components/avatar/package.json
  src/components/button-toolbar/README.md
  src/components/button/README.md
  src/components/calendar/README.md
  src/components/calendar/calendar.js
  src/components/calendar/calendar.spec.js
  src/components/calendar/package.json
  src/components/card/README.md
  src/components/dropdown/README.md
  src/components/form-datepicker/README.md
  src/components/form-datepicker/form-datepicker.js
  src/components/form-datepicker/package.json
  src/components/form-file/form-file.js
  src/components/form-file/form-file.spec.js
  src/components/form-tags/README.md
  src/components/form-timepicker/README.md
  src/components/link/link.js
  src/components/modal/README.md
  src/components/modal/modal.spec.js
  src/components/overlay/README.md
  src/components/pagination-nav/README.md
  src/components/pagination/README.md
  src/components/popover/README.md
  src/components/sidebar/README.md
  src/components/table/README.md
  src/components/tabs/README.md
  src/components/tooltip/helpers/bv-tooltip.js
  src/components/tooltip/tooltip.spec.js
  src/directives/hover/README.md
  src/directives/popover/README.md
  src/utils/config-defaults.js
  src/utils/date.js
  src/utils/date.spec.js
  yarn.lock
Labels: PR: Minor

#5120 chore(docs): fix unmatched backquotes
  docs/markdown/intro/README.md
Labels: Type: Docs

#5121 feat(custom components): avoid using padding/margin utility classes where possible (closes #5117)
  src/_custom-controls.scss
  src/components/avatar/README.md
  src/components/calendar/README.md
  src/components/calendar/_calendar.scss
  src/components/calendar/calendar.js
  src/components/form-datepicker/README.md
  src/components/form-spinbutton/README.md
  src/components/form-spinbutton/_spinbutton.scss
  src/components/form-spinbutton/form-spinbutton.js
  src/components/form-timepicker/README.md
  src/components/form-timepicker/form-timepicker.js
  src/components/time/README.md
  src/components/time/_time.scss
  src/components/time/time.js
  src/utils/bv-form-btn-label-control.js
Labels: PR: Minor, Type: Enhancement, Type: Refactor, Type: SCSS

#5122 feat(icons): new `throb` and `fade` animations
  src/_variables.scss
  src/icons/README.md
  src/icons/_icons.scss
  src/icons/icons.d.ts
  src/icons/icons.js
  src/icons/package.json
  src/icons/plugin.js
Labels: PR: Minor, Type: Enhancement, Type: SCSS

#5139 docs(layout): add table for container width values
  src/components/layout/README.md
Labels: PR: Patch, Type: Docs

#5123 chore: update pull request template
  .github/PULL_REQUEST_TEMPLATE.md
Labels: PR: Patch

#5124 feat(b-avatar): and support for badges on avatars
  src/_custom-controls.scss
  src/components/avatar/README.md
  src/components/avatar/_avatar.scss
  src/components/avatar/avatar.js
  src/components/avatar/avatar.spec.js
  src/components/avatar/package.json
  src/components/time/_time.scss
  src/utils/config-defaults.js
Labels: PR: Minor, Type: Feature

#5132 feat(b-form-rating): new `b-form-rating` custom component
  src/components/form-rating/README.md
  src/components/form-rating/_form-rating.scss
  src/components/form-rating/form-rating.js
  src/components/form-rating/form-rating.spec.js
  src/components/form-rating/index.d.ts
  src/components/form-rating/index.js
  src/components/form-rating/index.scss
  src/components/form-rating/package.json
  src/components/index.d.ts
  src/components/index.js
  src/components/index.scss
  src/components/layout/README.md
  src/index.js
  src/utils/config-defaults.js
Labels: PR: Minor, Type: Custom Component, Type: Feature

#5143 chore(docs): minor tweaks to the layout and grid docs
  src/components/layout/README.md
Labels: PR: Patch, Type: Docs

#5142 chore(b-form-rating): remove focus outline from icons
  src/components/form-rating/_form-rating.scss
Labels: PR: Patch

#5140 chore(docs): remove new tags from things that aren't so new any more
  src/components/calendar/package.json
  src/components/form-datepicker/package.json
  src/components/form-timepicker/package.json
  src/components/overlay/package.json
  src/components/time/package.json
Labels: Type: Docs

#5126 chore(CI): switch to GitHub Actions and add BundleWatch
  .bundlewatch.config.json
  .circleci/config.yml
  .github/workflows/test.yml
  package.json
  src/components/calendar/calendar.js
  src/components/carousel/carousel-slide.js
  src/components/carousel/carousel.js
  src/components/collapse/collapse.js
  src/components/form-datepicker/form-datepicker.spec.js
  src/components/form-file/form-file.js
  src/components/form-input/form-input.js
  src/components/form-spinbutton/form-spinbutton.js
  src/components/form-tags/form-tags.js
  src/components/media/media-aside.js
  src/components/modal/modal.js
  src/components/overlay/overlay.js
  src/components/pagination-nav/pagination-nav.js
  src/components/pagination/pagination.js
  src/components/popover/helpers/bv-popover-template.js
  src/components/sidebar/sidebar.js
  src/components/table/helpers/mixin-bottom-row.js
  src/components/table/helpers/mixin-busy.js
  src/components/table/helpers/mixin-empty.js
  src/components/table/helpers/mixin-items.js
  src/components/table/helpers/mixin-provider.js
  src/components/table/helpers/mixin-sorting.js
  src/components/table/helpers/mixin-tbody-row.js
  src/components/table/helpers/mixin-tbody.js
  src/components/table/helpers/mixin-thead.js
  src/components/table/helpers/sanitize-row.js
  src/components/table/helpers/stringify-record-values.js
  src/components/table/helpers/text-selection-active.js
  src/components/table/tbody.js
  src/components/table/td.js
  src/components/table/tfoot.js
  src/components/table/thead.js
  src/components/table/tr.js
  src/components/tabs/tabs.js
  src/components/time/time.js
  src/components/toast/toast.js
  src/components/tooltip/helpers/bv-popper.js
  src/components/tooltip/helpers/bv-tooltip-template.js
  src/components/tooltip/helpers/bv-tooltip.js
  src/directives/popover/popover.js
  src/directives/scrollspy/scrollspy.class.js
  src/directives/scrollspy/scrollspy.js
  src/directives/visible/visible.js
  src/mixins/dropdown.js
  src/mixins/form-selection.js
  src/mixins/form-size.js
  src/mixins/form-validity.js
  src/mixins/form.js
  src/mixins/pagination.js
  src/utils/bv-form-btn-label-control.js
  src/utils/config-set.js
  src/utils/dom.js
  src/utils/env.js
  yarn.lock
Labels: CI, Type: Enhancement

#5146 chore(form-options-mixin): handle edge case where null/falsey passed to options prop
  src/mixins/form-options.js
Labels: Type: Enhancement, Type: Refactor

#5147 feat(b-calendar, b-form-datepicker): add scoped slots for date navigation buttons (closes #5117)
  src/components/calendar/README.md
  src/components/calendar/calendar.js
  src/components/calendar/package.json
  src/components/form-datepicker/README.md
  src/components/form-datepicker/form-datepicker.js
  src/components/form-datepicker/package.json
  src/utils/object.js
  src/utils/object.spec.js
Labels: PR: Minor, Type: Feature

#5150 feat(b-form-datepicker): add pass through prop `date-info-fn` (closes #4826)
  src/components/form-datepicker/form-datepicker.js
  src/components/form-datepicker/package.json
Labels: PR: Minor, Type: Feature

#5156 feat(b-avatar): if variant is empty string, then remove spacing around image (closes #5154)
  src/components/avatar/README.md
  src/components/avatar/avatar.js
Labels: PR: Minor, Type: Enhancement

#5157 chore: set `CI_BRANCH_BASE` for BundleWatch to pick up the correct compare branch
  .github/workflows/test.yml
Labels: CI, Type: Fix

#5158 fix(b-alert): memory leak by using the correct method to clear the countdown timeout
  src/components/alert/alert.js
Labels: PR: Patch, Type: Fix

#5159 fix(b-form-datepicker): make datepicker respect `no-highlight-today` prop
  src/components/form-datepicker/form-datepicker.js
Labels: PR: Patch, Type: Fix

#5177 fix(b-avatar): fix button type font size inheritance
  src/components/avatar/_avatar.scss
Labels: PR: Patch, Type: Fix, Type: SCSS

#5168 chore(docs): handle Zeit Now deploy previews
  docs/components/footer.vue
  docs/components/header.vue
  docs/nuxt.config.js
Labels: PR: Patch, Type: Docs

#5175 feat(b-calendar, b-form-datepicker): add prop `weekday-header-format` to specify weekday header length (closes #5171)
  src/components/calendar/README.md
  src/components/calendar/calendar.js
  src/components/calendar/package.json
  src/components/form-datepicker/README.md
  src/components/form-datepicker/form-datepicker.js
  src/components/form-datepicker/package.json
Labels: PR: Minor, Type: Feature

#5179 fix(b-calendar): use `Intl.NumberFormat` for formatting the number in the date buttons (closes #5171)
  src/components/calendar/calendar.js
Labels: PR: Patch, Type: Enhancement, Type: Fix

#5155 docs: add themes and dashboards page
  README.md
  docs/components/bv-logo.vue
  docs/components/componentdoc.vue
  docs/components/feedback.js
  docs/components/footer.vue
  docs/components/header.vue
  docs/components/sidebar.vue
  docs/content/index.js
  docs/markdown/intro/README.md
  docs/markdown/reference/changelog/README.md
  docs/markdown/reference/changelog/meta.json
  docs/markdown/reference/contributing/README.md
  docs/markdown/reference/contributing/meta.json
  docs/markdown/reference/settings/README.md
  docs/markdown/reference/settings/meta.json
  docs/markdown/reference/theming/README.md
  docs/markdown/reference/third-party/README.md
  docs/markdown/reference/third-party/meta.json
  docs/nuxt.config.js
  docs/pages/docs/layout.js
  docs/pages/docs/misc/_slug.js
  docs/pages/docs/misc/changelog.js
  docs/pages/docs/misc/contributing.js
  docs/pages/docs/misc/index.js
  docs/pages/docs/misc/settings.js
  docs/pages/docs/misc/third-party.js
  docs/pages/docs/reference/_slug.js
  docs/pages/index.vue
  docs/pages/themes.vue
  docs/plugins/docs-mixin.js
  docs/plugins/docs.js
  src/components/layout/README.md
Labels: Type: Docs

#5182 feat(b-sidebar): add optional backdrop support
  docs/assets/scss/styles.scss
  src/components/modal/modal.js
  src/components/sidebar/README.md
  src/components/sidebar/_sidebar.scss
  src/components/sidebar/package.json
  src/components/sidebar/sidebar.js
  src/components/sidebar/sidebar.spec.js
  src/utils/dom.js
Labels: PR: Minor, Type: Feature

#5188 chore: migrate to new domain
  .eslintignore
  .github/ISSUE_TEMPLATE/BUG_REPORT_TEMPLATE.md
  .gitignore
  .prettierignore
  CHANGELOG-OLD.md
  CHANGELOG.md
  CONTRIBUTING.md
  README.md
  docs/components/header.vue
  docs/markdown/reference/starter-templates/README.md
  docs/nuxt.config.js
  package.json
  scripts/icons.scss
  scripts/index.scss
  src/utils/plugins.js
Labels: Type: Docs

#5189 chore: improve CI workflow
  .github/workflows/test.yml
  docs/assets/scss/styles.scss
Labels: CI, PR: Patch, Type: Enhancement

#5191 chore(b-sidebar): only render the tab traps when the sidebar is open
  src/components/sidebar/sidebar.js
Labels: PR: Patch, Type: Accessibility

#5194 chore: fix docs header version dropdown
  docs/components/header.vue
Labels: Type: Docs, Type: Fix

#5201 chore: add support for CodeSandbox CI
  .codesandbox/ci.json
Labels: CI, Type: Enhancement

#5200 feat(b-form-rating): add `show-value-max` prop to show possible max rating when `show-value` is `true`
  src/components/form-rating/README.md
  src/components/form-rating/form-rating.js
  src/components/form-rating/form-rating.spec.js
  src/components/form-rating/package.json
Labels: PR: Minor, Type: Enhancement

#5198 chore(docs): add canonical url to head section
  docs/components/header.vue
  docs/constants.js
  docs/layouts/default.js
  docs/layouts/docs.js
  docs/nuxt.config.js
  docs/pages/themes.vue
Labels: PR: Patch, Type: Docs

#5211 fix(b-calendar, b-form-datepicker): minor adjustments to styling and example updates
  src/components/calendar/_calendar.scss
  src/components/form-datepicker/README.md
  src/components/form-datepicker/form-datepicker.js
Labels: PR: Patch, Type: Enhancement, Type: Fix

#5217 chore(docs): minor tweaks to the b-form-rating docs
  src/components/form-rating/README.md
  src/components/form-rating/package.json
Labels: PR: Patch, Type: Docs

#5207 fix(b-avatar): set `align-items: center` for default slot content (fixes: #5205)
  src/components/avatar/README.md
  src/components/avatar/_avatar.scss
Labels: PR: Patch, Type: Fix, Type: SCSS

#5219 chore: remove redundant `docs` workflow
  .github/workflows/test.yml
Labels: CI

#5224 chore(docs): add head meta and link tags to master branch
  docs/constants.js
  docs/layouts/default.js
  docs/layouts/docs.js
Labels: Type: Docs

#5228 chore(docs): minor adjustments to the form docs
  src/components/form/README.md
  src/components/input-group/README.md
Labels: PR: Patch, Type: Docs

#5238 fix(b-form-datepicker, b-form-timepicker): prevent duplicate validation icons (fixes #5237)
  src/_custom-controls.scss
Labels: PR: Patch, Type: Custom Component, Type: Fix, Type: SCSS

#5231 fix(b-form-datepicker, b-form-timepicker): adjust scss to support input-groups
  src/_custom-controls.scss
Labels: Type: Custom Component, Type: Fix, Type: SCSS

#5240 chore(docs): minor update to input-group docs
  src/components/input-group/README.md
Labels: PR: Patch

#5242 feat(b-calendar, b-form-datepicker): relax `YYYY-MM-DD` string parsing (closes #5232)
  src/utils/date.js
  src/utils/date.spec.js
Labels: PR: Minor, Type: Enhancement

#5241 chore(docs): minor tweaks for mobile friendliness
  docs/components/componentdoc.vue
  src/components/media/README.md
  src/components/table/package.json
Labels: Type: Docs

#5249 chore: overwrite Vercel now default headers
  .eslintignore
  .gitignore
  .prettierignore
  now.json
Labels: Type: Docs, Type: Temporary Fix

#5208 chore(docs): update Zeit references to Vercel
  docs/components/footer.vue
  docs/components/header.vue
  docs/nuxt.config.js
Labels: PR: Patch, Type: Docs

#5247 fix: handle nested form options normalization (closes #5245)
  src/components/form-select/helpers/mixin-options.js
  src/mixins/form-options.js
Labels: PR: Patch, Type: Fix

#5248 feat(b-overlay): add support for overlay `click` event (closes #5243)
  src/components/overlay/overlay.js
  src/components/overlay/overlay.spec.js
  src/components/overlay/package.json
Labels: PR: Minor, Type: Feature

#5252 fix(b-form-datepicker, b-form-timepicker): fix menu padding in button only mode (fixes #5251)
  src/_custom-controls.scss
  src/components/form-datepicker/form-datepicker.spec.js
  src/components/form-timepicker/form-timepicker.spec.js
  src/utils/bv-form-btn-label-control.js
Labels: PR: Patch, Type: Custom Component, Type: Fix, Type: SCSS

#5258 chore: minor refactors in code optimization for better minification
  src/components/aspect/aspect.js
  src/components/calendar/calendar.js
  src/components/carousel/carousel.js
  src/components/form-rating/form-rating.js
  src/components/form-spinbutton/form-spinbutton.js
  src/components/form-textarea/form-textarea.js
  src/components/layout/row.js
  src/components/pagination-nav/pagination-nav.js
  src/components/pagination/pagination.js
  src/components/progress/progress-bar.js
  src/components/table/helpers/mixin-items.js
  src/components/table/helpers/mixin-pagination.js
  src/components/table/helpers/mixin-selectable.js
  src/components/tabs/tabs.js
  src/components/toast/toast.js
  src/components/tooltip/helpers/bv-tooltip.js
  src/directives/scrollspy/scrollspy.class.js
  src/directives/scrollspy/scrollspy.js
  src/icons/helpers/icon-base.js
  src/mixins/form-text.js
  src/mixins/pagination.js
  src/utils/math.js
Labels: PR: Patch, Type: Refactor

#5257 chore(docs): add generated robots.txt and sitemap.xml for SEO
  docs/nuxt.config.js
  package.json
  yarn.lock
Labels: PR: Patch, Type: Docs

#5265 fix(types): update table field definition types to include sticky column (fixes #5263)
  src/components/table/index.d.ts
Labels: Type: Fix, Type: Types

#5264 chore(docs): update footer with new information
  docs/assets/powered-by-vercel.svg
  docs/components/footer.vue
Labels: Type: Docs

#5271 chore(docs): fix typos
  docs/components/contributors.vue
  docs/pages/themes.vue
  src/components/avatar/README.md
  src/components/calendar/calendar.js
  src/components/card/card-img-lazy.spec.js
  src/components/card/card-img.spec.js
  src/components/form-datepicker/README.md
  src/components/form-rating/README.md
  src/components/form-spinbutton/README.md
  src/components/form-timepicker/README.md
  src/components/form-timepicker/form-timepicker.js
  src/components/modal/modal.spec.js
  src/components/popover/README.md
  src/components/sidebar/README.md
  src/components/table/README.md
  src/components/table/_table.scss
  src/components/table/helpers/mixin-thead.js
  src/components/table/table-filtering.spec.js
  src/components/table/table-sorting.spec.js
  src/components/time/README.md
  src/components/toast/README.md
  src/components/tooltip/README.md
  src/components/tooltip/helpers/bv-tooltip.js
  src/directives/tooltip/README.md
  src/mixins/dropdown.js
  src/mixins/form-text.js
  src/mixins/has-listener.js
  src/utils/bv-collapse.js
  src/utils/config-defaults.js
  src/utils/observe-dom.js
Labels: PR: Patch, Type: Docs

#5268 chore: add partners section to repo readme
  README.md
  static/powered-by-vercel.svg
Labels: PR: Patch

#5279 fix(b-table, b-table-lite, b-table-simple): handle header variant for sticky columns (fixes #5278)
  src/components/table/tbody.js
  src/components/table/td.js
  src/components/table/tfoot.js
  src/components/table/th.js
  src/components/table/thead.js
  src/components/table/tr.js
Labels: PR: Patch, Type: Fix

#5282 chore(docs): add partners section to landing page
  docs/assets/vercel.svg
  docs/pages/index.vue
Labels: PR: Patch
