Repository bootstrap-vue/bootstrap-vue, pull requests merged in 2021-05, with the labels that each got.

#6582 chore: update dependencies (closes #6412, #6429, #6430, #6436, #6522)
  .github/dependabot.yml
  .husky/.gitignore
  .husky/pre-commit
  docs/nuxt.config.js
  docs/utils/marked-loader.js
  package.json
  src/components/dropdown/dropdown.spec.js
  src/components/form-checkbox/form-checkbox.spec.js
  src/components/form-input/form-input.spec.js
  src/components/form-radio/form-radio.spec.js
  src/components/form-rating/form-rating.spec.js
  src/components/form-spinbutton/form-spinbutton.js
  src/components/form-tags/form-tags.spec.js
  src/components/form-textarea/form-textarea.spec.js
  src/components/tabs/tabs.spec.js
  src/mixins/listeners.spec.js
  yarn.lock
Labels: Type: CI, Type: Chore, Type: Dependencies

#6583 chore(icons): update Bootstrap Icons to v1.4.1 (closes #6472)
  .bundlewatch.config.json
  package.json
  src/icons/README.md
  src/icons/icons.d.ts
  src/icons/icons.js
  src/icons/package.json
  src/icons/plugin.js
  yarn.lock
Labels: Bootstrap Icons, PR: Minor, Type: Dependencies

#6587 chore: update dependencies (closes #6584, #6586)
  .eslintrc.js
  .github/dependabot.yml
  package.json
  yarn.lock
Labels: Type: Chore, Type: Dependencies

#6592 chore(ci): update workflows to new Node.js versions
  .github/workflows/build.yml
  .github/workflows/codeql.yml
  .github/workflows/test.yml
Labels: Type: CI, Type: Chore

#6511 fix(utils/dom): bind `requestAF()` to `window` (#6508)
  src/utils/dom.js
Labels: PR: Patch, Type: Fix

#6594 chore(docs): fix typo in `<b-carousel>` docs (closes #6593)
  src/components/carousel/README.md
Labels: Type: Docs

#6466 chore(docs): add new "Vuexy - Admin Dashboard" theme
  docs/content/themes/vuexy-admin-dashboard.yaml
Labels: Type: Docs, Type: Themes

#6603 fix(b-table): set `aria-sort` when using `sortKey` and `no-local-sorting` (closes #6602)
  src/components/table/helpers/mixin-sorting.js
  src/components/table/table-sorting.spec.js
Labels: PR: Patch, Type: Fix

#6611 chore(icons): update Bootstrap Icons to v1.5.0
  .bundlewatch.config.json
  package.json
  src/icons/README.md
  src/icons/icons.d.ts
  src/icons/icons.js
  src/icons/package.json
  src/icons/plugin.js
  yarn.lock
Labels: Bootstrap Icons, PR: Minor, Type: Dependencies, Type: Security
