Repository bootstrap-vue/bootstrap-vue, pull requests merged in 2021-02, with the labels that each got.

#6389 fix(b-input-tags): not respecting custom `$input-color` (closes #6388)
  src/components/form-tags/_form-tags.scss
Labels: PR: Patch, Type: Fix, Type: SCSS

#6390 feat(b-form-tags) added `focus` & `blur` events (closes #5947)
  src/components/form-tags/form-tags.js
  src/components/form-tags/form-tags.spec.js
Labels: PR: Minor, Type: Enhancement

#6346 fix(b-form-group): remove `role="alert"` from valid/invalid feedback (closes #6300, #6307)
  src/components/form-group/form-group.js
  src/components/form-group/form-group.spec.js
Labels: PR: Patch, Type: Accessibility, Type: Fix

#6395 feat(b-form-tags): adds `focusin` & `focusout` to wrapper and prevents firing multiple `focus`/`blur` events
  src/components/form-input/package.json
  src/components/form-tags/form-tags.js
  src/components/form-tags/form-tags.spec.js
  src/components/form-tags/package.json
  src/components/form-textarea/package.json
  src/components/tooltip/helpers/bv-tooltip.js
  src/constants/events.js
Labels: PR: Minor, Type: Enhancement

#6403 feat(b-skeleton): move `.b-skeleton-animate-wave` properties into SCSS variables (closes #6398)
  src/_variables.scss
  src/components/skeleton/_skeleton.scss
Labels: PR: Minor, Type: Enhancement, Type: SCSS

#6408 chore(deps): update dependencies an regenerate `yarn.lock`
  package.json
  yarn.lock
Labels: Type: Chore, Type: Dependencies
