Repository bootstrap-vue/bootstrap-vue, pull requests merged in 2021-01, with the labels that each got.

#6276 chore: bump version to v2.21.2
  CHANGELOG.md
  package.json
  src/icons/icons.d.ts
  src/icons/icons.js
  src/icons/plugin.js
Labels: PR: Patch, Type: Chore

#6277 chore: release v2.21.2
  .codesandbox/ci.json
  .github/workflows/build.yml
  .github/workflows/test.yml
  CHANGELOG.md
  docs/markdown/intro/README.md
  docs/markdown/reference/theming/README.md
  package.json
  src/components/collapse/helpers/bv-collapse.js
  src/components/dropdown/README.md
  src/components/dropdown/dropdown-group.js
  src/components/dropdown/dropdown-header.js
  src/components/dropdown/dropdown-item.js
  src/components/form-btn-label-control/_form-btn-label-control.scss
  src/components/form-btn-label-control/bv-form-btn-label-control.js
  src/components/form-file/README.md
  src/components/form-select/package.json
  src/components/form-textarea/package.json
  src/components/nav/nav-form.js
  src/components/nav/nav-item.js
  src/components/sidebar/_sidebar.scss
  src/components/table/README.md
  src/components/table/helpers/mixin-caption.js
  src/components/table/helpers/mixin-table-renderer.js
  src/components/table/table-lite.spec.js
  src/components/table/table.spec.js
  src/constants/env.js
  src/icons/helpers/icon-base.js
  src/icons/helpers/make-icon.js
  src/icons/icon.js
  src/icons/icons.d.ts
  src/icons/icons.js
  src/icons/iconstack.js
  src/icons/package.json
  src/icons/plugin.js
  yarn.lock
Labels: PR: Patch, Type: Chore

#6280 chore(docs): fix typo in `<b-table>` docs
  src/components/table/README.md
Labels: Type: Docs

#6296 chore(docs): align navigation with section titles
  CHANGELOG-OLD.md
  docs/assets/css/docs.min.css.map
  src/components/alert/README.md
  src/components/badge/README.md
  src/components/button-group/README.md
  src/components/button-toolbar/README.md
  src/components/button/README.md
  src/components/card/README.md
  src/components/dropdown/README.md
  src/components/embed/README.md
  src/components/form-checkbox/README.md
  src/components/form-file/README.md
  src/components/form-group/README.md
  src/components/form-input/README.md
  src/components/form-radio/README.md
  src/components/form-textarea/README.md
  src/components/form/README.md
  src/components/image/README.md
  src/components/input-group/README.md
  src/components/link/README.md
  src/components/list-group/README.md
  src/components/list-group/package.json
  src/components/modal/README.md
  src/components/nav/README.md
  src/components/navbar/README.md
  src/components/pagination-nav/README.md
  src/components/spinner/README.md
  src/components/table/README.md
  src/components/toast/README.md
  src/components/toast/package.json
  src/components/tooltip/README.md
  src/directives/popover/README.md
  src/directives/scrollspy/README.md
  src/directives/scrollspy/helpers/bv-scrollspy.class.js
  src/directives/scrollspy/scrollspy.js
  src/directives/tooltip/README.md
  src/icons/README.md
  src/icons/package.json
Labels: Type: Docs

#6298 chore(icons): update Bootstrap Icons to v1.3.0
  .bundlewatch.config.json
  package.json
  src/icons/README.md
  src/icons/icons.d.ts
  src/icons/icons.js
  src/icons/package.json
  src/icons/plugin.js
  yarn.lock
Labels: Bootstrap Icons, PR: Minor, Type: Dependencies

#6299 chore(docs): fix typo in `<b-button>`section
  src/components/button-group/README.md
Labels: Type: Docs

#6302 fix(b-img-lazy): prefer computed props over user supplied ones
  src/components/image/img-lazy.js
Labels: PR: Patch, Type: Fix

#6341 fix(b-icon): correct incorrect SCSS variable
  src/icons/_icons.scss
Labels: PR: Patch, Type: Fix, Type: SCSS

#6342 chore(docs): correct title case for references to "Getting Started" section
  docs/components/footer.vue
  docs/content.js
Labels: Type: Docs

#6339 feat(b-dropdown): add `toggle-attrs` prop (closes #3694)
  src/components/dropdown/dropdown.js
  src/components/dropdown/dropdown.spec.js
  src/components/dropdown/package.json
Labels: PR: Minor, Type: Enhancement

#6345 fix(b-form-input/b-form-textarea): legacy browser support (closes #6283)
  src/utils/props.js
Labels: PR: Patch, Type: Fix

#6347 feat(b-form-tags): add `feedback-aria-live` prop
  src/components/form-tags/form-tags.js
  src/components/form-tags/form-tags.spec.js
  src/components/form-tags/package.json
Labels: PR: Minor, Type: Accessibility, Type: Enhancement

#6349 fix(b-img-lazy): `blank` placeholder for Firefox (closes #6320)
  src/components/image/img-lazy.js
Labels: PR: Patch, Type: Fix

#6355 fix(b-table): add missing `sortKey` field type and correct a typo (closes #6352)
  src/components/table/index.d.ts
Labels: PR: Patch, Type: Fix, Type: Types

#6356 chore(refactor): unify event variable names
  src/components/collapse/collapse.js
  src/components/modal/README.md
  src/components/modal/helpers/bv-modal.js
  src/components/modal/modal.js
  src/components/navbar/navbar-toggle.js
  src/components/pagination-nav/pagination-nav.js
  src/components/pagination/pagination.js
  src/components/table/helpers/mixin-tbody-row.js
  src/components/table/helpers/mixin-tbody.js
  src/components/tabs/tabs.js
  src/components/toast/toast.js
  src/components/tooltip/helpers/bv-tooltip.js
  src/mixins/click-out.spec.js
  src/mixins/focus-in.spec.js
Labels: Type: Refactor

#6366 fix(b-form-radio-group) make sure to pass state to form radio options for contextual feedback (closes #6357)
  src/components/form-checkbox/form-checkbox-group.spec.js
  src/components/form-radio/form-radio-group.spec.js
  src/components/form-radio/form-radio.js
  src/mixins/form-radio-check-group.js
Labels: PR: Patch, Type: Fix

#6368 chore(docs): make sure the clicked anchor target is reflected in URL (closes #6288)
  docs/components/quick-links.vue
  docs/components/section.js
  docs/components/toc.vue
  docs/utils/index.js
Labels: PR: Patch, Type: Docs, Type: Fix

#6367 fix(b-dropdown): decrease delay when hiding inside a navbar on no-touch devices (closes #6306)
  src/mixins/dropdown.js
Labels: PR: Patch, Type: Fix

#6371 fix(b-table): header cell overflow for `.sr-only` sort label (closes #6326)
  src/components/table/helpers/mixin-sorting.js
  src/components/table/helpers/mixin-thead.js
Labels: PR: Patch, Type: Fix

#6374 fix(b-link): remove default values from `vue-router` pass-down props (closes #6373)
  src/components/link/link.js
Labels: PR: Patch, Type: Fix

#6372 fix(b-table): add missing `role="grid"` when selectable (closes #6305)
  src/components/table/helpers/mixin-selectable.js
  src/components/table/table-selectable.spec.js
Labels: PR: Patch, Type: Accessibility, Type: Fix

#6375 feat: add `header-tag` and `footer-tag` props to all components with header and footer (closes #6321)
  src/components/calendar/calendar.js
  src/components/calendar/calendar.spec.js
  src/components/calendar/package.json
  src/components/modal/modal.js
  src/components/modal/modal.spec.js
  src/components/modal/package.json
  src/components/sidebar/package.json
  src/components/sidebar/sidebar.js
  src/components/sidebar/sidebar.spec.js
  src/components/time/package.json
  src/components/time/time.js
  src/components/time/time.spec.js
  src/components/toast/package.json
  src/components/toast/toast.js
  src/components/toast/toast.spec.js
Labels: PR: Minor, Type: Accessibility, Type: Enhancement

#6381 chore(refactor): move away from lifecycle hook listeners
  src/components/form-tags/form-tags.js
  src/components/modal/helpers/modal-manager.js
  src/components/modal/modal.js
  src/components/toast/toaster.js
  src/mixins/form-text.js
  src/mixins/listen-on-document.js
  src/mixins/listen-on-root.js
  src/mixins/listen-on-root.spec.js
  src/mixins/listen-on-window.js
Labels: PR: Patch, Type: Chore, Type: Refactor

#6382 fix(b-table): prefer user-provided `role` attribute
  src/components/table/helpers/mixin-selectable.js
Labels: PR: Patch, Type: Fix

#6383 fix(b-table): default `role` to `grid` when `selectable` and `table` otherwise
  src/components/table/helpers/mixin-selectable.js
  src/components/table/helpers/mixin-table-renderer.js
  src/components/table/table-selectable.spec.js
Labels: Type: Accessibility, Type: Enhancement
